### ISSUE TITLE
Implement ISO DIS layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#100]
Identical to the FDIS layout, except:

- usage of the word "DRAFT" instead of "FINAL DRAFT"
- additional warning message on front cover: "THIS DOCUMENT IS A DRAFT CIRCULATED FOR COMMENT AND APPROVAL. IT IS THEREFORE SUBJECT TO CHANGE AND MAY NOT BE REFERRED TO AS AN INTERNATIONAL STANDARD UNTIL PUBLISHED AS SUCH."

FDIS:
<img width="594" alt="Screen Shot 2020-04-01 at 4 33 02 PM" src="https://user-images.githubusercontent.com/11865/78116140-764c7680-7436-11ea-86dd-4565ef8ed7d3.png">

DIS:

<img width="609" alt="Screen Shot 2020-04-01 at 4 33 21 PM" src="https://user-images.githubusercontent.com/11865/78116168-81070b80-7436-11ea-8398-220639e74ebb.png">

**Comment by ronaldtse** [comment]
The special content header should also apply like FDIS: https://github.com/metanorma/mn-native-pdf/issues/97#issuecomment-607120015

Except with the text changed from "FINAL DRAFT INTERNATIONAL STANDARD" to "DRAFT INTERNATIONAL STANDARD".

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Resulted PDF:
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.dis.pdf

**Comment by ronaldtse** [comment]
Pending same treatment as https://github.com/metanorma/mn-native-pdf/issues/97#issuecomment-611706749

**Comment by ronaldtse** [comment]
@Intelligent2013 Sorry I made a mistake with the DIS layout. The correct DIS layout is this:

<img width="529" alt="Screen Shot 2020-04-11 at 1 53 27 PM" src="https://user-images.githubusercontent.com/11865/79036561-d348e900-7bfb-11ea-89a8-f76fefc8f6d7.png">

These files are available on the internet for comparison:
https://www.apotekarsocieteten.se/wp-content/uploads/2020/02/Medical-devices-—-Symbols-to-be-used-with-medical-device-labels-labelling-and-information-to-be-supplied-—-EN-ISO-15223-1.pdf

https://dri.ca/docs/ISO_DIS_22301_(E).pdf

http://www.mikrobiologi.net/organization/document/prEN_ISO_15195_20180611.pdf

https://www.sis.se/api/document/preview/922057/

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Updated DIS:
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.dis.pdf
