### ISSUE TITLE
Applying the new ISO DIS layout to all CD/WD/NP/AWI

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#101]
We should apply the same DIS PDF layout to all other stages, like NP/AWI/CD/WD

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Resulted PDFs:
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.cd.pdf
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.wd.pdf
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.nwip.pdf
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.awi.pdf

**Comment by ronaldtse** [comment]
@Intelligent2013 this looks great! I have two more requests:

1. Instead of just "DRAFT" these documents are named:
CD: Committee Draft
WD: Working Draft
NWIP: New Work Item Proposal Draft
AWI: Approved Work Item

If you are not getting this information from the XML, please file a ticket against metanorma-iso.

2. Support "iterations":

Sometimes a draft can be identified multiple iterations (e.g. if a CD failed voting, then a new CD is prepared, and the new CD will be called 2CD).

So the draft name will be called: "Committee Draft", "Committee Draft 2", "Committee Draft 3"...

Same: If you are not getting this information from the XML, please file a ticket against metanorma-iso.

Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse 
> 1. Instead of just "DRAFT" these documents are named:

Asked a questions regarding document stages: https://github.com/metanorma/metanorma-iso/issues/342
But XSLT updated preliminary to using 'stage' element for determine stages.

> 2. Support "iterations":

Schema contains iteration element. Support added in xslt.
