### ISSUE TITLE
Develop IEC International Standard layout (samples and published cover)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#109]
Sample documents:

* https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf
* https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-3_2010.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-23.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-21.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-1.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-2.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-2.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-24.pdf
* http://www.nobelcert.com/DataFiles/FreeUpload/IEC%2060794-1-22.pdf
* https://ran-s3.s3.amazonaws.com/isa.org.jm/s3fs-public/files/documents/isoiec31010.pdf

Front covers:

<img width="532" alt="Screen Shot 2020-04-11 at 2 39 49 AM" src="https://user-images.githubusercontent.com/11865/79015156-d366cb80-7b9e-11ea-8329-723a2eb492c7.png">

<img width="532" alt="Screen Shot 2020-04-11 at 2 40 03 AM" src="https://user-images.githubusercontent.com/11865/79015162-d5c92580-7b9e-11ea-9e04-8f88aef667ef.png">

<img width="534" alt="Screen Shot 2020-04-11 at 2 39 58 AM" src="https://user-images.githubusercontent.com/11865/79015159-d5308f00-7b9e-11ea-98e5-d4dfa4356e0f.png">

Back cover:
<img width="535" alt="Screen Shot 2020-04-11 at 2 44 40 AM" src="https://user-images.githubusercontent.com/11865/79015170-dd88ca00-7b9e-11ea-850f-6035030961aa.png">

**Comment by ronaldtse** [comment]
This standard says "Basic EMC Publication", that's a special phrase. That has to be from the XML.

**Comment by ronaldtse** [comment]
<img width="542" alt="Screen Shot 2020-04-11 at 3 43 56 AM" src="https://user-images.githubusercontent.com/11865/79018569-adddc000-7ba6-11ea-9b47-fe2831104794.png">

Some other standards have a "HORIZONTAL STANDARD" label. We will need to handle this.

**Comment by Intelligent2013** [comment]
@ronaldtse I can't find this data in source XML:
- IEC 61000-4-5:2014-05(en-fr)
(standard name with year-month and  language code(s)), vertical text on 1st page
- COMMISSION ELECTROTECHNIQUE INTERNATIONALE
(publisher/author/owner name on french)
- price code
- ICS and ISBN data
- copyright statement on french
- the text on 2nd page (About the IEC... and below) is a static text?
- the text 'NORME INTERNATIONALE' is a static text for all documents? 
- how to determine when we should place text 'BASIC EMC PUBLICATION/PUBLICATION FONDAMENTALE EN CEM' and when 'HORIZONTAL STANDART'

**Comment by ronaldtse** [comment]
I believe all of these items are to be added in the source XML. I believe ICS is already included (if the author sets them).

> how to determine when we should place text 'BASIC EMC PUBLICATION/PUBLICATION FONDAMENTALE EN CEM' and when 'HORIZONTAL STANDARD'?

I don't know the answer to this either, but it seems that they are mutually exclusive -- these "Functions" are allowed:
* Basic EMC Publication
* Basic Safety Publication
* Basic Environment Publication
* Basic Quality Assurance Publication

If it is a Horizontal Standard, let's not show the Functions.

**Comment by Intelligent2013** [comment]
Done. Some data on cover pages are hardcoded, because in xml source (https://metanorma.github.io/mn-samples-iec/documents/iec-rice.xml) there aren't such data.

One more question - how to determine when we should display COLOUR INSIDE image?

**Comment by ronaldtse** [comment]
> Done. Some data on cover pages are hardcoded, because in xml source (https://metanorma.github.io/mn-samples-iec/documents/iec-rice.xml) there aren't such data.

Could you help file them in metanorma-iec? They should be provided by the XML.

> One more question - how to determine when we should display COLOUR INSIDE image?

I think there should be an attribute in the document that expresses this. e.g. document attribute like `:accessibility-color-inside: true`.

**Comment by Intelligent2013** [comment]
Task on hold (there are a dependent tasks).

**Comment by opoudjis** [comment]
Task no longer on hold

**Comment by Intelligent2013** [comment]
To do: update IEC xslt for collection xml processing (https://github.com/metanorma/metanorma-iec/issues/41#issuecomment-745294495)

**Comment by Intelligent2013** [comment]
Done.
