### ISSUE TITLE
IEC styling (table of contents)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#110]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf

<img width="534" alt="Screen Shot 2020-04-11 at 2 40 08 AM" src="https://user-images.githubusercontent.com/11865/79015225-f5604e00-7b9e-11ea-869d-af225cb9a73c.png">
<img width="534" alt="Screen Shot 2020-04-11 at 2 40 13 AM" src="https://user-images.githubusercontent.com/11865/79015234-f6917b00-7b9e-11ea-9fa7-881b81b59d02.png">
<img width="532" alt="Screen Shot 2020-04-11 at 2 40 17 AM" src="https://user-images.githubusercontent.com/11865/79015237-f72a1180-7b9e-11ea-9bee-72a543312225.png">
<img width="534" alt="Screen Shot 2020-04-11 at 2 40 21 AM" src="https://user-images.githubusercontent.com/11865/79015240-f7c2a800-7b9e-11ea-8336-31682af319ca.png">

French ToC:
<img width="537" alt="Screen Shot 2020-04-11 at 2 43 28 AM" src="https://user-images.githubusercontent.com/11865/79015266-0610c400-7b9f-11ea-983b-d398ce353cfd.png">
<img width="533" alt="Screen Shot 2020-04-11 at 2 43 33 AM" src="https://user-images.githubusercontent.com/11865/79015269-0741f100-7b9f-11ea-94d8-4c9f161add10.png">
<img width="533" alt="Screen Shot 2020-04-11 at 2 43 40 AM" src="https://user-images.githubusercontent.com/11865/79015270-07da8780-7b9f-11ea-9ec0-394cf8abe9f9.png">
<img width="536" alt="Screen Shot 2020-04-11 at 2 43 44 AM" src="https://user-images.githubusercontent.com/11865/79015274-08731e00-7b9f-11ea-9dd7-c0c8206849bf.png">
<img width="537" alt="Screen Shot 2020-04-11 at 2 43 51 AM" src="https://user-images.githubusercontent.com/11865/79015275-090bb480-7b9f-11ea-9d77-8a0d1224953a.png">

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Except ToC on French. Could you provide the XML example for document on two languages, please?

**Comment by ronaldtse** [comment]
@Intelligent2013 we don't have a dual language document yet, but it will be implemented as 2 separate documents with an identical structure.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we don't have a dual language document yet, but it will be implemented as 2 separate documents with an identical structure.

@ronaldtse 
I.e. should we:
1. process two XML and produce one PDF - with English part + French part ? (it's possible via xslt to process second XML from one xslt)
or
2. process two XML and produce two PDF - one on English, one on French ?

What is option do you prefer?

**Comment by ronaldtse** [comment]
It will be 1, where two XML => 1 PDF.

**Comment by Intelligent2013** [comment]
> It will be 1, where two XML => 1 PDF.

In this case I'll add an additional parameter 'param' (key-value, multiple for using in future, optional). These key-values will pass into xslt as external parameters. I.e. command line will be like this:
java -jar mn2pdf-1.13.jar  -x "iso,en.xml" -s iso.standard.xsl -o iso.pdf  --param "second-xml" "iso.fr.xml"

**Comment by Intelligent2013** [comment]
> It will be 1, where two XML => 1 PDF.

@ronaldtse Second xml will be always in French? Or can be on any language?
I ask about it, because in xslt there are a few language specific static texts like 'Content', 'Figure', 'Table', 'Equation',... And looks like I need to entry a dictionary for these terms:
Content ->Sommaire
Figure -> Figure
Table -> Tableau
Equation -> ...
...

**Comment by ronaldtse** [comment]
Great question. I think those keys have to be provided in the XML, because for later rendering we won’t be able to reproduce the same text depending on implementation.

**Comment by Intelligent2013** [comment]
> Great question. I think those keys have to be provided in the XML as a dictionary, because for later rendering we won’t be able to reproduce the same text depending on implementation.

@ronaldtse Should I create an issue on `metanorma` repository or somewhere else?

**Comment by ronaldtse** [comment]
Yes please @Intelligent2013 . Thanks!

**Comment by Intelligent2013** [comment]
In mn2pdf v1.18 (https://github.com/metanorma/mn2pdf/releases/download/v1.18/mn2pdf-1.18.jar) I've added a parameter 'param' to pass an external artifacts/parameters into xslt. So for produce PDF IEC on two languages you need to add `--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml` into command line, like this:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.18.jar   -x iec-rice.xml  -s iec.international-standard.xsl  -o  iec-rice.pdf  -d --param additionalXMLs=iec-rice.fr.xml
```

For 3- and more languages document just add comma separated values - paths to another xml files:
```
--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml
```
