### ISSUE TITLE
IEC styling (Foreword)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#111]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf

<img width="534" alt="Screen Shot 2020-04-11 at 2 40 26 AM" src="https://user-images.githubusercontent.com/11865/79015325-1e80de80-7b9f-11ea-9f78-86b4b3db3be2.png">
<img width="533" alt="Screen Shot 2020-04-11 at 2 40 30 AM" src="https://user-images.githubusercontent.com/11865/79015331-204aa200-7b9f-11ea-9e8c-47dd45446f16.png">

French foreword:
<img width="536" alt="Screen Shot 2020-04-11 at 2 43 55 AM" src="https://user-images.githubusercontent.com/11865/79015465-5e47c600-7b9f-11ea-9396-07a94b076ba9.png">
<img width="534" alt="Screen Shot 2020-04-11 at 2 43 59 AM" src="https://user-images.githubusercontent.com/11865/79015473-61db4d00-7b9f-11ea-94c0-8c1e42b94196.png">

**Comment by Intelligent2013** [comment]
@ronaldtse This example is a two languages document. What is aт xml structure of such documents?

**Comment by Intelligent2013** [comment]
Done. Except content on French.

**Comment by Intelligent2013** [comment]
In mn2pdf v1.18 (https://github.com/metanorma/mn2pdf/releases/download/v1.18/mn2pdf-1.18.jar) I've added a parameter 'param' to pass an external artifacts/parameters into xslt. So for produce PDF IEC on two languages you need to add `--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml` into command line, like this:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.18.jar   -x iec-rice.xml  -s iec.international-standard.xsl  -o  iec-rice.pdf  -d --param additionalXMLs=iec-rice.fr.xml
```

For 3- and more languages document just add comma separated values - paths to another xml files:
```
--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml
```
