### ISSUE TITLE
IEC Styling (introduction and front pages)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#112]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf
<img width="537" alt="Screen Shot 2020-04-11 at 2 40 35 AM" src="https://user-images.githubusercontent.com/11865/79017608-5a6a7280-7ba4-11ea-9f29-39b20c9f2dc2.png">
<img width="535" alt="Screen Shot 2020-04-11 at 2 40 41 AM" src="https://user-images.githubusercontent.com/11865/79017615-5e969000-7ba4-11ea-999f-e10901ea003f.png">
<img width="534" alt="Screen Shot 2020-04-11 at 2 40 45 AM" src="https://user-images.githubusercontent.com/11865/79017618-5f2f2680-7ba4-11ea-8ffa-3fc437bafe4c.png">

<img width="535" alt="Screen Shot 2020-04-11 at 2 40 49 AM" src="https://user-images.githubusercontent.com/11865/79017621-60605380-7ba4-11ea-8ff0-44857dfdd267.png">

French portion:
<img width="542" alt="Screen Shot 2020-04-11 at 2 44 03 AM" src="https://user-images.githubusercontent.com/11865/79017644-6f470600-7ba4-11ea-923a-bbd6c3256672.png">
<img width="536" alt="Screen Shot 2020-04-11 at 2 44 07 AM" src="https://user-images.githubusercontent.com/11865/79017648-7110c980-7ba4-11ea-8ea9-97a8e0d4d343.png">
<img width="534" alt="Screen Shot 2020-04-11 at 2 44 11 AM" src="https://user-images.githubusercontent.com/11865/79017651-71a96000-7ba4-11ea-81a0-7c72021caee2.png">

**Comment by Intelligent2013** [comment]
Done.

**Comment by Intelligent2013** [comment]
In mn2pdf v1.18 (https://github.com/metanorma/mn2pdf/releases/download/v1.18/mn2pdf-1.18.jar) I've added a parameter 'param' to pass an external artifacts/parameters into xslt. So for produce PDF IEC on two languages you need to add `--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml` into command line, like this:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.18.jar   -x iec-rice.xml  -s iec.international-standard.xsl  -o  iec-rice.pdf  -d --param additionalXMLs=iec-rice.fr.xml
```

For 3- and more languages document just add comma separated values - paths to another xml files:
```
--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml
```
