### ISSUE TITLE
IEC styling (bibliography)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#113]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf

<img width="532" alt="Screen Shot 2020-04-11 at 2 43 23 AM" src="https://user-images.githubusercontent.com/11865/79017685-8554c680-7ba4-11ea-8952-30fe7736b8be.png">

French:
<img width="534" alt="Screen Shot 2020-04-11 at 2 44 33 AM" src="https://user-images.githubusercontent.com/11865/79017690-8685f380-7ba4-11ea-98ef-999c16be4e48.png">

**Comment by Intelligent2013** [comment]
Done. Except content on French.

**Comment by Intelligent2013** [comment]
In mn2pdf v1.18 (https://github.com/metanorma/mn2pdf/releases/download/v1.18/mn2pdf-1.18.jar) I've added a parameter 'param' to pass an external artifacts/parameters into xslt. So for produce PDF IEC on two languages you need to add `--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml` into command line, like this:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.18.jar   -x iec-rice.xml  -s iec.international-standard.xsl  -o  iec-rice.pdf  -d --param additionalXMLs=iec-rice.fr.xml
```

For 3- and more languages document just add comma separated values - paths to another xml files:
```
--param additionalXMLs=iec-rice.fr.xml,iec-rice.de.xml
```
