### ISSUE TITLE
IEC styling (abbreviations, definition lists)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#114]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf

<img width="432" alt="Screen Shot 2020-04-11 at 2 40 58 AM" src="https://user-images.githubusercontent.com/11865/79017717-9ac9f080-7ba4-11ea-8a96-59cea849214c.png">

<img width="441" alt="Screen Shot 2020-04-11 at 2 41 16 AM" src="https://user-images.githubusercontent.com/11865/79017732-a5848580-7ba4-11ea-9873-012eef59ae21.png">

**Comment by Intelligent2013** [comment]
Done.
