### ISSUE TITLE
IEC styling (tables, figures, formulas, notes, examples)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#115]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf
<img width="448" alt="Screen Shot 2020-04-11 at 2 41 37 AM" src="https://user-images.githubusercontent.com/11865/79017799-c8af3500-7ba4-11ea-9313-191999521bd4.png">
<img width="394" alt="Screen Shot 2020-04-11 at 2 41 46 AM" src="https://user-images.githubusercontent.com/11865/79017802-c8af3500-7ba4-11ea-9e0b-32f9f472bc7d.png">
<img width="435" alt="Screen Shot 2020-04-11 at 2 41 28 AM" src="https://user-images.githubusercontent.com/11865/79017797-c8169e80-7ba4-11ea-90e3-ef123dfbd5fe.png">

<img width="462" alt="Screen Shot 2020-04-11 at 2 41 13 AM" src="https://user-images.githubusercontent.com/11865/79017793-c77e0800-7ba4-11ea-8758-4ad705949bbe.png">
<img width="449" alt="Screen Shot 2020-04-11 at 2 41 25 AM" src="https://user-images.githubusercontent.com/11865/79017795-c8169e80-7ba4-11ea-808e-581c99caf80a.png">

<img width="460" alt="Screen Shot 2020-04-11 at 2 41 06 AM" src="https://user-images.githubusercontent.com/11865/79017786-c5b44480-7ba4-11ea-8880-5436e6caa59b.png">

**Comment by Intelligent2013** [comment]
Done.
