### ISSUE TITLE
IEC styling (Annex numbering)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#116]
Sample document: https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-5_2014.pdf

<img width="442" alt="Screen Shot 2020-04-11 at 2 42 03 AM" src="https://user-images.githubusercontent.com/11865/79017843-e5e40380-7ba4-11ea-81c8-27889ccfbad5.png">
<img width="429" alt="Screen Shot 2020-04-11 at 2 42 11 AM" src="https://user-images.githubusercontent.com/11865/79017847-e7adc700-7ba4-11ea-9df8-8ab40fe7e1f1.png">
<img width="437" alt="Screen Shot 2020-04-11 at 2 42 22 AM" src="https://user-images.githubusercontent.com/11865/79017850-e8465d80-7ba4-11ea-8257-7f2a8ca6b747.png">
<img width="433" alt="Screen Shot 2020-04-11 at 2 42 25 AM" src="https://user-images.githubusercontent.com/11865/79017851-e8465d80-7ba4-11ea-9754-1b511d0e24af.png">
<img width="438" alt="Screen Shot 2020-04-11 at 2 42 37 AM" src="https://user-images.githubusercontent.com/11865/79017853-e8def400-7ba4-11ea-8d95-f14bfedc4362.png">
<img width="443" alt="Screen Shot 2020-04-11 at 2 42 45 AM" src="https://user-images.githubusercontent.com/11865/79017854-e8def400-7ba4-11ea-9388-dff8e2fe1d4a.png">

**Comment by Intelligent2013** [comment]
Done.
