### ISSUE TITLE
IEC FDIS cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#120]
e.g.
* https://webstore.iec.ch/preview/info_iecfdis60721-3-0%7Bed2.0%7Den.pdf
* https://webstore.iec.ch/preview/info_iecfdis60598-2-1%7Bed2.0%7Db.pdf

<img width="532" alt="Screen Shot 2020-04-11 at 2 16 47 PM" src="https://user-images.githubusercontent.com/11865/79036889-38eaa480-7bff-11ea-83e0-673fb30bc032.png">

<img width="531" alt="Screen Shot 2020-04-11 at 2 16 53 PM" src="https://user-images.githubusercontent.com/11865/79036892-3be59500-7bff-11ea-8a4d-7f0137562590.png">
<img width="533" alt="Screen Shot 2020-04-11 at 2 16 59 PM" src="https://user-images.githubusercontent.com/11865/79036893-3d16c200-7bff-11ea-80e8-5846afcf845b.png">
<img width="532" alt="Screen Shot 2020-04-11 at 2 17 06 PM" src="https://user-images.githubusercontent.com/11865/79036894-3e47ef00-7bff-11ea-929b-a6e5229d5775.png">

**Comment by Intelligent2013** [comment]
Done. FYI: almost all data on 2nd page are hard-coded.

**Comment by ronaldtse** [comment]
@Intelligent2013 could you also help file the hard-coded information in metanorma-iec? They should be provided. Thanks!

**Comment by Intelligent2013** [comment]
Task on hold (there is a dependent task).

**Comment by Intelligent2013** [comment]
To do: update xslt (see https://github.com/metanorma/metanorma-iec/files/5750501/coverpage.zip).

**Comment by Intelligent2013** [comment]
Done.
