### ISSUE TITLE
IEC pre-publication cover pages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#121]
All IEC documents prior to publication have a circulation cover page.

Samples:
* (CDV) http://sactc265.iphy.ac.cn/document/iec/国际标准投票/2017年/90_387e_CDV--IEC%2061788-23%20Superconductivity%20-%20Part%2023%20Residual%20resistance%20ratio%20measurement%20-%20Residual%20resistance%20ratio%20of%20Nb/90_387e_CDV.pdf
* (FDIS) https://ulstandards.ul.com/wp-content/uploads/2020/02/21A_725e_FDIS.pdf

They are:
<img width="527" alt="Screen Shot 2020-04-11 at 2 29 33 PM" src="https://user-images.githubusercontent.com/11865/79037128-0772d880-7c01-11ea-9f01-4bf2a52f50a0.png">
<img width="532" alt="Screen Shot 2020-04-11 at 2 29 11 PM" src="https://user-images.githubusercontent.com/11865/79037127-02158e00-7c01-11ea-8d0c-d86ec8fefd35.png">
<img width="535" alt="Screen Shot 2020-04-11 at 2 29 18 PM" src="https://user-images.githubusercontent.com/11865/79037131-08a40580-7c01-11ea-8427-e5c3cb8e0193.png">

**Comment by ronaldtse** [comment]
Notice that there are a couple options for a document:
* CEN processing (true/false)
* category of standard (EMC, Environment, Quality assurance, Safety) This is displayed on the front page during publication
* horizontal standard (true/false) This is also displayed on the cover page at publication.

EMC
Outer cover
<img width="532" alt="Screen Shot 2020-04-11 at 2 33 02 PM" src="https://user-images.githubusercontent.com/11865/79037172-5de01700-7c01-11ea-8de9-2a02fc9306c1.png">

Inner cover
<img width="532" alt="Screen Shot 2020-04-11 at 2 33 17 PM" src="https://user-images.githubusercontent.com/11865/79037179-633d6180-7c01-11ea-8481-15cb1c8e95e5.png">

Horizontal standard:
https://webstore.iec.ch/preview/info_iec62648%7Bed1.1%7Db.pdf

Outer cover
<img width="534" alt="Screen Shot 2020-04-11 at 2 35 44 PM" src="https://user-images.githubusercontent.com/11865/79037246-bb746380-7c01-11ea-8d71-241dca05f513.png">

Inner cover
<img width="534" alt="Screen Shot 2020-04-11 at 2 35 14 PM" src="https://user-images.githubusercontent.com/11865/79037233-aa2b5700-7c01-11ea-8971-014cfa2a96ba.png">

**Comment by Intelligent2013** [comment]
Done. But almost all data hard-coded into xslt, because I don't have an XML example with these data:
- for circulation cover page
- CEN processing
- category of standard 
- horizontal standard
- etc.

**Comment by ronaldtse** [comment]
> Done. But almost all data hard-coded into xslt, because I don't have an XML example with these data:

@Intelligent2013 could you help create the issues for metanorma-iec to support those attributes? Their values should be in XML and the XSLT should just read them.

**Comment by Intelligent2013** [comment]
Task on hold (there are a dependent tasks).

**Comment by Intelligent2013** [comment]
To do: update xslt (see https://github.com/metanorma/metanorma-iec/files/5750501/coverpage.zip).

**Comment by Intelligent2013** [comment]
Done.
