### ISSUE TITLE
Horizontal spacing between terms and descriptions differs (DOC vs PDF)

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#138]
From https://github.com/metanorma/mn-native-pdf/issues/58
Horizontal spacing is bigger in PDF.

For example:

````
stem:[w]:: is the mass fraction of grains with a particular defect in the test sample;
stem:[m_D]:: is the mass, in grams, of grains with that defect;
stem:[m_S]:: is the mass, in grams, of the test sample.
````

*DOC output:*
![cap-doc](https://user-images.githubusercontent.com/33627611/79909613-4700a800-83eb-11ea-840b-8f7480f85e57.PNG)

*PDF output:*

![cap-pdf](https://user-images.githubusercontent.com/33627611/79909623-49fb9880-83eb-11ea-9c88-4627c87dc76b.PNG)

Thanks!

**Comment by Intelligent2013** [comment]
@manuel489 Apache FOP doesn't support 'auto' width for table's columns. Therefore, I calculate column's width depends on text content length (longest word length) and set it as 'proportional'.
To set width 'as in DOC' we need to have some attribute in XML, for example 'firstcol-width':
```
<dl id="_5f6960f8-5d63-4671-a730-8c6ff5137870" firstcol-width="20mm">
        <dt>
          <stem type="MathML">
            <math xmlns="http://www.w3.org/1998/Math/MathML">
              <mi>w</mi>
            </math>
          </stem>
        </dt>
        <dd>
          <p id="_aff50c2b-cc52-4e2e-86b9-a24a50b148a1">mass fraction of gelatinized kernels, expressed in per cent</p>
        </dd>
        <dt>
          <stem type="MathML">
            <math xmlns="http://www.w3.org/1998/Math/MathML">
              <mi>t</mi>
            </math>
          </stem>
        </dt>
        <dd>
          <p id="_c0125ccb-aae8-4ad1-959e-22a5f7759ff9">cooking time, expressed in minutes</p>
        </dd>
```

@ronaldtse is it possible?

Without it, is not possible to solve this issue.

**Comment by ronaldtse** [comment]
This is acceptable, let's close this for now. Thanks!
