### ISSUE TITLE
Remaining issues on UN Recommendation template

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#151]
Hi @Intelligent2013,

As it is requested in https://github.com/metanorma/mn-native-pdf/issues/61, these are the remaining visual diffs regarding Recommendation template.

Remaining diffs between *Resulted PDF* (https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_437E_Rec42.pdf) and *Original PDF* (https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_437E_Rec42.pdf)

- In resulted PDF, first page, the main title is missing and the organization's name is different.

*Resulted PDF:*
![cap1-resulted](https://user-images.githubusercontent.com/33627611/80598448-5f7a4f00-89f7-11ea-9cc8-f96d775061e9.PNG)

*Original PDF:*
![cap1-original](https://user-images.githubusercontent.com/33627611/80598134-debb5300-89f6-11ea-9264-0ca3baadd1dc.PNG)

- In resulted PDF, third page, the main title is missing.

*Resulted PDF:*
![cap2-resulted](https://user-images.githubusercontent.com/33627611/80598148-e549ca80-89f6-11ea-81ef-4184d6d72c7b.PNG)

*Original PDF:*
![cap2-original](https://user-images.githubusercontent.com/33627611/80598159-ea0e7e80-89f6-11ea-8c04-dc185138d72b.PNG)

- In resulted PDF, fourth page, the main title is missing and `#{tc}` is shown instead.

*Resulted PDF:*
![cap3-resulted](https://user-images.githubusercontent.com/33627611/80598171-f09cf600-89f6-11ea-8018-f03ccd7e7bce.PNG)

*Original PDF:*
![cap3-original](https://user-images.githubusercontent.com/33627611/80598181-f692d700-89f6-11ea-88f1-5c02ba5c10a6.PNG)

- In resulted PDF final page (26), the information contact differs, e.g., the fax number is missing, the email is different, the "http:\\" of  the website link is missing, etc. See images below.

*Resulted PDF:*
![cap4-resulted](https://user-images.githubusercontent.com/33627611/80598194-fdb9e500-89f6-11ea-91ce-470853b2562a.PNG)

*Original PDF:*
![cap4-original](https://user-images.githubusercontent.com/33627611/80598221-05798980-89f7-11ea-93a5-f70df5561837.PNG)

Thanks!

**Comment by Intelligent2013** [comment]
> In resulted PDF, first page, the main title is missing and the organization's name is different.

**Comment by Intelligent2013** [comment]
> In resulted PDF, first page, the main title is missing and the organization's name is different.

In source XML there isn't title and 'UNECE' name:
```
<?xml version="1.0" encoding="UTF-8"?>
<un-standard xmlns="https://www.metanorma.org/ns/un">
<bibdata type="standard">

<docidentifier>42</docidentifier>
<docnumber>42</docnumber>
<contributor>
<role type="author"/>
<organization>
<name>United Nations</name>
<abbreviation>UN</abbreviation>
</organization>
</contributor>
<contributor>
<role type="publisher"/>
<organization>
<name>United Nations</name>
<abbreviation>UN</abbreviation>
</organization>
</contributor>
```

> In resulted PDF, third page, the main title is missing.

No title in XML.

> In resulted PDF, fourth page, the main title is missing and #{tc} is shown instead.

In Source XML:
```
<clause>
        <title>#{tc}<br/>Simple, Transparent and Effective Processes for Global Commerce</title>
```

> In resulted PDF final page (26), the information contact differs, e.g., the fax number is missing, the email is different, the "http:\" of the website link is missing, etc. See images below.

Source xml:
```
<feedback-statement>
    <clause>
      <p id="boilerplate-feedback-name">UN Economic Commission for Europe: Information Service</p>
      <p id="boilerplate-feedback-address">
        Palais des Nations<br/>
        CH-1211 Geneva 10<br/>
        Switzerland<br/>
        <br/>
        <link target="tel:+41(0)229171234">+41 (0) 22 917 12 34 (switchboard)</link><br/>
        <link target="mailto:unece_info@un.org">unece_info@un.org</link><br/>
        <link target="https://www.unece.org/">www.unece.org/</link>
      </p>
    </clause>
  </feedback-statement>
```

So, there aren't issues in PDF.

**Comment by manuel489** [comment]
Ok, thanks @Intelligent2013 for your clarification.
