### ISSUE TITLE
Vista fonts installer download failed often

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#155]
Vista fonts installer download failed often:

![image](https://user-images.githubusercontent.com/5559926/80641795-11546280-8a6e-11ea-820c-06629604bc2a.png)

Today I've tried a lot of attempts to re-run jobs to make a release of mn2pdf, and now the problem for mn-native-pdf, I can't merge PR and spent a time to non-productive actions. Could we move PowerPointViewer.exe installer inside our repository to work more robust?

**Comment by ronaldtse** [comment]
We wish to keep the fonts on archive.org since we are not allowed to distribute them. 

I found an alternative site that might work:
* https://files.giga-downloads.de/office/PowerPointViewer.exe

**Comment by ronaldtse** [comment]
I think this is now solved with Fontist. Closing.
