### ISSUE TITLE
Add MPFA samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#162]
For MPFD the samples are here: https://github.com/metanorma/mn-samples-mpfa/

**Comment by Intelligent2013** [comment]
@ronaldtse Where can I get original DOC/PDF for xslt development?

**Comment by Intelligent2013** [comment]
XSLT for MPFD added. But workflows didn't change to support it yet. Some source XMLs has `doctype` values:
```xml
<doctype>Supervision of MPF Intermediaries</doctype>
<doctype>Compliance Standards for MPF Trustees</doctype>
<doctype>Guidelines</doctype>
```
And therefore we need to create the xslt files with names:
- 'mpfd.Supervision of MPF Intermediaries.presentation.core.xsl'
- 'mpfd.Compliance Standards for MPF Trustees.presentation.core.xsl'
- mpfd.Guidelines.presentation.core.xsl

but I don't sure that it'a right solution.

**Comment by Intelligent2013** [comment]
XSLTs for MPFD added.
