### ISSUE TITLE
Add GB layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#163]
For GB, there are a number of layouts:
https://github.com/metanorma/mn-samples-gb

* Enterprise standard
* Local standard
* Sector standard
* Social standard
* GB standard

**Comment by Intelligent2013** [comment]
@ronaldtse Where can I get original DOC/PDF for xslt development?

**Comment by ronaldtse** [comment]
@Intelligent2013 here are the Word files: https://metanorma.github.io/mn-samples-gb/

**Comment by Intelligent2013** [comment]
@ronaldtse 
In docx on cover pages there are such titles and logo:

File: rice.gb.en
Title: National standard (Recommended)
Logo: GB 

File: rice.gb.enterprise.en
Title: Acme Inc. Enterprise Standard
Logo: -

File: rice.gb.local.en
Title: Hong Kong Special Administrative Region Local Standard
Logo:  DB81

File: rice.gb.sector.en
Title: People's Republic of China Food Industry Standard
Logo: LS

File: rice.gb.social.en
Title: - 
Logo: ABC

Question: how to construct title from xml fields (for each document these rules are different) and when we should show logo?

**Comment by ronaldtse** [comment]
Ping @opoudjis for answers. The logos are different per type of standard, as shown in the Word files.

**Comment by Intelligent2013** [comment]
@ronaldtse XSLT is ready, except titles and logos. https://github.com/metanorma/mn-native-pdf/pull/190 can be merged.

**Comment by opoudjis** [comment]
The logic of deriving titles from subfields of identifiers involves big lookup tables that have a dedicated gem (gb-agencies). Once again, they are not in the XML, and if you insist that they be represented in the XML, you're going to have to wait. 

The logo choice depends on gbprefix:

prefix = xml.at(ns("//bibdata/ext/gbtype/gbprefix"))&.text

case gbprefix.downcase
        when "db" then "gb-standard-db"
        when "gb" then "gb-standard-gb"
        when "gjb" then "gb-standard-gjb"
        when "gm" then "gb-standard-gm"
        when "jjf" then "gb-standard-jjf"
        when "zb" then "gb-standard-zb"
else
nil
        end

**Comment by Intelligent2013** [comment]
@opoudjis thank you for the clarification. Yes, I need to have title directly in then XML. I'll create a ticket on metanorma-gb.

**Comment by Intelligent2013** [comment]
Logo added.
