### ISSUE TITLE
DIS `<stagename>` was changed to "Draft international standard", need to change XSLT

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#168]
From https://github.com/metanorma/metanorma-iso/issues/364

> @opoudjis should have mentioned this for the new version -- the `<stagename>` element has been changed to show DIS as "Draft international standard", which broke our PDF templates.

> This task is for @Intelligent2013 to update the PDF templates for this change. The generated XMLs for all stages can be seen in mn-samples-iso.

Thanks!

**Comment by Intelligent2013** [comment]
Fixed.

**Comment by Intelligent2013** [comment]
TItle shows ok now:
![image](https://user-images.githubusercontent.com/5559926/80954315-d489c200-8e05-11ea-90c2-bc78b7f8d3fc.png)

Pages for other stages see in https://github.com/metanorma/mn-native-pdf/issues/169#issuecomment-623321043
