### ISSUE TITLE
ISO cover: fix PRF vs FINAL stages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#169]
docstage (60) docsubstage (60) = published
docstage (60) docsubstage (00) = PRF

Right now the styles are switched:

https://github.com/metanorma/mn-samples-iso/blob/master/sources/international-standard/iso-rice-en.covers.final.adoc
<img width="548" alt="Screen Shot 2020-05-03 at 11 46 29 AM" src="https://user-images.githubusercontent.com/11865/80898236-bc497280-8d33-11ea-8a64-5a55a939a28b.png">

https://github.com/metanorma/mn-samples-iso/blob/master/sources/international-standard/iso-rice-en.covers.prf.adoc
<img width="544" alt="Screen Shot 2020-05-03 at 11 47 21 AM" src="https://user-images.githubusercontent.com/11865/80898248-da16d780-8d33-11ea-8807-fa43d1905b68.png">

**Comment by Intelligent2013** [comment]
Hmm. Really the logic to determine showed text is compicated. I'll try to simplify code.

**Comment by Intelligent2013** [comment]
iso-rice-en.covers.final.xml:
![image](https://user-images.githubusercontent.com/5559926/80946019-cdf34e80-8df5-11ea-8af7-2ffe2b4c7fcf.png)

iso-rice-en.covers.prf.xml:
![image](https://user-images.githubusercontent.com/5559926/80946120-0135dd80-8df6-11ea-9811-b435a48dee39.png)

![image](https://user-images.githubusercontent.com/5559926/80946177-20cd0600-8df6-11ea-9e41-19410af2eb44.png)

Other stages:
iso-rice-en.covers.awi.xml (really `<stage abbreviation="NWIP">10</stage>`):
![image](https://user-images.githubusercontent.com/5559926/80946289-5c67d000-8df6-11ea-893e-166dda986476.png)

![image](https://user-images.githubusercontent.com/5559926/80946317-70133680-8df6-11ea-99e3-764cb5ba4382.png)

iso-rice-en.covers.cd.xml :
![image](https://user-images.githubusercontent.com/5559926/80946357-87eaba80-8df6-11ea-8a13-7e8d77a10efa.png)

![image](https://user-images.githubusercontent.com/5559926/80946393-9b962100-8df6-11ea-9f15-7448863dab52.png)

iso-rice-en.covers.dis.xml :
![image](https://user-images.githubusercontent.com/5559926/80946425-b4063b80-8df6-11ea-9424-d79f3e7ef8b2.png)

![image](https://user-images.githubusercontent.com/5559926/80946498-d730eb00-8df6-11ea-8de9-59408cfebb0c.png)

iso-rice-en.covers.fdis.xml :
![image](https://user-images.githubusercontent.com/5559926/80946558-f760aa00-8df6-11ea-93a5-2a02d90a32d6.png)

![image](https://user-images.githubusercontent.com/5559926/80946603-13644b80-8df7-11ea-9d96-604b4274a33b.png)

iso-rice-en.covers.np.xml 
![image](https://user-images.githubusercontent.com/5559926/80946651-32fb7400-8df7-11ea-9a16-0da676ce3c85.png)

![image](https://user-images.githubusercontent.com/5559926/80946679-3e4e9f80-8df7-11ea-828f-0ce4a07cdb87.png)



iso-rice-en.covers.wd.xml 
![image](https://user-images.githubusercontent.com/5559926/80946711-4e667f00-8df7-11ea-906a-c89ab90ccd06.png)

![image](https://user-images.githubusercontent.com/5559926/80946734-5c1c0480-8df7-11ea-9922-e4a4135f3e30.png)

**Comment by ronaldtse** [comment]
LGTM, thanks @Intelligent2013 !
