### ISSUE TITLE
ISO: ISO-690 issues

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#172]
> The ISO PDF layout has some spacing issues with NOTEs/EXAMPLEs, it shoudl have some gap on top and bottom.

![image](https://user-images.githubusercontent.com/5559926/80945124-c337ba00-8df3-11ea-888d-6c7ce3ff4b77.png)

![image](https://user-images.githubusercontent.com/5559926/80945220-02660b00-8df4-11ea-93c3-d94068bceeb1.png)

> the EXAMPLEs are not numbered

![image](https://user-images.githubusercontent.com/5559926/80945159-dd719800-8df3-11ea-8cfe-f5dc64e109ca.png)

**Comment by ronaldtse** [comment]
Please use ISO 8601-1 which we have samples for ISO XML, MN XML and actual published document for proofing of style. Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse  Between original ISO 8601-1 PDF and produced PDF there are a few differences in styles:
- blue hyperlinks;
- links like (3.1.1.3)
instead of (Clause 3.1.1.3)
- a bit difference in vertical space between paragraphs

In a few month ago there were a few issues to align ISO xslt to original ISO Rice documents:
- https://github.com/metanorma/mn-native-pdf/issues/35
- https://github.com/metanorma/mn-native-pdf/issues/34

It seems this ISO 8601-1 looks differently. Do I need to remade all ISO xslt styles again to align ISO 8601-1?

And I found that in iso-tc154-8601-1-en.xml there a few questions for me in markup:
1. Source PDF shows as:
![изображение](https://user-images.githubusercontent.com/5559926/80995400-e17ad580-8e46-11ea-8b6b-d7d1bbbcc2d7.png)
but source XML contains two claims
```
<clause id="terms-concepts" inline-header="false" obligation="normative">
	<title>Basic concepts</title>
	<clause id="term-date" inline-header="false" obligation="normative">
		<title>date</title><p id="_f8ed4107-fcf1-433d-b8bf-3f1bf1ad37f2">
				<em>time</em> (<xref target="term-time"/>) on the <em>calendar</em> (<xref target="term-calendar"/>) <em>time scale</em> (<xref target="term-time-scale"/>)</p>
```

instead of claims/term

In produced PDF it shows as ('date' on the same line with '3.1.1.1'):
![изображение](https://user-images.githubusercontent.com/5559926/80995701-5cdc8700-8e47-11ea-8727-b052a0b712f3.png)

2. Original source PDF have 'Note x to entry':
![изображение](https://user-images.githubusercontent.com/5559926/80995863-9b724180-8e47-11ea-88a9-538454f49c8b.png)

but in source XML it marks as 'note':
```
<note id="_0a4f93d5-ea21-45f4-8b9e-cf27e4356428">
	<p id="_6189b5c6-1bb0-418d-a07c-5095d258312e">The term “time” is often used in common language. However, it should only be used if the meaning is clearly visible from the context.</p>
</note>
<note id="_5d1be11d-0921-401c-973a-a5e32ce42f70">
	<p id="_3959ecbb-f8cb-43c5-9664-57ad809fb29c">On a time scale consisting of successive time intervals, such as a <em>clock</em> (<xref target="term-clock"/>) or <em>calendar</em> (<xref target="term-calendar"/>), distinct instants may be expressed by the same time.</p>
</note>
```
which we display as 'NOTE'. In xslt we have processing for 'termnote' and it shows as 'Note x to entry' properly.

Should I remade xslt to show 'Note x to entry' (instead of 'NOTE') for 'note' tag also? Or source xml contain mistakes?

**Comment by ronaldtse** [comment]
> blue hyperlinks;

Is correct.

Tables, Figures should also be hyperlinks.

> It seems this ISO 8601-1 looks differently. Do I need to remade all ISO xslt styles again to align ISO 8601-1?

What are the style differences between ISO Rice and ISO 8601-1?

> (3.1.1.3) vs (Clause 3)

"Clause X" is used for depth level 1, if it is a subclause with depth > 1 level, it is referred as "X.Y.Z".

> but source XML contains two clauses instead of clause/term

This is an error in the source XML (https://github.com/metanorma/iso-8601-1)

However, I don't see this problem in the source XML?

> <note> vs <termnote>

This is strange -- I don't see this problem in the source XML? Let me send you the source XML again.

**Comment by Intelligent2013** [comment]
@ronaldtse 

In source xml - `<note>`.
In source PDF show: `Note 1 to entry`.
In produced PDF (by XSLT) show: `NOTE`
Reason: In ISO xslt, for `<note>` we put `NOTE` in PDF, but for `<termnote>` we put `Note 1 to entry`.

In source PDF there a few notes which show as 'NOTE' (not 'Note 1 to entry') and it markup in XML as `<note>` also.

**Comment by ronaldtse** [comment]
@Intelligent2013 you're right -- this is a regression!

https://github.com/metanorma/metanorma-standoc/issues/270

**Comment by Intelligent2013** [comment]
@ronaldtse ok, let's wait...

**Comment by Intelligent2013** [comment]
@ronaldtse looks like there is an issue in `<example>` vs `<termexample>` also.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013

**Comment by Intelligent2013** [comment]
@ronaldtse  Issue fixed:

![изображение](https://user-images.githubusercontent.com/5559926/81105510-b8c50f80-8f1c-11ea-93a3-2565262f1402.png)
...

![изображение](https://user-images.githubusercontent.com/5559926/81105632-e27e3680-8f1c-11ea-8694-ee7bbbcfa201.png)

...

![изображение](https://user-images.githubusercontent.com/5559926/81105705-ffb30500-8f1c-11ea-9e53-d4aa0c7cef0a.png)

In XML there are a few issues:
- internet hyperlinks are just a text
- no revision-date (date below 'First edition' on cover page)
- FYI in source XML there is a text which contains 'tab' characters, like this:
`<p id="_c246e499-1234-4db5-bd19-3783de1b1aa1">Implied:		[YYYY]</p>`
(before [YYYY] there are two tabs). In original PDF it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/81106136-b911da80-8f1d-11ea-903b-90ac2b606927.png)

XSL-FO 'don't know' how to display tabs, because there isn't such thing as 'tab stop' feature, therefore it display as:
![изображение](https://user-images.githubusercontent.com/5559926/81106289-02622a00-8f1e-11ea-8b5c-51012adf6732.png)

**Comment by ronaldtse** [comment]
Questions:

> internet hyperlinks are just a text

Pinging @opoudjis for answer

> no revision-date (date below 'First edition' on cover page)

In the DIS stage cover there is no place for the revision-date. Do we need it?

> FYI in source XML there is a text which contains 'tab' characters, like this:

I wonder if we can handle tab characters using a table...

**Comment by opoudjis** [comment]
>> internet hyperlinks are just a text
> Pinging @opoudjis for answer

I've recompiled, and am not finding "internet hyperlinks are just a text": cases like `<link target="http://www.iso.org/directives">www.iso.org/directives</link>` are marked up as intended. Specifics please.

>> FYI in source XML there is a text which contains 'tab' characters, like this:
>I wonder if we can handle tab characters using a table...

Do not. There is no expectation that you render XML tab as anything but space. The tabs were in the asciidoctor source, because of the original Word source use of them; but Metanorma does not give tabs a special value.

**Comment by Intelligent2013** [comment]
> > no revision-date (date below 'First edition' on cover page)
> 
> In the DIS stage cover there is no place for the revision-date. Do we need it?

In my version iso-tc154-8601-1-en.xml  I see IS stage, not DIS:
```
<status>
<stage abbreviation="IS">60</stage>
<substage>60</substage>
</status>
```
On cover page original PDF there is revision date:
![изображение](https://user-images.githubusercontent.com/5559926/81158074-49890300-8f90-11ea-835a-ed3433e9b8c2.png)


> > FYI in source XML there is a text which contains 'tab' characters, like this:
> 
> I wonder if we can handle tab characters using a table...

It's very huge and complex task to handle tabs via xslt. To create a table we should analyze multiparagraph text with markup via xslt and convert it into table structure - it's almost non-real task with further issues and bugs.

**Comment by Intelligent2013** [comment]
> I've recompiled, and am not finding "internet hyperlinks are just a text": cases like `<link target="http://www.iso.org/directives">www.iso.org/directives</link>` are marked up as intended. Specifics please.
> 

@ronaldtse In my two-days ago version I have text only (see www.iso.org/directives):
```
<p id="_c3006bb9-c77d-4d8d-9b17-56c8c1a7fc9e">The procedures used to develop this document and those intended for its
further maintenance are described in the ISO/IEC Directives, Part 1. In
particular, the different approval criteria needed for the different
types of ISO documents should be noted. This document was drafted in
accordance with the editorial rules of the ISO/IEC Directives, Part 2
(see www.iso.org/directives).</p>
```

But in any case, xslt should process links as need.

**Comment by opoudjis** [comment]
ISO-690, right?

````
<p id="_72159a3e-c54c-43c4-a1ef-53e341f5ce85">The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular, the different approval criteria needed for the different types of ISO documents should be noted, This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see <link target="http://www.iso.org/directives">www.iso.org/directives</link>).</p>
````

*shrug*

**Comment by Intelligent2013** [comment]
> ISO-690, right?

Hmmm.... In ISO-690 looks ok, but I talked about ISO 8601-1. Sorry for any inconveniences.
From @ronaldtse two days ago (see above):
> Please use ISO 8601-1 which we have samples for ISO XML, MN XML and actual published document for proofing of style. Thanks!

**Comment by opoudjis** [comment]
Right. They are text, because they have not been marked up in the source as links (unlike in ISO-690). Updated source in that instance.

**Comment by ronaldtse** [comment]
Seems that everything is addressed here. Thanks @Intelligent2013 @opoudjis !
