### ISSUE TITLE
ISO document identifier duplicates year in header/reference number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#173]
![image](https://user-images.githubusercontent.com/11865/80965624-741a7500-8e45-11ea-8bbf-75cca6b194ce.png)

**Comment by Intelligent2013** [comment]
@ronaldtse the structure of ISO doc identifier is:
`<doc number>:<year>(<lang>)`

From ISO XML (for ISO 690 example) I concatenate from 3 fields: 
`doc number -> <docidentifier type="iso">ISO/DIS 690</docidentifier>`
:
`year -> <copyright><from>2020</from>`
`lang -> (value in braces from /iso:iso-standard/iso:bibdata/iso:docidentifier[@type = 'iso-with-lang'])`

In all ISO XML that I saw before, in docidentifier there isn't year, and I need to concatenate from a few fields.
It would be better to add into XML one more docidentifier with all components together.

**Comment by ronaldtse** [comment]
>  It would be better to add into XML one more docidentifier with all components together.

I agree. The docidentifier generation is more complex in the case of Amendments and Technical Corrigendum. Can you make a task for metanorma-iso? Thanks.

**Comment by Intelligent2013** [comment]
> > It would be better to add into XML one more docidentifier with all components together.
> 
> I agree. The docidentifier generation is more complex in the case of Amendments and Technical Corrigendum. Can you make a task for metanorma-iso? Thanks.

Added.

**Comment by ronaldtse** [comment]
@Intelligent2013 this is active again as @opoudjis fixed metanorma/metanorma-iso#365 . Can  you help follow up?

**Comment by Intelligent2013** [comment]
@ronaldtse Fixed.

Now, 
- the identifier for  cover page in upper right corner - docidentifier[@type = 'iso'], 
- 'Reference number' and page headers - docidentifier[@type = 'iso-reference']
