### ISSUE TITLE
ISO: tables sometimes exceed page width when Word doesn't

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#174]
Word:
<img width="497" alt="Screen Shot 2020-05-04 at 8 27 49 PM" src="https://user-images.githubusercontent.com/11865/80965793-c3f93c00-8e45-11ea-843d-b07224b3a819.png">

PDF:
<img width="579" alt="Screen Shot 2020-05-04 at 8 28 49 PM" src="https://user-images.githubusercontent.com/11865/80965850-decbb080-8e45-11ea-8b66-d4467f8e9c38.png">

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/81004191-b4352400-8e54-11ea-849a-86bb51eafbb3.png)

**Comment by ronaldtse** [comment]
Thanks!
