### ISSUE TITLE
ISO: layout issues with definition lists

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#175]
In ISO 10303-104, page 51 is rendered as:
<img width="611" alt="Screen Shot 2020-05-04 at 11 47 19 PM" src="https://user-images.githubusercontent.com/11865/80985286-98844a80-8e61-11ea-9bd8-b95cbfdf6f46.png">

The source document is available in https://github.com/metanorma/iso-10303

**Comment by Intelligent2013** [comment]
@ronaldtse Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/81106717-bf548680-8f1e-11ea-87af-51b85837d0a2.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
