### ISSUE TITLE
ISO: Cover publication date should be taken from `publish-date`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#179]
This document has set `publish-date` but is not showing.

I think the cover page shows `revdate`? For ISO "published" document (stage 60, substage 60), it should be using the `publish-date`.

```
= Integrated application resource: Modelling commands for the exchange of procedurally represented 2D CAD models
:docnumber: 10303
:partnumber: 112
:edition: 1
:copyright-year: 2006
:publish-date: 2006-12-15
```

<img width="620" alt="Screen Shot 2020-05-08 at 9 53 30 AM" src="https://user-images.githubusercontent.com/11865/81361747-c7284c80-9111-11ea-87c6-b6abeaf77cb6.png">

**Comment by Intelligent2013** [comment]
Fixed.
