### ISSUE TITLE
No warnings shown if required font is not installed in system

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/mn-native-pdf#185]
## Problem description

Currently, if the system does not have a certain font installed (e.g. Calibri) and that font is required in the document, no warnings / errors would show during the build process.

## Expected result

Either emit warnings or abort the build process.

**Comment by Intelligent2013** [comment]
Warnings added at starting and ending of process.
Version https://github.com/metanorma/mn2pdf/releases/download/v1.16/mn2pdf-1.16.jar
