### ISSUE TITLE
Source code line too long goes off page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#200]
From iso-13584-42 https://github.com/metanorma/iso-10303/blob/master/sources/iso-13584-42/document.adoc

<img width="871" alt="Screen Shot 2020-05-25 at 3 02 25 AM" src="https://user-images.githubusercontent.com/11865/82762865-022abf80-9e36-11ea-84d2-9a46b1688cb1.png">

**Comment by Intelligent2013** [comment]
Issue fixed:
![изображение](https://user-images.githubusercontent.com/5559926/83071014-0f81bd00-a075-11ea-9fe0-24fe4d3a8df5.png)
