### ISSUE TITLE
Table cells with content too long causes broken wrap

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#201]
From iso-13584-42: https://github.com/metanorma/iso-10303/blob/master/sources/iso-13584-42/document.adoc

<img width="758" alt="Screen Shot 2020-05-25 at 3 01 59 AM" src="https://user-images.githubusercontent.com/11865/82762907-4ae27880-9e36-11ea-9e61-572d8623f7b7.png">

**Comment by Intelligent2013** [comment]
Issue fixed:

![изображение](https://user-images.githubusercontent.com/5559926/83070284-edd40600-a073-11ea-8088-278e31b5e458.png)
