### ISSUE TITLE
Windows build failing on master and PRs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#204]
e.g. https://github.com/metanorma/mn-native-pdf/pull/199/checks?check_run_id=704356999

```
cp mn-samples-ogc/documents/16-080.xml sources/ogc-16-080.xml
2756
xmllint --xpath "name(*)" sources/ogc-16-080.xml | cut -d "-" -f 1 > MN_FLAVOR.txt
2757
xmllint --xpath "//*[local-name()='doctype']/text()" sources/ogc-16-080.xml > DOCTYPE.txt
2758
make: *** [Makefile:132: documents/ogc-16-080.pdf] Error -1073741819
2759
```

The ogc-16-080.xml relevant output is this:
```sh
$ xmllint --xpath "name(*)" mn-samples-ogc/documents/16-080.xml | cut -d "-" -f 1
ogc

$ xmllint --xpath "//*[local-name()='doctype']/text()" mn-samples-ogc/documents/16-080.xml 
user-guide
```

Not sure what the problem is...

**Comment by Intelligent2013** [comment]
Issue fixed.
Reason was in big file size of ogc-16-080.xml - 18MB. `xmllint` in Windows environment can't process such big xml - just empty result, no errors/warnings.
But in my local Win10 environment xmllint works ok.
`xmllint` has a parameter `--huge`, that solving this issue. But for prevent of further issues with xmllint on Win platform, I've replaced xmllint commands:
```
xmllint --xpath "name(*)" $< | cut -d "-" -f 1 > MN_FLAVOR.txt
xmllint --xpath "//*[local-name()='doctype']/text()" $< > DOCTYPE.txt
```
to powershell scripts:

```
powershell -Command "$$doc = [xml](Get-Content $<); $$doc.SelectNodes(\"*\").get_name()" | cut -d "-" -f 1 > MN_FLAVOR.txt
powershell -Command "$$doc = [xml](Get-Content $<); $$doc.SelectNodes(\"//*[local-name()='doctype']\").'#text'" > DOCTYPE.txt
```

**Comment by ronaldtse** [comment]
Wow that's a tricky bug -- thank you for fixing it!!
