### ISSUE TITLE
IHO PDF: index element processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#214]
Source s102.xml contains 'index' elements  `<index primary="Depth) X (Tan Ø/2"/>`:
```
<clause id="_sonar_footprint" obligation="normative">
	<title>Sonar Footprint</title>
	<p id="_41b6616f-22f6-453b-a4ae-96954a696521">Sonar footprint is a function of water depth (20 metres) and beam angle (0.5° X 0.5°). Computed footprint at nadir:</p>
	<p id="_850aac5a-bf8f-4344-acec-3bcc4e3d7c8b">Footprint @ Nadir = 2 X Depth) X (Tan Ø/2<index primary="Depth) X (Tan Ø/2"/>, where Ø = Beam Width Footprint = 2 X 20 m) X (Tan .25<index primary="20 m) X (Tan .25"/> = 0.17 metres</p>
	<p id="_5fbb532c-fbbc-4000-8756-22eb5b068318">Since this is a 0.5° X 0.5° system, the total footprint at Nadir is: <strong>0.17m X 0.17m</strong></p>
...
```

In DOC it doesn't display:
![изображение](https://user-images.githubusercontent.com/5559926/83436422-7a9d0c00-a446-11ea-95cc-79f17bcf925c.png)

@ronaldtse  Should I ignore it?

**Comment by ronaldtse** [comment]
Ping @opoudjis , seems like an error in XML escaping?

**Comment by ronaldtse** [comment]
The source text was this:

```
==== Sonar Footprint
Sonar footprint is a function of water depth (20 metres) and beam angle (0.5° X 0.5°). Computed footprint at nadir:

Footprint @ Nadir = 2 X ((Depth) X (Tan Ø/2)), where Ø = Beam Width Footprint = 2 X ((20 m) X (Tan .25)) = 0.17 metres

Since this is a 0.5° X 0.5° system, the total footprint at Nadir is: *0.17m X 0.17m*
```

There's no "index" word in it.

**Comment by ronaldtse** [comment]
Ping @opoudjis

**Comment by opoudjis** [comment]
`((` is a reserved expression in asciidoctor to mark up index terms.

Index terms are not displayed in text: they are used to generate an index --- if that is supported in the output format. But in this instance, this is a markup error, `((` should be escaped (e.g. as `(\(` or `(&#200c;(` ).

**Comment by opoudjis** [comment]
And, to anticipate the next question: we support index because IETF uses it, but we do not generate indexes in Metanorma output.

Yet.

**Comment by ronaldtse** [comment]
I've since changed the source formatting to:

https://github.com/metanorma/mn-samples-iho/blob/7ef2cb676d9ae320267d9290391f066a2bbb2c45/sources/s102/sections/ai-gridding_full.adoc

```adoc
==== Sonar Footprint
Sonar footprint is a function of water depth (20 metres) and beam angle (0.5° X 0.5°). Computed footprint at nadir:

Footprint @ Nadir = stem:[2 x (("Depth") x (Tan Ø/2))], where Ø = Beam Width stem:["Footprint" = 2 x ((20 m) x (Tan .25)) = 0.17 "metres"]

Since this is a stem:[0.5° x 0.5°] system, the total footprint at Nadir is: stem:[0.17m x 0.17m]


[[fig-sonar-footprint-at-nadir]]
.Sonar Footprint at Nadir
image::figure-sonar-footprint-at-nadir.png[]

```

So this problem should be gone.
