### ISSUE TITLE
PDF: ISO amendment - document review (continued from #59)

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-native-pdf#216]
Note: DOC was generated using gems "metanorma-iso" and "isodoc", and was then compared to generated PDF.

Noticed differences are as follows:

- Order and position of the sections is different. DOC is correct in this case.

In the original amendment model, sections are ordered as follows:
1. Introduction
2. Normative references
3.-nth All other sections (changes)

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756105-d6e27480-a66e-11ea-8e3c-b98541b0a3cb.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756134-e2ce3680-a66e-11ea-8e80-95283fd7b082.png)

- Original document has italicized and unnumbered titles for sections, in regular font size as for the rest of the text. Generated DOC also applies this. PDF needs to be changed.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756193-fc6f7e00-a66e-11ea-9eb0-a7c1fd7b8952.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756245-10b37b00-a66f-11ea-897d-b53eb2d2cf2a.png)

- Header differs.

PDF (main page after the foreword):
![image](https://user-images.githubusercontent.com/55683568/83756284-232db480-a66f-11ea-893a-f7d69df031de.png)

PDF (other pages):
![image](https://user-images.githubusercontent.com/55683568/83756350-3e002900-a66f-11ea-9ee5-3f75d5f05152.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756301-2b85ef80-a66f-11ea-975b-22f7d20be8eb.png)

- Title on the first page after foreword differs. DOC has an additional "Amendment" subtitle, as the original amendment model.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756486-66882300-a66f-11ea-8c59-31e2ab8e042c.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756463-5ff9ab80-a66f-11ea-9ada-f7a50f7e9941.png)

- "Normative references" in DOC vs. "Normative References" in PDF - capital R in PDF should be replaced with small r.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756590-8cadc300-a66f-11ea-9ab5-79699db18583.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756601-946d6780-a66f-11ea-9220-226aaeb8a99e.png)

- PDF includes some right-aligned dashes after sections, which shouldn't be present.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756651-a6e7a100-a66f-11ea-8389-b6faf1e5ff11.png)

- "Key" for Figure 1 has unequal horizontal spacing for 1 and 2 in PDF. It seems this is caused by a difference in width of the left margin for odd and even pages in PDF. I think width of the margins should be the same, regardless of whether the page is odd or even.

Moreover, "Key" has a bigger spacing between the number and corresponding explanation, in comparison to generated DOC and original document.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83756723-c088e880-a66f-11ea-900f-259bbb4a38dc.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83756752-cbdc1400-a66f-11ea-9b3e-5d8f32512d68.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83756827-e2826b00-a66f-11ea-8db6-944802bb272f.png)

Following issues are addressed in metanorma-iso, and after they're solved, corresponding parts of generated PDF need to be re-checked:

- Figures are numbered differently in generated PDF and in the original. I opened a ticket https://github.com/metanorma/metanorma-iso/issues/388 in metanorma-iso to address this issue.

- Titles (from ISO document which amendment refers to) cannot be generated properly. I opened a ticket https://github.com/metanorma/metanorma-iso/issues/387 in metanorma-iso to address this issue.

- ToC shouldn't be included in generated DOC/PDF. I opened a ticket https://github.com/metanorma/metanorma-iso/issues/390 in metanorma-iso to address this issue.

- Front page and Copyright page differs for all `docstage`s. I opened a ticket https://github.com/metanorma/metanorma-iso/issues/391 in metanorma-iso to address this issue.

**Comment by Intelligent2013** [comment]
@anermina could you generate a source XML file and put it somewhere, please? I can't do it in my Windows and Ubuntu environment due make errors.

**Comment by Intelligent2013** [comment]
@anermina don't worry about source XML. Updated xml here already: https://github.com/metanorma/mn-samples-iso/tree/gh-pages

**Comment by Intelligent2013** [comment]
All issues fixed.

> Figures are numbered differently in generated PDF and in the original.

Temporarily I've removed numbering for figures in amendment PDF documents. 

> ToC shouldn't be included in generated DOC/PDF.

ToC removed for amendment PDF.

**Comment by anermina** [comment]
Following two issues are present now:

1.  Italicized title shouldn't apply to the Foreword section.

PDF:
![image](https://user-images.githubusercontent.com/55683568/89131769-9046b480-d50f-11ea-92d6-948560be075a.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/89131778-a18fc100-d50f-11ea-9bda-e52a43a7a339.png)

2. Are margins intentionally set differently for even and odd pages in PDF? 
Indented text looks non-indented when it gets to the even page in PDF, which was initially reported as an issue with "Key" elements after the figures, but is now present in the following part of the text:

PDF:
![image](https://user-images.githubusercontent.com/55683568/89131845-17942800-d510-11ea-8846-2691b614be80.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/89131860-2ed31580-d510-11ea-8e63-0da6ed9334fa.png)

**Comment by Intelligent2013** [comment]
> Italicized title shouldn't apply to the Foreword section.

Fixed. Updated PDF:  [rice-amd.final.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/5021822/rice-amd.final.presentation.pdf)

> Are margins intentionally set differently for even and odd pages in PDF?

Yes, the margins are different for even and odd pages in PDF. This was done a few months ago for fixing issue https://github.com/metanorma/mn-native-pdf/issues/97.

**Comment by anermina** [comment]
After this change, we got a bug in processing Annex title:
![image](https://user-images.githubusercontent.com/55683568/89338438-ded58980-d69c-11ea-85d6-b7728acb6fe7.png)

Before:
![image](https://user-images.githubusercontent.com/55683568/89338524-fe6cb200-d69c-11ea-9a45-9a0a5b75a151.png)

Foreword title looks good!

**Comment by Intelligent2013** [comment]
Sorry, looks like I've used old source XML before:
Updated version: [rice-amd.final.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/5027524/rice-amd.final.presentation.pdf)

**Comment by anermina** [comment]
All good now! Closing.
