### ISSUE TITLE
Automate XSLT update in gems

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-native-pdf#230]
### Intro

Thanks to @opoudjis for the suggestion of improvement which can help us to keep xslt up-to-date in our gems

### Problem

We need to always keep eye on xslt update & propagate them to gems

### Proposed solution

Implement separate GHA workflow which will be triggered by release (or other even on this repo), the steps of this flow
 - build XSLTs with `make xslts`
 - commit xslts which was generated according to the mapping bellow:
   ```
    cp xslt/iec.international-standard.xsl ../metanorma-iec/lib/isodoc/iec
    cp xslt/iso.international-standard.xsl ../metanorma-iso/lib/isodoc/iso
    cp xslt/iso.amendment.xsl ../metanorma-iso/lib/isodoc/iso
    cp xslt/itu.recommendation.xsl ../metanorma-itu/lib/isodoc/itu
    cp xslt/itu.recommendation-annex.xsl ../metanorma-itu/lib/isodoc/itu
    cp xslt/itu.resolution.xsl ../metanorma-itu/lib/isodoc/itu
    cp xslt/ogc.abstract-specification-topic.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.best-practice.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.change-request-supporting-document.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.community-practice.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.community-standard.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.discussion-paper.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.engineering-report.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.policy.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.reference-model.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.release-notes.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.standard.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.test-suite.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.user-guide.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.white-paper.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/ogc.other.xsl ../metanorma-ogc/lib/isodoc/ogc
    cp xslt/un.plenary.xsl ../metanorma-unece/lib/isodoc/un
    cp xslt/un.plenary-attachment.xsl ../metanorma-unece/lib/isodoc/un
    cp xslt/un.recommendation.xsl ../metanorma-unece/lib/isodoc/un
    cp xslt/csd.standard.xsl ../metanorma-csd/lib/isodoc/cc
    cp xslt/csa.standard.xsl ../metanorma-csand/lib/isodoc/csa
    cp xslt/rsd.standard.xsl ../metanorma-rsd/lib/isodoc/ribose
    cp xslt/m3d.report.xsl ../metanorma-m3d/lib/isodoc/m3aawg
    cp xslt/gb.recommendation.xsl ../metanorma-gb/lib/isodoc/gb
    cp xslt/iho.specification.xsl ../metanorma-iho/lib/isodoc/iho
    cp xslt/iho.standard.xsl ../metanorma-iho/lib/isodoc/iho
   ```

### Open questions

 - [x] Which event should trigger xslts update? Release event or some else even? - Use `push: on master` as trigger event

cc @opoudjis @Intelligent2013 @ronaldtse

**Comment by CAMOBAP** [comment]
@Intelligent2013 please let me know how do you think generally about the topic? Also maybe you have something to say for the open question?

**Comment by Intelligent2013** [comment]
@CAMOBAP when I update XSLTs, I change them in a separate branch to make sure that all PDF generate ok. After merge branch to master, XSLTs in `xslt_src` folder are ready to further use. I don't use a git versions. So I think you can triggered workflow on push or merging to master branch.

**Comment by CAMOBAP** [comment]
@Intelligent2013 thanks for your input, push to master as the event, works perfectly also

**Comment by opoudjis** [comment]
@CAMOBAP So has this functionality been implemented? That behaviour does not seem to be happening...

**Comment by CAMOBAP** [comment]
@opoudjis hmm, let me check

**Comment by Intelligent2013** [comment]
Ping @CAMOBAP.

**Comment by ronaldtse** [comment]
@Intelligent2013 I think @CAMOBAP is on holiday, he's returning the week after.

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse @Intelligent2013 

1. Should we rename the files below?
 - `xslt_src/csd.standard.core.xsl` -> `xslt_src/cc.standard.core.xsl`
 - `xslt_src/csd.standard.presentation.core.xsl` -> `xslt_src/cc.standard.presentation.core.xsl`
 - `xslt_src/m3d.report.core.xsl` -> `xslt_src/m3aawg.report.core.xsl`
 - `xslt_src/m3d.report.presentation.core.xsl` -> `xslt_src/m3aawg.report.presentation.core.xsl`
 - `xslt_src/mpfd.circular.core.xsl` -> `xslt_src/mpfa.circular.core.xsl
 - `xslt_src/mpfd.circular.presentation.core.xsl` -> `xslt_src/mpfa.circular.presentation.core.xsl`
 - `xslt_src/mpfd.compliance-standards-for-mpf-trustees.core.xsl` -> `xslt_src/mpfa.compliance-standards-for-mpf-trustees.core.xsl`
 - `xslt_src/mpfd.compliance-standards-for-mpf-trustees.presentation.core.xsl` -> `xslt_src/mpfa.compliance-standards-for-mpf-trustees.presentation.core.xsl`
 - `xslt_src/mpfd.guidelines.core.xsl` -> `xslt_src/mpfa.guidelines.core.xsl`
 - `xslt_src/mpfd.guidelines.presentation.core.xsl` -> `xslt_src/mpfa.guidelines.presentation.core.xsl`
 - `xslt_src/mpfd.standards.core.xsl` -> `xslt_src/mpfa.standards.core.xsl`
 - `xslt_src/mpfd.standards.presentation.core.xsl` -> `xslt_src/mpfa.standards.presentation.core.xsl`
 - `xslt_src/mpfd.supervision-of-mpf-intermediaries.core.xsl` -> `xslt_src/mpfa.supervision-of-mpf-intermediaries.core.xsl`
 - `xslt_src/mpfd.supervision-of-mpf-intermediaries.presentation.core.xsl` -> `xslt_src/mpfa.supervision-of-mpf-intermediaries.presentation.core.xsl`
 - `xslt_src/rsd.standard.core.xsl` -> `xslt_src/ribose.standard.core.xsl`
 - `xslt_src/rsd.standard.presentation.core.xsl` -> `xslt_src/ribose.standard.presentation.core.xsl`

2. As far as I understand we should copy any produced `xslt/*.xsl` except `*.presentation.*`, is that correct?

**Comment by ronaldtse** [comment]
@CAMOBAP rename: yes please.

> As far as I understand we should copy any produced xslt/*.xsl except *.presentation.*, is that correct?

@Intelligent2013 can you please help answer? Thanks!

**Comment by CAMOBAP** [comment]
> rename: yes please, an excellent find 😉 Also need to ping @opoudjis that the XSL names will change.

@ronaldtse @opoudjis I can change it in specific processors too. To be on the same page, should I care about potential backward compatibility issues or anything what should I check after this rename?

**Comment by ronaldtse** [comment]
>  I can change it in specific processors too.

@CAMOBAP thank you. I don't think there are side effects but let's see what @opoudjis says.

**Comment by Intelligent2013** [comment]
@CAMOBAP I didn't look at changes in PR yet, therefore answer about current situation.

> 1. Should we rename the files below?

Each xslt filename has a parts related to xml structure. For example, `csd.standard.presentation.core.xsl`:
- `csd` - <__csd__-standard xmlns="https://www.metanorma.org/ns/csd">
- `standard` - <doctype>__standard__</doctype>

This rules are using for PDF generating in mn-native-pdf in gh-pages branch.

If we change `csd` to `cc`, then we need some external determined rules for relationship between xslt filename and source xml file.

> 2. As far as I understand we should copy any produced xslt/*.xsl except *.presentation.*, is that correct?

@CAMOBAP in `xslt_src` folder there are two kind of *core*.xsl files:
- with `presentation` suffix - it should be used for PDF
- without `presentation` suffix - obsoleted xslt files and can be omitted.

So in xslt/*presentation.xsl should be used.

**Comment by CAMOBAP** [comment]
@Intelligent2013 thanks for the explanation, I asked about XSLT with `presentation` suffix because I didn't manage to find them in our `metanorma-*` processors, maybe @opoudjis can comment on this also.

**Comment by opoudjis** [comment]
Yes, I rename the *.presentation suffixes to strip them when I copy them into the individual gems.

There are indeed rules for allocating the multiple XSLTs of a flavour; they are often but not always doctype. The rules are implemented in the lib/isodoc/*/pdf_converter.rb files.

**Comment by Intelligent2013** [comment]
I propose to remove non-presentation in mn-native-pdf, and rename *presentation.core.xsl into *core.xsl (+ update Makefile).

**Comment by Intelligent2013** [comment]
@CAMOBAP  I'll do it in `feature/update-xslts-in-processors branch` if do you mind.

**Comment by CAMOBAP** [comment]
> I propose to remove non-presentation xslt in mn-native-pdf, and rename *presentation.core.xsl into *core.xsl (+ update Makefile).

Good idea

> @CAMOBAP I'll do it in feature/update-xslts-in-processors branch if do you mind.

Yes please, just let me know once you are done

**Comment by Intelligent2013** [comment]
@CAMOBAP Done.

**Comment by CAMOBAP** [comment]
It works!

Several commits were pushed:
 - https://github.com/metanorma/metanorma-itu/commit/eb5278238bd3044d4ee57a82ff3fc0ef043854ba
 - https://github.com/metanorma/metanorma-gb/commit/d9ec5318c0aa02b4898f9993283bf63eb3cd4ccc

For `itu` new XSLT files was added, so I prepared PR for it https://github.com/metanorma/metanorma-itu/pull/273

Closing this one
