### ISSUE TITLE
Presentation XML as basis for XSLTs

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#231]
I am finalising testing, and I am handing over the pres_xml branch of code to you to implement. 

https://github.com/metanorma/metanorma-docker/issues/87 will change docker to generate samples runs that use the new code structure, and therefore that will produce PresentationXML for you to consume.

This is the summary of changes that have been made, from https://github.com/metanorma/metanorma-standoc/issues/285

* STS and RFC will still be processed from the semantic (default) XML layer, so the changes being made in Presentation XML are only for PDF (and HTML, DOC)
* There shall be no autonumbering in the Presentation XML layer: all captions and headings will contain their autonumber
* All `xref` tags will be populated with the required autonumbered reference. The localities are left in place; they are used to infer whether an anchor is generated in HTML.
* The formula label will now be contained in `//formula/name`. (This is NOT a feature of semantic Metanorma XML.)
* The note label will now be contained in `//note/name` and `//termnote/name`. (This is NOT a feature of semantic Metanorma XML.)
* The term label will now be contained in `//term/name`. (This is NOT a feature of semantic Metanorma XML.)
* The recommendation, permission, requirement label will now be contained in `//permission/name`, `//requirement/name`, `//recommendation/name`. (This is NOT a feature of semantic Metanorma XML.)
* `clause/title` has a `depth=` attribute, indicating the level of heading that should be given for it; this is not always predictable (Annexes that are glossaries in NIST for example should treat the subheading "Glossary" at the same level as the Annex itself.) if it is absent, use the normal clause depth calculation. Sometimes it is added redundantly.
* I'm introducing `<tab/>` as a tab delimiter, to be used to separate section numbers from the section title. Word will render this as a single tab, HTML as a space.
* For OGC, added a Keywords and a Submitting Organisations preface clause to the presentation XML layer , identified as type=keywords and type=submitting_orgs

**Comment by opoudjis** [comment]
Reminder: this code is *all* in pres_xml. If you want to run metanorma locally to generate PresentationXML, you will have to switch to pres_xml branch for all gems involved. That means a gemfile like this (example for GB flavour):

```
gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "pres_xml"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "pres_xml"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "pres_xml"
gem "metanorma-gb", git: "https://github.com/metanorma/metanorma-gb", branch: "pres_xml"
````

**Comment by Intelligent2013** [comment]
I've modified gemfile for mn-samples-gb and tried to run metanorma locally ot generate PresentationXML, but without success:
```
Running locally via bundle ...
nil versions are discouraged and will be deprecated in Rubygems 4
bundler: failed to load command: metanorma (/home/intluser/.rbenv/versions/2.7.1/bin/metanorma)
ArgumentError: wrong number of arguments (given 3, expected 2)
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/metanorma-gb-ca1a355c3b92/lib/metanorma/gb/processor.rb:35:in `input_to_isodoc'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:122:in `process_input'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:21:in `compile'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/lib/metanorma/cli/compiler.rb:45:in `compile_file'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/lib/metanorma/cli/compiler.rb:30:in `compile'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/lib/metanorma/cli/compiler.rb:35:in `compile'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/lib/metanorma/cli/command.rb:37:in `compile'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/lib/metanorma/cli.rb:61:in `start'
  /home/intluser/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.3.2/exe/metanorma:20:in `<top (required)>'
  /home/intluser/.rbenv/versions/2.7.1/bin/metanorma:23:in `load'
  /home/intluser/.rbenv/versions/2.7.1/bin/metanorma:23:in `<top (required)>'
make: *** [Makefile:79: sources/rice.gb.sector.zh.xml] Error 1
```

So better I'll wait a metanorma-docker update.

**Comment by opoudjis** [comment]
Since I can't replicate this, I think we have a problem that's worth addressing now anyway. Have you done `bundle update` as well as `bundle install`?

I am happy to sent you Presentation XML bundles for various repositories to get you started.

**Comment by opoudjis** [comment]
Sent in Skype

**Comment by Intelligent2013** [comment]
Problem was solved after `gem install bundler`  (just repeat it).

**Comment by Intelligent2013** [comment]
XSLTs for presentation XMLs added into `master` branch.

**Comment by Intelligent2013** [comment]
XSLTs for presentation XML available:
https://github.com/metanorma/mn-native-pdf
https://github.com/metanorma/mn-native-pdf-nist

- *.presentation.xsl - for processing presentation xml.
- *.xsl - for processing non-presentation xml.
