### ISSUE TITLE
XSLT: change sections ordering

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#236]
Currently ordering (for ISO example) is:
- sections/clause[1]
- bibliography/references[1]
- sections/*[> 1]

Need to change to:
- default order
  - sections/clause[@type='scope']
  - references ~~[@obligation=normative]~~ [@normative='true']
  - terms
  - definitions
  - then the rest

- in amendments and technical corrigenda to ISO
  - ignore any such orderings, they are just a bunch of chapter

- General preface rule is:
  - Abstract
  - Foreword
  - Introduction
  - other Preface clauses
  - Acknowledgements

Exceptions:
- MPFA: there are only clauses, so no notion of pulling out references or terms and interpolating them
- MPFD: terms are considered the final part of the preface
- NIST: 
  - no interpolating of either terms or references in main section,  because terms and references are typically included within annexes, altnhough references not within annexes are processed before annexes
  - preface is: 
     - foreword, 
     - abstract, 
     - keywords, 
     - boilerplate, 
     - other preface clauses (which can include acknowledgements)
- OGC:
  - prefaces sections:
    - abstract, 
    - keywords (which is now an explicit clause), 
    - foreword, 
    - introduction, 
    - submitting organisations (which has a type now: submitting_orgs), 
    - submitters (ditto: type=submitters), 
    - other preface clauses, 
    - acknowledgements
  - scope
  - Conformance clause[@type=conformance]
  - normative references ~~(obligation = normative)~~ `[@normative='true']`
  - terms
  - definitions
  - other clauses
  - annexes
  - bibliography
  

- RSD:
  - preface
    - Abstract, 
    - foreword, 
    - executivesummary (which  is a separate tag), 
    - introduction, 
    - preface clauses, 
    - acknowledgements

- UN: no special treatment of references or terms, middle section is all just clauses, then annexes, then bibliography

**Comment by Intelligent2013** [comment]
@opoudjis in point of view of XML, how can I determine a section 'terms'?
`sections/terms` only or something else more?

I found in ITU XMLs (example G.650.1-201803.presentation.xml):
```xml
	<sections>
		<clause id="scope" type="scope"...><title depth="1">1.<tab/>Scope</title>...</clause>
		<clause id="definitions" obligation="normative">
			<title depth="1">3.<tab/>Definitions</title>
			<p id="_8a12faed-23ee-4672-93f0-26d55049fdeb">This Recommendation defines the following terms:</p>
			<terms id="general_definitions" obligation="normative">
				<title depth="2">3.1.<tab/>General definitions</title>
			...
			<terms id="mechanical_characteristics"
     				obligation="normative">
				<title depth="2">3.2.<tab/>Mechanical characteristics</title>
			...
		<definitions id="abbreviations_acronyms"
           			obligation="normative">
			<title depth="1">4.<tab/>Abbreviations and acronyms</title>
```

In this example `terms` inside clause. I.e. XML path is sections/clause/terms. It's correct?

**Comment by ronaldtse** [comment]
@Intelligent2013 just to confirm that MPFD and MPFA are the same flavor. Thanks.

**Comment by opoudjis** [comment]
Fixed OGC

**Comment by opoudjis** [comment]
> @opoudjis in point of view of XML, how can I determine a section 'terms'?
> `sections/terms` only or something else more?

You are right. terms includes clause[.//terms], and definitions includes clause[.//definitions].

Note correction in OGC, but I see you already did so.

A-OK.

**Comment by Intelligent2013** [comment]
> You are right. terms includes clause[.//terms], and definitions includes clause[.//definitions].

@opoudjis  These rules are not working for `T-Editing-Guidelines-201602.presentation.xml`. If I apply these rules, then resulted PDF has non-correct sections order:
![изображение](https://user-images.githubusercontent.com/5559926/89045497-4b2a5300-d354-11ea-906a-1df87105a6b2.png)

Section 4 and 8 show together in ToC, because they are 'definitions' both (In source XML `clause 8` has child `definitions`):

```xml
...
		<definitions id="Abbreviations_and_acronyms"
           			obligation="normative">
			<title depth="1">4.<tab/>Abbreviations and acronyms</title>
...
		<clause id="Description_of_core_material"
      			inline-header="false"
      			obligation="normative">
			<title depth="1">8.<tab/>Description of core material</title>
...
			<clause id="preScope"
      				inline-header="false"
      				obligation="normative">
				<title depth="2">8.1.<tab/>Scope</title>
...
			<definitions id="Core_material_abbreviations_and_acronyms"
           				obligation="normative">
				<title depth="2">8.4.<tab/>Abbreviations and acronyms</title>
...
```

**Comment by opoudjis** [comment]
The issue here is: "Symbols and abbreviated terms", which is what definitions clauses are titled as in other standards, is distinctive enough that it can be reliably identified by the title. However in ITU, the title of definitions clauses is just "Definitions", which is simply not distinctive enough. So I will tighten the rule for recognising it in generating Metanorma XML: in ITU, it will be automatically recognised only as a top level heading, or if given explicitly as a heading attribute.
