### ISSUE TITLE
ITU: Boilerplate text should be in XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#24]
> In mn-itu.xsl I hardcoded sections FOREWORD, NOTE, INTELLECTUAL PROPERTY RIGHTS and copyright, because there aren't these data in xml.

**Comment by ronaldtse** [comment]
@Intelligent2013 this ticket is now actionable. Can you help update ITU to read the boilerplate text from XML? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse I've did it a month ago yet.

**Comment by ronaldtse** [comment]
Got it. Thanks! Closing this now...
