### ISSUE TITLE
Review new OGC layout for issues in sample documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#243]
@metanorma/editors can you go through the generated OGC PDFs and see if there are any obvious issues we should fix in the layout?

e.g. title too large, fonts hard to read etc.

You can download the artifacts here: https://github.com/metanorma/mn-native-pdf/pull/242/checks?check_run_id=1056857057

(the 'xxx.presentation.pdf' files are the ones to check)

**Comment by Intelligent2013** [comment]
@metanorma/editors @manuel489 @anermina 
If you didn't start reviewing yet, then please updated PDFs from here:
https://github.com/metanorma/mn-native-pdf/pull/242/checks?check_run_id=1071504306
((the 'xxx.presentation.pdf' files)

I've fixed a few issues:
- removed blue color from links
- source code font fixed
- footnotes for first-level headings fixed

**Comment by manuel489** [comment]
Ok, these are the "obvious" issues that I've noticed:

1. Malformed em-dash rendering in *16-131r2*. Pages 1, 12, 17 (to name some). Ticket opened in https://github.com/metanorma/mn-native-pdf/issues/258

2. *Foreword* and *Introduction* prefatory sections are misplaced in *10-091r3*. They should be at the preface area and unnumbered. This, in part, is a markup mistake, the [.preface] attribute is missing for these sections. However, the numbering is still an issue. I have open a ticket for it in https://github.com/metanorma/metanorma-ogc/issues/194

3. In *12-077r1*, the indentation of the unordered list is very pronounced. Maybe we should remove the indentation for these cases? Ticket: https://github.com/metanorma/mn-native-pdf/issues/259

4. The requirements in *17-069* are numbered like they were tables even when they are, for example, typeset as
````
[[req_core_root_op]]
[.requirement,label="/req/core/root-op"]
====
[.requirement]
======
The server SHALL support the HTTP GET operation at the path  `/`.
======
====
````
which results in:
![requirement](https://user-images.githubusercontent.com/33627611/94996160-ed430300-0570-11eb-8112-0f992b541a15.PNG)

Apparently, this comes from another markup that is not currently in mn-samples-ogc repository.

5. In *17-069*, page 26, there is a Figure caption ("Figure 2") that points to nowhere. (This also happens in pages: 28 and 36.)
![figure-case](https://user-images.githubusercontent.com/33627611/94996458-e7e6b800-0572-11eb-8380-a9adf7a674f6.PNG)

6.  There are some figures missing in *19-004*, pages: 44, 45.  Only the caption is shown. (This is fixable by markup. Such "Figures" are actually the captions of the code blocks that are immediately above. This is an error from the original source, see Figures 25 and 26 in http://docs.opengeospatial.org/dp/19-004.html)

7. In *12-077r1*, very large string of characters (links) go beyond the margins of the page:
![issue7](https://user-images.githubusercontent.com/33627611/94996961-e965af80-0575-11eb-95f9-6fa8f35c4e34.PNG)

**Comment by manuel489** [comment]
The issue 5 from above was due to a markup error. It is fixed and merged to master.

**Comment by manuel489** [comment]
@Intelligent2013, all the issues listed above are fixed except for one:

> In 12-077r1, very large string of characters (links) go beyond the margins of the page:

![capture3](https://user-images.githubusercontent.com/33627611/106365505-7c3c0e00-630c-11eb-9774-84e34afea9f3.PNG)

Is it possible to fix?
(Good work btw!)

**Comment by Intelligent2013** [comment]
> 7. In 12-077r1, very large string of characters (links) go beyond the margins of the page:

@manuel489 fixed in XSLT for PDF (but in your screenshot looks as DOC or HTML):
![изображение](https://user-images.githubusercontent.com/5559926/106393500-86433700-6408-11eb-86d0-b135f0aee31d.png)

But there is one more issue due the source adoc. It shows in PDF:
![изображение](https://user-images.githubusercontent.com/5559926/106393519-a07d1500-6408-11eb-9d0e-7a02c0750a06.png)

In 12-077r1/sections/ab-examples.adoc there is a space here `gzip &Options`:
```
. The same request delivers the same image in some other format such as GeoTIFF, in a compressed unsigned 16-bit format. Optional advanced features need to be provided by the server.
+
--
`http://example.com/CS?CID=ece48e24ad2b41eab709984e272cbbc2&Request=GetMap&Service=IS&Version=1.0.0&CRS=EPSG:4326&Options.tif.band.datatype=u16&Options.tif.compress=gzip &Options.tif.type=geotiff&Format=image/tif&Exceptions=IMAGE&BBox=-78.94355126506584,43.85916706820535,-78.93842759427986,43.86007044647508&Width=1674&Height=400&Time=F101`
--
```

Due this issue, in source xml link splits by url and text:
![изображение](https://user-images.githubusercontent.com/5559926/106393584-02d61580-6409-11eb-8680-eb62ff73bedd.png)

Please remove the space.

**Comment by manuel489** [comment]
> @manuel489 fixed in XSLT for PDF
Thanks @Intelligent2013! 

> (but in your screenshot looks as DOC or HTML):

No, I that was PDF output indeed 😃 :
![Capture2](https://user-images.githubusercontent.com/33627611/106394874-52025300-63d5-11eb-85db-5a628a29b39a.PNG)


> Please remove the space.

Sure, thank you!

**Comment by manuel489** [comment]
Well, I think that is all for this ticket.  I'm closing.
(@anermina, you're welcome to re-open if you have something to add 😃 )
