### ISSUE TITLE
Indent and shrink note content

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#248]
Counterpart of https://github.com/metanorma/basicdoc-models/issues/8 for PDF: 

The following content may be found in notes: 

* unordered lists
* ordered lists
* definition lists
* formuale
* sourcecode
* blockquotes

All such content must be rendered in a smaller font than their counterparts outside of notes, if note paragraphs themselves are rendered in a smaller font.

All such content shall be indented by 1cm, so that it can be clearly identified as belonging to a note. Normal paragraphs in a note do not need to be indented if they are not already. (However, I am not currently indenting blockquotes any differently, given how strongly indented they already are.)

This applies to all flavours.

**Comment by Intelligent2013** [comment]
Done.
