### ISSUE TITLE
Malformed em-dash in generated OGC layouts

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#258]
*From https://github.com/metanorma/mn-native-pdf/issues/243*

It seems that `--` markup generates a malformed em-dash rendering.

For instance, in *16-131r2* (presentation version):

````
Every second day the human race generates as much data as was generated from the dawn of humanity through the year 2003
 footnote:[http://www.pbs.org/show/human-face-big-data/]. Big Data is both a challenge and an opportunity. Big Data is 
"`extensive datasets -- primarily in the characteristics of volume, variety, velocity, and/or variability -- that require a scalable 
technology for efficient storage, manipulation, management, and analysis.`" footnote:[ISO/IEC CD2 20546 Information 
Technology -- Big Data -- Overview and Vocabulary]
````

Renders:
![issue11](https://user-images.githubusercontent.com/33627611/94995133-36dc1f80-056a-11eb-903a-d7fc495adab2.PNG)

*footnote*
![em-dash2](https://user-images.githubusercontent.com/33627611/94995231-fa5cf380-056a-11eb-8614-b9dea3885c57.PNG)

**Comment by ronaldtse** [comment]
I think this is related to the font missing a Unicode space character. Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
Fixed. Thin-space is missing in some Arial font versions, so it replaced by 'space' char in xslt on fly.

![изображение](https://user-images.githubusercontent.com/5559926/95016691-45573380-065d-11eb-8ba8-2b52aa5b9569.png)

![изображение](https://user-images.githubusercontent.com/5559926/95016699-51db8c00-065d-11eb-9aab-e56dc5e93120.png)

Latest PDF available here:
https://github.com/metanorma/mn-native-pdf/runs/1205286044
