### ISSUE TITLE
Indentation of lists in table environment

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#259]
*From https://github.com/metanorma/mn-native-pdf/issues/243*

I think the indentation of the lists in table environment is too large. Maybe an adjustment is necessary for these cases?

From *12-077r1*:

![issue6](https://user-images.githubusercontent.com/33627611/94995726-3f365980-056e-11eb-865b-e4290dfd6084.PNG)

**Comment by ronaldtse** [comment]
@manuel489 agree. @Intelligent2013 can you help? Thanks.

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/95020404-9114d780-0673-11eb-96dd-d2038bab900e.png)


PDFs available here:
https://github.com/metanorma/mn-native-pdf/runs/1205511849
