### ISSUE TITLE
Enable PDF Accessibility in output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#26]
Apache FOP supports accessibility options:
https://xmlgraphics.apache.org/fop/2.4/accessibility.html

Metanorma XML supports accessibility options as shown here:
https://www.metanorma.com/blog/2019-10-08-metanorma-accessibility-html-word/

We should also enable [PDF/UA](https://xmlgraphics.apache.org/fop/2.4/accessibility.html#pdfua-iso-14289)

Here's what we need to do:

In Adobe Acrobat, the "Description" tab, we need to have:

* Title: [full title of document]
* (for the flavors that support them) Author: [list author names in the order they appear in the document, separated by semicolons]
* Subject: [Abstract]
* Keywords: [Keywords]
* Advanced > Tagged PDF: Yes
* Advanced > Fast Web View: Yes

"Fonts" tab:
* All fonts used are embedded (or indicated “Embedded Subset”)
 
"Initial view" tab:
* Window Options > Show: Document Title
 
"Advanced" tab:
* "Reading Options" > Language: English

**Comment by Intelligent2013** [comment]
PDF Accessibility added for all xsl templates.
