### ISSUE TITLE
Internal indentation in lists

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#260]
*From https://github.com/metanorma/mn-native-pdf/issues/243*
*This issue is related with https://github.com/metanorma/mn-native-pdf/issues/259*

This is personal opinion, but I think the internal indentation of the list items (in normal environment) is maybe too large.

![issue10](https://user-images.githubusercontent.com/33627611/95017035-d6f67f00-0624-11eb-9989-f748d02b1b1f.PNG)

@ronaldtse?

**Comment by Intelligent2013** [comment]
Duplicate https://github.com/metanorma/mn-native-pdf/issues/261

**Comment by manuel489** [comment]
Wow, didn't notice it was duplicated. Thanks @Intelligent2013!
