### ISSUE TITLE
Internal indentation of list items

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#261]
*From https://github.com/metanorma/mn-native-pdf/issues/243*
*This issue is related with https://github.com/metanorma/mn-native-pdf/issues/259*

This is personal opinion, but I think the internal indentation of the list items (in normal environment) is maybe too large?

![issue10](https://user-images.githubusercontent.com/33627611/95017035-d6f67f00-0624-11eb-9989-f748d02b1b1f.PNG)

@ronaldtse?

**Comment by Intelligent2013** [comment]
I've set indents as in source design PDF (https://github.com/metanorma/metanorma-ogc/issues/182):
![изображение](https://user-images.githubusercontent.com/5559926/95017701-94a06280-0663-11eb-80b6-bbacc9d27c02.png)

![изображение](https://user-images.githubusercontent.com/5559926/95017738-d5987700-0663-11eb-9b16-70a8eba3e76d.png)

Current indents are:
- from left margin - 13mm
- between start of list-item label (circle dot or number) - 12mm

I can set any value which you like. Just tell me the exactly value.

**Comment by manuel489** [comment]
> I've set indents as in source design PDF (metanorma/metanorma-ogc#182):

Thanks, I imagined something like that. Then I think it's better we leave it as it is.
