### ISSUE TITLE
BIPM brochure review: Horizontal misalignment in ToC

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#266]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

In table of contents, line breaks sometimes occur too late introducing a misalignment between the section title and the page number.

*Generated*
![issue1-generated](https://user-images.githubusercontent.com/33627611/96002201-dc16b380-0e06-11eb-9c44-805ff8f8476d.PNG)

*Original*
![issue1-original](https://user-images.githubusercontent.com/33627611/96002239-e46eee80-0e06-11eb-9bf6-2121e587d547.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/96346661-b3f8b000-10a5-11eb-833c-3cf92c9f5ad5.png)
