### ISSUE TITLE
BIPM brochure review: Spurious vertical space on page beginning

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#267]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

When a sub-clause starts in a new page, there is a spurious vertical space between beginning of a page and section title. (I believe this comes from the space between a paragraph and a sub-clause.) For example:

*Generated*
![issue6-generated](https://user-images.githubusercontent.com/33627611/96003741-8e9b4600-0e08-11eb-8170-bbf9745467e4.PNG)

*Original*
![issue6-original](https://user-images.githubusercontent.com/33627611/96003749-91963680-0e08-11eb-873b-2bce32ecef14.PNG)

**Comment by Intelligent2013** [comment]
Fixed.

Example:
![изображение](https://user-images.githubusercontent.com/5559926/96352520-7bb89800-10cc-11eb-847b-54cc9d886dba.png)
