### ISSUE TITLE
Eliminate local_bibdata

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#275]
local_bibdata has been removed as of https://github.com/metanorma/metanorma-bipm/issues/29

it is still mentioned in the ITU XSLT. The structure has been updated to:

````
<ext>
  <structuredidentifier>
    <amendment language=''>1</amendment>
    <amendment language='en'>Amendment 1</amendment>
    <corrigendum language=''>2</corrigendum>
    <corrigendum language='en'>Corrigendum 2</corrigendum>
  </structuredidentifier>
</ext>
````

Please ensure there are no mentions of local_bibdata in the XSLTs: 

````
<bibdata>
  <language current="true">fr</language>
  <status>
    <stage language="">in force</stage>
    <stage language="fr">en force</stage>
  </status>
</bibdata>

<localized-strings>
  <localized-string key="see" lang="fr">voir</localized-string>
</localized-strings>
````

is the structure now for enums: `//bibdata/status/stage[@language = "" or not(@language)]` is the enum value, and `//bibdata/status/stage[@language = "{lang}"]` is the display value. The same applies for `//bibdata/status/substage` and `//bibdata/ext/doctype`

**Comment by Intelligent2013** [comment]
Done.
