### ISSUE TITLE
ITU: xml markup in document text

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#28]
In source/itu-T-Editing-Guidelines-201602.xml  there is a markup:
```
<p id="_7571feeb-d6f1-47bc-a445-0ad010b90a56">The draft <title of="" the="" draft="">, which is proposed for approval, consent or determination:</title>
		</p>
```
which displayed in doc as:
`The draft <title of="" the="" draft="">, which is proposed for approval, consent or determination:</title>
`
But in point of view of xml the tag <title is usual tag, not simple text. I think this text should be coded as:
`&lt;title .... &gt;, ... &lt;/title&gt;`
for correct processing in xslt in displaying in PDF.

**Comment by ronaldtse** [comment]
This might be a bug in metanorma-itu. Posting there.

**Comment by opoudjis** [comment]
As noted, this issue was fixed last week, and the XML now has the correct markup with `&lt;...&gt;`. Please use the latest XML, it is being refreshed on the mn-samples-itu repository as I update the gems.
