### ISSUE TITLE
BIPM xslt: mathvariant="script" issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#289]
Source issue:
https://github.com/metanorma/bipm-si-brochure/issues/44#issuecomment-736876159

Source xml:
```xml
<stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML">
		<mstyle mathvariant="script">
			<mtext>K</mtext>
		</mstyle>
	</math>
</stem>, <stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML">
		<mi>m</mi>
		<mfenced open="(" close=")">
			<mrow>
				<mstyle mathvariant="script">
					<mtext>K</mtext>
				</mstyle>
			</mrow>
		</mfenced>
	</math>
</stem>
```

Original PDF:
![изображение](https://user-images.githubusercontent.com/5559926/101172825-ba8db780-3652-11eb-931e-7974c1f756a1.png)

Resulted PDF generated on Win7:
![изображение](https://user-images.githubusercontent.com/5559926/101172932-e1e48480-3652-11eb-8bcd-efd2778efae7.png)

Resulted PDF generated on MacOS:
![изображение](https://user-images.githubusercontent.com/5559926/101173077-13f5e680-3653-11eb-820b-07ab32f720bb.png)

**Comment by Intelligent2013** [comment]
In the original DOC, the font `Monotype Corsiva` is using for `K`.

**Comment by Intelligent2013** [comment]
In jEuclid these fonts hardcoded for using in case of `mathvariant="script"`:
- EUSM10, 
- cmsy10, 
- Math5,
- Mathematica5, 
- Savoye LET, 
- Brush Script MT, 
- Zapfino, 
- Apple Chancery, 
- Edwardian Script ITC, 
- Lucida Handwriting,
- Monotype Corsiva, 
- Santa Fe LET

(`jeuclid\jeuclid-core\src\main\java\net\sourceforge\jeuclid\context\LayoutContextImpl.java`)

The font `Savoye LET` (installed on MacOS by default) is using to display `K` in PDF.
The font `Monotype Corsiva` installed on Win7 by default.

I've installed `Savoye LET` on Win7 and get the same result as on Mac:
![изображение](https://user-images.githubusercontent.com/5559926/101192602-5b3ca100-366c-11eb-90ff-581729391b81.png)

If two fonts from list installed on system, then first font will be used. I.e. even we'll install ``Monotype Corsiva` on MacOS, then  `Savoye LET` will be used in any case.

To do: find the solution how to specify/redefine 'script' font list.

**Comment by Intelligent2013** [comment]
To redefine 'script' font list - put LayoutContextImpl.java and change order (move Monotype Corsiva at first place):
```java
        final List<String> fontsScript = new ArrayList<String>(12);
        fontsScript.add("Monotype Corsiva");
        fontsScript.add("EUSM10");
        fontsScript.add("cmsy10");
        fontsScript.add("Math5");
        fontsScript.add("Mathematica5");
        fontsScript.add("Savoye LET");
        fontsScript.add("Brush Script MT");
        fontsScript.add("Zapfino");
        fontsScript.add("Apple Chancery");
        fontsScript.add("Edwardian Script ITC");
        fontsScript.add("Lucida Handwriting");
        fontsScript.add("Santa Fe LET");
```

Next tasks:
- Monotype Corsiva is licensed fonts, then need to find an alternative font and put at second place in the list;
- reorder font list - move similar looks font upper.

**Comment by Intelligent2013** [comment]
@ronaldtse I've found the font 'TeXGyreChorus' (https://github.com/brechtm/rinoh-typeface-texgyrechorus) that looks similar to 'Monotype Corsiva':

### Monotype Corsiva:

![изображение](https://user-images.githubusercontent.com/5559926/101244434-9e078300-3717-11eb-9752-4262f3698f90.png)

### TeXGyreChorus:
![изображение](https://user-images.githubusercontent.com/5559926/101244484-df982e00-3717-11eb-909a-0d63bd1b01fb.png)

Could we use it when 'Monotype Corsiva' doesn't available?

**Comment by ronaldtse** [comment]
> Could we use it when 'Monotype Corsiva' doesn't available?

 Looks good to me! Let's replace Monotype Corsiva on all platforms with TeXGyreChorus. The Fontist formula task is now at fontist/formulas#61 .

**Comment by Intelligent2013** [comment]
Done in mn2pdf v1.25: https://github.com/metanorma/mn2pdf/releases/tag/v1.25
