### ISSUE TITLE
ISO: Support MathML using new JEuclid

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#3]
JEuclid seems to be incompatible with the latest Apache FOP 2.4, but there is an active fork at https://github.com/rototor/jeuclid which supports FOP.

This task is to integrate that into:
* the installation and usage flow of this repository
* GitHub Actions for continuous integration

**Comment by Intelligent2013** [comment]
@ronaldtse I've tried to install rototor's fork jars into FOP, but it seems FOP doesn't see these jars.
Regarding
> There is no ServiceLoader configuration in this fork of the FOP plugin so it will not be auto-configured and needs to be loaded manually when desired using the following code: JEuclidFopFactoryConfigurator.configure(factory);

jars will work only in own application on Java which utilized FOP via API. I.e. in CLI isn't working.
I can develop on Java a simple program for it.

**Comment by ronaldtse** [comment]
@Intelligent2013 got it, let's go the Java route in loading the fork. Look forward to seeing the integration. Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse 
I've developed 'xml2pdf' java application (maven project) to run FOP programmatically with JEuclid fork library. Makefile updated also. It seems, mathml equation displays ok in pdf now.
