### ISSUE TITLE
ISO: Setup Chinese font for produce PDF

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#30]
Source xml:iso-rice-zh.xml,
Necessary to find SimSun font for ubuntu and add step into workflow (on windows pdf display ok with SimSun font), or find similar good font.

**Comment by ronaldtse** [comment]
We can install Adobe's Source Han fonts to replace SimSun:

e.g.
https://gist.github.com/enzinier/8d00d3f37d2e23985dcfa65662d163fa

**Comment by ronaldtse** [comment]
These fonts will be handle all Chinese, Japanese and Korean text.

Source Han Sans

https://github.com/adobe-fonts/source-han-sans/raw/release/OTC/SourceHanSansOTC_EL-R.zip

https://github.com/adobe-fonts/source-han-sans/raw/release/OTC/SourceHanSansOTC_M-H.zip

Source Han Serif

https://github.com/adobe-fonts/source-han-serif/raw/release/OTC/SourceHanSerifOTC_EL-M.zip

https://github.com/adobe-fonts/source-han-serif/raw/release/OTC/SourceHanSerifOTC_SB-H.zip

**Comment by ronaldtse** [comment]
Google's Noto CJK is identical to Adobe's Source Han:

https://www.google.com/get/noto/help/cjk/

**Comment by Intelligent2013** [comment]
@ronaldtse Thank you for your help!
Apache FOP doesn't support OTC fonts, but I found Han Sans TTF, converted from OTC here:
https://github.com/Pal3love/Source-Han-TrueType
I've updated xsl, font and workflow files for macos and ubuntu in the branch ronaldtse-add-iso-rice.

![image](https://user-images.githubusercontent.com/5559926/69916998-b7c21a80-1472-11ea-9c0b-11128942e766.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! It looks great now!
