### ISSUE TITLE
OGC document review: Front page in white-paper document

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#307]
*In relation to https://github.com/metanorma/mn-native-pdf/issues/89*

In 16-131r2, front page is slightly different in PDF vs DOC:

*PDF:*

![issue1-pdf](https://user-images.githubusercontent.com/33627611/106646100-a76c6a80-6563-11eb-8fec-30649aae9cec.PNG)

*DOC:*

![issue1-doc](https://user-images.githubusercontent.com/33627611/106645754-2a40f580-6563-11eb-960c-a5a709f98d8d.PNG)

In DOC, relevant metadata is listed, but not in PDF.
Is this difference important?

**Comment by Intelligent2013** [comment]
OGC XSLT updated for rendering these additional bibdata fields.
![изображение](https://user-images.githubusercontent.com/5559926/106752132-254f7500-663b-11eb-8c24-b5bfc71017bd.png)
