### ISSUE TITLE
ISO: Differences in structure of iso-rice-en  and iso-rice-zh

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#31]
There are differences between xml and doc for ISO rice.

1. In iso-rice-zh.xml there isn't section/preface/introduction, looks like it moved into sections/clause (first clause), i.e. second clause in iso-rice-zh.xml is first clause (Scope) in iso-rice-en.xml.

2. If compare docs iso-rice-en.doc  and iso-rice-zh.doc :
- in iso-rice-zh.doc  section 'Normative references' (7 elements) moved at the end of document as Bibliography (7 elements)
- in iso-rice-zh.doc  there isn't last Bibliography section which contains 16 elements (in iso-rice-en.doc).
But xml there are such data.

3. In iso-rice-en.xml  the section 'Terms and definitions' placed in terms/term tag, but iso-rice-zh.xml this section placed in clause/clause tag.
These texts 'paddy', 'husked rice', 'milled rice' display in Contents table (see image), because they are in clause/clause (we show 1st and 2nd level titles from clauses).

![Untitled](https://user-images.githubusercontent.com/5559926/69905029-70c71d00-13bf-11ea-9b08-efbc3a543d2b.png)

**Comment by ronaldtse** [comment]
1. In the TOC, individual terms should not be TOC entries.

2. The difference in Normative References and Bibliography are probably errors. Tracking in https://github.com/metanorma/metanorma-iso/issues/299 .

**Comment by Intelligent2013** [comment]
> 1. In the TOC, individual terms should not be TOC entries.

I display 1st and 2nd levels of clauses (for example, 4 and 4.1, 4.2) in TOC.
In https://metanorma.github.io/mn-samples-iso/documents/iso-rice-zh.xml, individuals terms placed in clause(s):
![image](https://user-images.githubusercontent.com/5559926/71006755-e8eb4d80-20f6-11ea-8507-f65202321940.png)

In https://metanorma.github.io/mn-samples-iso/documents/iso-rice-en.xml, individuals terms places in term(s), so it's correct:
![image](https://user-images.githubusercontent.com/5559926/71006805-fc96b400-20f6-11ea-9612-af5dc581d14e.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 thank you for the explanation. I can confirm that the XML generated is incorrect. This will be resolved in https://github.com/metanorma/metanorma-iso/issues/299 .

**Comment by opoudjis** [comment]
@Intelligent2013 I've fixed these. 

Yes I know it's taken a month. I have a large backlog...
