### ISSUE TITLE
PDF vs DOC: Numbered list in IEC document

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#310]
*In relation to https://github.com/metanorma/mn-native-pdf/issues/58*

Currently, lists are numbered differently in PDF compared to DOC.

PDF:
![issue1-pdf](https://user-images.githubusercontent.com/33627611/107858919-0906c180-6e0d-11eb-841c-8d1836618d78.PNG)

DOC:
![issue1-doc](https://user-images.githubusercontent.com/33627611/107858921-0a37ee80-6e0d-11eb-86ca-e56dd0464467.PNG)

And, looking at the [original document](https://www.iso.org/files/live/sites/isoorg/files/developing_standards/docs/en/model_document-rice_model.pdf),  seems like DOC has the correct approach?

**Comment by Intelligent2013** [comment]
@manuel489 This issue relates to https://github.com/metanorma/mn-native-pdf/issues/296 and https://github.com/metanorma/isodoc/issues/245 for all flavors.
But IEC xslt partially fixed now for this issue. Here is resulted PDF: [iec-rice-en.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/5980830/iec-rice-en.presentation.pdf)

**Comment by manuel489** [comment]
Thank you @Intelligent2013!
