### ISSUE TITLE
Insert white spaces in "mod" operator

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#311]
*In relation to https://github.com/metanorma/mn-samples-jcgm/pull/7*

Currently, we need to add white spaces  side-by-side in module operator (`mod`).

Example:
````
stem:[i_j = a_j xx (i_j mod b_j) - c_j xx floor(i_j//b_j)]
````
renders in PDF as:

![Capture1](https://user-images.githubusercontent.com/33627611/108908124-5519e900-75f9-11eb-8cbc-cd3d3b3ca6d9.PNG)

Original source:
![Capture2](https://user-images.githubusercontent.com/33627611/108908630-eab57880-75f9-11eb-9bdf-b03648b50612.PNG)

Thanks!

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/109428346-d44b5a80-7a07-11eb-9ed4-b5117c883492.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by manuel489** [comment]
Thank you @Intelligent2013 !
Closing
