### ISSUE TITLE
Arabic right-to-left text direction support

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#314]
Add Arabic right-to-left text direction support.

Source issues:
- https://github.com/metanorma/metanorma-itu/issues/274
- https://github.com/ituob/service-publications-docs/issues/17

Original PDF in Arabic: https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164D-2016-PDF-A.pdf

FOP support: https://xmlgraphics.apache.org/fop/2.5/complexscripts.html

To do:
- in ITU xslt in `fo:root` add 
```xml
<xsl:if test="$lang = 'ar'">
	<xsl:attribute name="writing-mode">rl-tb</xsl:attribute>
</xsl:if>
```
- find and add font with Arabic glyphs (https://xmlgraphics.apache.org/fop/2.5/complexscripts.html#fonts_arabic). Traditional Arabic?

- change default _hard-coded_ alignment from `text-align="left"` to `text-align"right"` (for section's headers, table-cells, etc.)

**Comment by Intelligent2013** [comment]
Used Arabic fonts in T-SP-E.164D-2016-PDF-A.pdf:
![image](https://user-images.githubusercontent.com/5559926/115555987-d23fa280-a2b8-11eb-9291-338c3cf38f47.png)

**Comment by Intelligent2013** [comment]
Arabic text looks very strange (it seems each glyph rendered separaterely) in the resulted PDF (Apache FOP):
![image](https://user-images.githubusercontent.com/5559926/115758041-5ec88e80-a3a7-11eb-8cfe-ace589128aac.png)

in comparison to original PDF:
![image](https://user-images.githubusercontent.com/5559926/115758131-76077c00-a3a7-11eb-879a-0fe0e90e272e.png)

But if copy-paste this text from both original and resulted PDF to Word, it looks identical (font Traditional Arabic):

![image](https://user-images.githubusercontent.com/5559926/115759189-a4d22200-a3a8-11eb-859b-b1db467adc69.png)

**Comment by ronaldtse** [comment]
Looks like that Arabic ligatures are not showing up. This seems to fix it: https://stackoverflow.com/questions/65309548/fop-arabic-letter-spacing

**Comment by Intelligent2013** [comment]
Everything is correct in FOP config. When I've removed `xml:lang="ar"` attribute from xslt it renders ok:
![image](https://user-images.githubusercontent.com/5559926/115851665-e22dc280-a42f-11eb-903f-f2b3813878a9.png)

I've asked about this issue here https://stackoverflow.com/questions/67227341/apache-fop-spaces-between-arabic-glyphs

**Comment by opoudjis** [comment]
So... Should I not be doing changes in the source XML, to introduce bidi characters?

**Comment by ronaldtse** [comment]
I don’t think the xml needs any changing, right?

**Comment by Intelligent2013** [comment]
No need to change xml.

I've removed `xml:lang="ar"` (I hope temporarely, until someone answers for my question on stackoverfow).
Resulted PDF: [T-SP-E.164D-2016-A.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/6375981/T-SP-E.164D-2016-A.presentation.pdf)

**Comment by opoudjis** [comment]
The XML doesn't; but I'll need to understand what you've done, @Intelligent2013, in case I need to do something similar in Word or HTML (and I think I will).

**Comment by Intelligent2013** [comment]
@opoudjis 
1. set globally 'right-to-left' text direction property (https://www.w3.org/International/questions/qa-html-dir), except cover page, because this property changes table's column order.
2. for cover page (in case of fixed table template), set  'right-to-left' text direction property inside each cell.
3. instead of properties text-align="left" and text-align="right" use text-align="start" and text-align="end".

**Comment by Intelligent2013** [comment]
It seems I've found a place of the bug in FOP.
In the class `src\main\java\org\apache\fop\complexscripts\fonts\OTFAdvancedTypographicTableReader.java` determined a variable
```java
private static String defaultTag = "dflt";
```
It should be redefined (see `dt = lt;`) in the function:
```java
private void readScriptTable(OFTableName tableTag, long scriptTable, String scriptTag) throws IOException {
		...
		// read default language system table offset
		int dl = in.readTTFUShort();
		String dt = defaultTag;
		if (dl > 0) {
			...
		}
		// read language system record count
		int nl = in.readTTFUShort();
		List ll = new java.util.ArrayList();
		if (nl > 0) {
				String[] lta = new String[nl];
				int[] loa = new int[nl];
				// read language system records
				for (int i = 0, n = nl; i < n; i++) {
						String lt = in.readTTFString(4);
						int lo = in.readTTFUShort();
...
						lta[i] = lt;
						loa[i] = lo;
						if (dl == lo) {
								dl = 0;
								dt = lt;
						}
						ll.add(lt);
				}
	...
```

but this never happens. Looks there is an issue in `readTTF...` functions...

The result of the function `readScriptTable` is using in the class `src\main\java\org\apache\fop\complexscripts\fonts\GlyphTable.java` in the variable `lookups`.
Content of `lookups`:

![image](https://user-images.githubusercontent.com/5559926/132952025-8cb2b978-95ba-470b-9f76-4a14488bcc93.png)

Glyph table contains the value 'dflt' - the value of the variable `defaultTag`.

In the function:
```java
public List<LookupSpec> matchLookupSpecs(String script, String language, String feature) {
	Set<LookupSpec> keys = lookups.keySet();
	List<LookupSpec> matches = new ArrayList<LookupSpec>();
	for (Object key : keys) {
			LookupSpec ls = (LookupSpec) key;
			if (!"*".equals(script)) {
					if (!ls.getScript().equals(script)) {
							continue;
					}
			}
			if (!"*".equals(language)) {
					if (!ls.getLanguage().equals(language)) {
							continue;
					}
			}
			if (!"*".equals(feature)) {
					if (!ls.getFeature().equals(feature)) {
							continue;
					}
			}
			matches.add(ls);
	}
	return matches;
}
```

there is a checking the document's language value (value from the attribute `xml:lang` (if this attribute didn't set, then the default value `dflt` is using) ) and the value from Glyph table:
- in case if the attribute `xml:lang` is omitted (i.e. value `dflt` is using), then the result of checking is true (`"dflt" = "dflt"`), and glyph table is using in further processing for displaying (PDF is correct in this case)
- in case if the attribute `xml:lang` is set (`xml:lang="ar"`), the the result of checking is false (`"ar" != "dflt"`), and glyph table is ignoring.
The logic of font reader classes is too complicated to understand it in the reasonable time.

Workaround solution - set language to the default value `dflt` in case if has value 'ar':
```java
if ((language == null) || "none".equals(language) || "ar".equals(language)) {
        language = "dflt";
}
```
In this case:
- Arabic language will be set in PDF  (`/Lang (ar)`), and PDF will be generated PDF/UA-1 mode
- PDF will be rendered with joined glyphs as expected:
![image](https://user-images.githubusercontent.com/5559926/132953240-a64d54f0-0498-4df6-8cdb-3557c5067df8.png)

**Comment by Intelligent2013** [comment]
Fixed.
