### ISSUE TITLE
Add BSI layout

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#316]
Add BSI xslt for PDF rendering.
Source documents: https://github.com/metanorma/mn-samples-bsi/tree/master/reference-docs

**Comment by Intelligent2013** [comment]
Used fonts:
- Frutiger-Bold
![image](https://user-images.githubusercontent.com/5559926/116678368-e585f880-a9b1-11eb-94a1-ea3e209af55d.png)

- Frutiger-Roman
![image](https://user-images.githubusercontent.com/5559926/116678515-136b3d00-a9b2-11eb-9f54-25eb7a7745e6.png)

**Comment by Intelligent2013** [comment]
Initial version of BSI xslt added (based on ISO xslt). Resulted PDF for BS ISO 44001 (rendered on xml generated by metanorma-iso):
[document.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/6405481/document.presentation.pdf)

**Comment by Intelligent2013** [comment]
@ronaldtse actually, there are a few kind of 1st page designs in source PDFs:
1. adoptions\bs-en-12973\
![image](https://user-images.githubusercontent.com/5559926/116699321-1b38da80-a9ce-11eb-9834-862ff071d414.png)

2. adoptions\bs-iso-44001 :
![image](https://user-images.githubusercontent.com/5559926/116699745-9dc19a00-a9ce-11eb-9cdb-c08a3ef6e17c.png)

3. adoptions\bsi-iso-30042:
![image](https://user-images.githubusercontent.com/5559926/116700139-217b8680-a9cf-11eb-91ae-9afb37a25789.png)

4. bs-codes-of-practice\bs-7273-4-2015-A1-2021 
![image](https://user-images.githubusercontent.com/5559926/116705620-66a2b700-a9d5-11eb-9c88-906f5212d8af.png)

5. bs-design-requirements\bs-4592-0-A1-2012 
![image](https://user-images.githubusercontent.com/5559926/116705244-fc8a1200-a9d4-11eb-9068-375d729ec9e4.png)

6. bs-specification\bs-8887-220:
![image](https://user-images.githubusercontent.com/5559926/116705677-75896980-a9d5-11eb-8136-2b787d4b6869.png)

7. pas\pas-2030\PAS 2035.pdf:
![image](https://user-images.githubusercontent.com/5559926/116705947-c600c700-a9d5-11eb-966f-d7747fc21a2f.png)

8. pas\pas-7000\PAS 7000.pdf:
![image](https://user-images.githubusercontent.com/5559926/116706074-e3ce2c00-a9d5-11eb-87e4-2075cac774ab.png)

9. pas\BSI-PAS0.pdf:
![image](https://user-images.githubusercontent.com/5559926/116706205-095b3580-a9d6-11eb-943b-14ae1cb0eb80.png)

What kind of cover should be used in resulted PDF? (current xslt developed for 2nd)

**Comment by ronaldtse** [comment]
Moved to https://github.com/metanorma/mn-native-pdf-bsi/issues/1 , closing.
