### ISSUE TITLE
trigger the autopush mn-native-pdf-nist if common.xsl is updated

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#317]
The problem: xslts in the repository https://github.com/metanorma/mn-native-pdf-nist/ updated March, 15, and automatically updated in metanorma-nist (by update-xslts-in-processor task in Makefile).
common.xsl in this repository (mn-native-pdf) updated a few days ago.
Xslts  in the repository https://github.com/metanorma/mn-native-pdf-nist/ depend on common.xsl and should be updated sync when common.xsl changed, otherwise we get inconsistent xslts in metanorma-nist.

To do: when common.xsl is updated in this repository, then need to trigger https://github.com/metanorma/mn-native-pdf-nist/
For example: `git commit --allow-empty -m "trigger"` for mn-native-pdf-nist repo.

I think the similar problem relates to mn-native-pdf-bsi repo.

**Comment by CAMOBAP** [comment]
Done, test in progress https://github.com/metanorma/mn-native-pdf/runs/2727358672?check_suite_focus=true

**Comment by ronaldtse** [comment]
@CAMOBAP the run passed. Is this done then?

**Comment by CAMOBAP** [comment]
Yep. done
