### ISSUE TITLE
ISO: what does mean char 'E' in ISO/CD 17301-1(E)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#32]
What does mean char 'E' on cover page in line: 
ISO/CD 17301-1(E)

![Untitled2](https://user-images.githubusercontent.com/5559926/69905062-ea5f0b00-13bf-11ea-9c25-0ddfe4fe79d4.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 the "(E)" means the document is in English. If it is "(F)" it is in French.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 the "(E)" means the document is in English. If it is "(F)" it is in French.

@ronaldtse Thanks. But in case of Chinese? (for -zh- doc)

**Comment by ronaldtse** [comment]
@Intelligent2013 I think it should be "C" but Chinese is not an official ISO language. Russian will be "R", German will be "D". I think this should be provided by the XML directly?

**Comment by Intelligent2013** [comment]
@ronaldtse yes, there is tag /iso-standard/bibdata/language.
In iso-rice-en.xml language=**en**, but in  iso-rice-zh.xml language=**zh**. In the current version mn-iso.xsl I get first letter in upper-case, and for Chinese it shows as (Z). Should I translate to (C)?

**Comment by ronaldtse** [comment]
@Intelligent2013 In the XML file there should be an attribute that directly provides the text "ISO/CD 17301-1(E)", I'm filling a bug in metanorma-iso about it. In the meantime, just do without the (E).
