### ISSUE TITLE
XSLT: prefix to the document identifier

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#320]
Source: https://github.com/metanorma/metanorma-iso/issues/508#issuecomment-863313600
`no longer make the decision as to whether to prefix the document identifier or not`

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-iso/issues/508 is closed.

No pressure at all :-) , but I will not release the Metanorma stack until you have realised this ticket. As I said, the prefix will already come inserted in bibitem/docidentifier from now on; so you will receive `<docidentifier type="IETF">IETF RFC 20</docidentifier>`, and you will no longer need to inject "IETF" yourself.

**Comment by Intelligent2013** [comment]
Done.
