### ISSUE TITLE
Customize Tagging

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#326]
Source: https://github.com/metanorma/bipm-si-brochure/issues/149

In all XSLTs add:
- `H1` to `H6` for headers
- `L` for lists

Apache FOP doc: http://xmlgraphics.apache.org/fop/2.4/accessibility.html#customTags

**Comment by Intelligent2013** [comment]
Done:

- added `H1` to `H6` for headers:

![image](https://user-images.githubusercontent.com/5559926/131260407-ef917cab-c28a-4922-b371-72b4c977f21c.png)

- `L` for lists, `LI` for list item - no need to add it. it creates by default (for fo:list-body and fo:list-item elements):

![image](https://user-images.githubusercontent.com/5559926/131260323-d61e5343-4622-41a1-8f94-8444f87f5b84.png)

- added `TOC` and `TOCI` for Table of Contents:

![image](https://user-images.githubusercontent.com/5559926/131260514-085db25d-b4f0-43a4-bfde-8b02f2ad143a.png)

- added `BlockQuote` for quotes:

![image](https://user-images.githubusercontent.com/5559926/131260611-260ebcc0-fc11-4f88-a4e6-594c62761992.png)

- added `Index` for index:

![image](https://user-images.githubusercontent.com/5559926/131260668-6c7177dc-644a-4dc6-bfaa-553dba1ecdf7.png)

- added `Code` for source code:

![image](https://user-images.githubusercontent.com/5559926/131260693-7bd5ac25-1fdb-437c-9e5e-4b45f472cdd8.png)

**Comment by ronaldtse** [comment]
Excellent work. We should add a blog post about accessibility tagging in PDF.
