### ISSUE TITLE
Repeatable footnotes processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#334]
In mn xml there is case when a few footnotes have the identical text:
```xml
<clause id="_">
   <title depth="3">9.3.1.
   <p id="_">. . . <fn reference="5"><p id="_">Footnotes text 12345</p></fn> . . .
. . .
<clause id="_">
   <title depth="3">9.2.3.
   <p id="_">. . . <fn reference="5"><p id="_">Footnotes text 12345</p></fn> . . .
```

For some xslt this situation causes the critical error:
`
Caused by: org.apache.fop.fo.ValidationException: Property ID "footnote_5" (found on "fo:inline") previously used; ID values must be unique within...
`
due two footnote body with inline with the same id:
```xml
<fo:footnote-body>
... <fo:inline ...  id="footnote_5">5</fo:inline>...
</fo:footnote-body>
...
<fo:footnote-body>
... <fo:inline ...  id="footnote_5">5</fo:inline>...
</fo:footnote-body>
```

To do: footnote body should be created only for first footnote entrance.
It seems similar issue fixed for ISO and IHO already. Need to check for all xslt:
- [x] BIPM
- [x] BSI
- [x] CSA
- [x] CSD
- [x] IEC
- [x] IHO
- [x] ISO
- [x] ITU
- [x] JCGM
- [x] M3A
- [x] MPFA
- [x] NIST
- [x] OGC
- [x] Ribose
- [x] UN

**Comment by ronaldtse** [comment]
I don't think MN XML is supposed to have identical IDs on elements with identical footnote. Maybe this is an MN bug?

**Comment by Intelligent2013** [comment]
> I don't think MN XML is supposed to have identical IDs on elements with identical footnote. Maybe this is an MN bug?

@ronaldtse there isn't issue in MN XML. Xslt creates footnote for each `fn`:
```xml
<fn reference="5"><p id="_"><p > . . .
```
If there are a few `fn` with the same `@reference`, then we get a few footnote-body with identical `@id`:
```xml
<fo:footnote-body>
... <fo:inline ...  id="footnote_{@reference}">{@reference}</fo:inline>...
</fo:footnote-body>
...
<fo:footnote-body>
... <fo:inline ...  id="footnote_{@reference}">{@reference}</fo:inline>...
</fo:footnote-body>
```

I've fixed this issue for OGC already, and in progress for other flavors.
