### ISSUE TITLE
Process ToC levels to render

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#337]
Source: https://github.com/metanorma/metanorma-ogc/issues/328

TBD: pass ToC levels parameter via mn2pdf command line or metanorma xml.

**Comment by ronaldtse** [comment]
@Intelligent2013 note that the following functionality already exists in Metanorma:

https://www.metanorma.org/author/topics/document-format/sections/

> By default, the table of contents includes two levels of heading. More levels of heading can be set by using the document attribute :toclevels:; e.g. :toclevels: 3 for three levels of heading included. The number of levels of heading to include can be set separately for HTML/PDF and for DOC, by using the document attributes :htmltoclevels: and :doctoclevels:.

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/metanorma/issues/226:
> * //misc-container/presentation-metadata[name = "TOC Heading Levels"]/value
> * //misc-container/presentation-metadata[name = "HTML TOC Heading Levels"]/value
> * //misc-container/presentation-metadata[name = "DOC TOC Heading Levels"]/value

**Comment by Intelligent2013** [comment]
Done.
