### ISSUE TITLE
Editor: Review generation of ISO document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#34]
Please spot the differences between the source and generated PDF. Both are attached here. Thanks!
[iso-rice-en.pdf](https://github.com/metanorma/mn-native-pdf/files/3909903/iso-rice-en.pdf)

[iso-rice-en.doc.zip](https://github.com/metanorma/mn-native-pdf/files/3909907/iso-rice-en.doc.zip)

**Comment by anermina** [comment]
1. Header has extra "(E)"
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985447-777a9f00-153b-11ea-8263-08605415a138.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985461-81040700-153b-11ea-8759-971b91a4d2f4.png)

2. In Table of Contents, there should be no Appendix 1 Sample code
rendered:
![image](https://user-images.githubusercontent.com/55683568/69989831-c8db5c00-1544-11ea-93ff-b23102f35924.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69989860-d85aa500-1544-11ea-8316-f8ef2128f61b.png)

3. Sections with [preface] attribute shouldn't be numbered
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985675-ff60a900-153b-11ea-9e6a-c3b1facc676c.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985699-0daec500-153c-11ea-9269-f9d10a4d1a7c.png)

4. Title after preface has an extra "Part 1:", i.e. "Cereals and pulses — Specifications and test methods — Part 1: Rice (in English)"
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985775-2fa84780-153c-11ea-84ca-304623146f92.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985791-3767ec00-153c-11ea-8795-99d93b1e0067.png)

5. R is capital in the title "Normative references" in the original document (but probably shouldn't be...)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985852-5bc3c880-153c-11ea-8295-d78926a34dc0.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985875-654d3080-153c-11ea-84a4-3ca430531c94.png)

6. Footnote 1 is set before the comma in "ISO 16634:–1,", while it is set after the comma in the original document
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985915-801fa500-153c-11ea-880b-7c0b1c59651e.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985925-8a41a380-153c-11ea-88fe-a1eecc588865.png)

7. "ISO DATE:" is missing in the footnote 1 in the generated document
rendered:
![image](https://user-images.githubusercontent.com/55683568/69985994-ae04e980-153c-11ea-98c7-8c70fa714e8c.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69985983-a7767200-153c-11ea-8e33-49009b194b89.png)

8. Word "modified" is added in generated document in this sentence: "[SOURCE: ISO 7301:2011, 3.2, modified — The term “cargo rice” is shown as deprecated, and Note 1 to entry is not included here]"
rendered:
![image](https://user-images.githubusercontent.com/55683568/69986030-c543d700-153c-11ea-9313-b631476683db.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69986054-d391f300-153c-11ea-885a-7b0325069874.png)

9. Font of the notes should be different
rendered:
![image](https://user-images.githubusercontent.com/55683568/69986111-f2908500-153c-11ea-9651-56d378e6ce85.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69986093-ea384a00-153c-11ea-947b-c65986f72d02.png)

10. Missing line break after "<rice>" here: "<rice> organic and inorganic components other than whole or broken kernels"
rendered:
![image](https://user-images.githubusercontent.com/55683568/69986153-0f2cbd00-153d-11ea-9a55-a762b2f9d797.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69986137-076d1880-153d-11ea-8e7c-2ec9ab138061.png)

11. In Table 1, first two rows should be boldfaced, i.e. terms such as "in husked rice" should be boldfaced
rendered:
![image](https://user-images.githubusercontent.com/55683568/69986795-5f584f00-153e-11ea-83b1-64490e10feb9.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69986764-523b6000-153e-11ea-94e2-a325b5e8b331.png)

12. Entries are vertically centered in the Table 1 in the rendered document, while they are vertically aligned to the top in the original document (example above)

13. Equations should be vertically centered 
rendered:
![image](https://user-images.githubusercontent.com/55683568/69987071-f6250b80-153e-11ea-976d-4afd801f2e65.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69987103-050bbe00-153f-11ea-9432-05db7c4ed80a.png)

14. Footnote font should be different
rendered:
![image](https://user-images.githubusercontent.com/55683568/69987129-181e8e00-153f-11ea-82e6-b7583292f2cd.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69987163-28cf0400-153f-11ea-9166-e997f1b802f0.png)

15. Heading should be boldfaced in Table D.1 
rendered:
![image](https://user-images.githubusercontent.com/55683568/69987203-3f755b00-153f-11ea-9731-ae2b693a5639.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69987231-4ef4a400-153f-11ea-8f72-9d56442fdae7.png)

16. "EXAMPLE — Sample Code" is written in different font in the original document. I think this is properly rendered in generated document, but maybe it's worth noting this is also a difference
rendered:
![image](https://user-images.githubusercontent.com/55683568/69987262-659afb00-153f-11ea-9d5b-a47b3af22f16.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69987281-73508080-153f-11ea-9c03-068b9e65820a.png)

**Comment by opoudjis** [comment]
Responses.

1. The doc identifier is compiled from bits of the XML, and the (E) derives from the source language; we will mitigate that by providing the full identifer in XML in https://github.com/metanorma/metanorma-standoc/issues/162

2. Suppression of headings in the table of contents is actually idiosyncratic, which is why I have to turn <h2> into p.Annex2 in postporcessing. It's a nasty exception, and I dunno how flexible ToC generation is in xsl:fo, but the rule is to ignore anything but h1 and annex/appendix in appendixes.

3. The Patent Notice is something we should have gotten rid of and haven't. It's obsolete markup. The Patent Notice currently forces the exception to include section number 0.

4. Interpolating "part nnn" into titles is something Alexander has missed

5. Normalising case in titles is an easy miss as well, that's done in code.

6. Hm. footnote placement. No idea how that happened.

7. ISO DATE, that may well be a bug my side, can't tell right now. But it should not be present.

8. Interpolating "modified" is done in code with modifications to term definitions.

9. Font: don't know how that happened.

10. The para for termdomain is a gotcha, it's meant to be in the same para as what follows it.

11. That's about imposing th = bold throughout, applied to everything in thead.

12. Centering is also an easy miss.

13. Yes, equations are centered.

14.  Font: don't know how that happened.

15. Again, thead = bold.

16. Yes, sourcecode is always monospace.

**Comment by ronaldtse** [comment]
@anermina thanks for the review! I noticed that some screenshots have been mixed... I will label the pictures as DOC or PDF for clarity.

(Since @opoudjis posted his comments before me, noticed that the original listing of screenshots may be mis-labeled. See this post for the correct order.)

> * Header has extra "(E)"

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69985447-777a9f00-153b-11ea-8263-08605415a138.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985461-81040700-153b-11ea-8759-971b91a4d2f4.png)

@Intelligent2013 knows about this, @opoudjis will be providing the full document identifier in https://github.com/metanorma/metanorma-standoc/issues/162


> * In Table of Contents, there should be no Appendix 1 Sample code

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69989860-d85aa500-1544-11ea-8316-f8ef2128f61b.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69989831-c8db5c00-1544-11ea-93ff-b23102f35924.png)

I think "Appendix 1 Sample code" should show up. @opoudjis will check and clarify.

> * Sections with [preface] attribute shouldn't be numbered

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69985675-ff60a900-153b-11ea-9e6a-c3b1facc676c.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985699-0daec500-153c-11ea-9269-f9d10a4d1a7c.png)

The ISO preface clause should be numbered (with 0) IFF it has subsections.

> * Title after preface has an extra "Part 1:", i.e. "Cereals and pulses — Specifications and test methods — Part 1: Rice (in English)"

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69985775-2fa84780-153c-11ea-84ca-304623146f92.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985791-3767ec00-153c-11ea-8795-99d93b1e0067.png)

The PDF output should match the DOC output.

> * R is capital in the title "Normative references" in the original document (but probably shouldn't be...)

DOC:

>   ![image](https://user-images.githubusercontent.com/55683568/69985852-5bc3c880-153c-11ea-8295-d78926a34dc0.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985875-654d3080-153c-11ea-84a4-3ca430531c94.png)

@anermina is correct. The title should be in normal casing ("Normative References" => "Normative references").

> * Footnote 1 is set before the comma in "ISO 16634:–1,", while it is set after the comma in the original document

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69985915-801fa500-153c-11ea-880b-7c0b1c59651e.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985925-8a41a380-153c-11ea-88fe-a1eecc588865.png)

The DOC output is correct here.

> * "ISO DATE:" is missing in the footnote 1 in the generated document

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69985994-ae04e980-153c-11ea-98c7-8c70fa714e8c.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69985983-a7767200-153c-11ea-8e33-49009b194b89.png)

The DOC output is correct.

> * Word "modified" is added in generated document in this sentence: "[SOURCE: ISO 7301:2011, 3.2, modified — The term “cargo rice” is shown as deprecated, and Note 1 to entry is not included here]"

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69986030-c543d700-153c-11ea-9313-b631476683db.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69986054-d391f300-153c-11ea-885a-7b0325069874.png)

The DOC output is correct.

> * Font of the notes should be different
>   rendered:
>   ![image](https://user-images.githubusercontent.com/55683568/69986111-f2908500-153c-11ea-9651-56d378e6ce85.png)
>   original:
>   ![image](https://user-images.githubusercontent.com/55683568/69986093-ea384a00-153c-11ea-947b-c65986f72d02.png)

I don't see the differences?

> * Missing line break after "<rice>" here: "<rice> organic and inorganic components other than whole or broken kernels"

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69986153-0f2cbd00-153d-11ea-9a55-a762b2f9d797.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69986137-076d1880-153d-11ea-8e7c-2ec9ab138061.png)

DOC is correct. The "domain" is placed in the immediate front of the definition.

> * In Table 1, first two rows should be boldfaced, i.e. terms such as "in husked rice" should be boldfaced

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69986795-5f584f00-153e-11ea-83b1-64490e10feb9.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69986764-523b6000-153e-11ea-94e2-a325b5e8b331.png)

Here's the definitive image from the original ISO Rice document:
<img width="547" alt="Screen Shot 2019-12-03 at 10 52 53 AM" src="https://user-images.githubusercontent.com/11865/70016482-67a29f80-15bb-11ea-910a-de9e6d79674d.png">

The DOC version: should have the 2nd header row bolded, and the math unbolded. Missing "%" sign in the header row 1 column 2 as line 3. (ping @opoudjis )

The PDF version: mostly correct. Missing "%" sign in the header row 1 column 2 as line 3.


> * Entries are vertically centered in the Table 1 in the rendered document, while they are vertically aligned to the top in the original document (example above)

Notice in the first data row first column the source encoding is wrong -- it should have been:

```adoc
| Extraneous matter: ...
|
* organic
|...
|
* inorganic
|...
```

See the definitive image to compare.


> * Equations should be vertically centered

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69987071-f6250b80-153e-11ea-976d-4afd801f2e65.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69987103-050bbe00-153f-11ea-9432-05db7c4ed80a.png)

DOC is correct here. There should also be an indent for the definition list after "where".

The definitive image from the original ISO Rice:
<img width="552" alt="Screen Shot 2019-12-03 at 10 54 33 AM" src="https://user-images.githubusercontent.com/11865/70016561-a173a600-15bb-11ea-96cb-e46ee85ec02b.png">


> * Footnote font should be different
>   rendered:
>   ![image](https://user-images.githubusercontent.com/55683568/69987129-181e8e00-153f-11ea-82e6-b7583292f2cd.png)
>   original:
>   ![image](https://user-images.githubusercontent.com/55683568/69987163-28cf0400-153f-11ea-9166-e997f1b802f0.png)

I'm not sure if I see a difference...

> * Heading should be boldfaced in Table D.1

I'm replacing the images here:

Definitive:
<img width="555" alt="Screen Shot 2019-12-03 at 10 56 01 AM" src="https://user-images.githubusercontent.com/11865/70016643-d67ff880-15bb-11ea-8626-b971bb1ab70b.png">

DOC:
<img width="529" alt="Screen Shot 2019-12-03 at 10 55 31 AM" src="https://user-images.githubusercontent.com/11865/70016628-cec05400-15bb-11ea-830c-84788392c889.png">

PDF:
<img width="629" alt="Screen Shot 2019-12-03 at 10 56 21 AM" src="https://user-images.githubusercontent.com/11865/70016663-e1d32400-15bb-11ea-9cf7-e18ba6a275e1.png">

There are some issues in both outputs.

> * "EXAMPLE — Sample Code" is written in different font in the original document. I think this is properly rendered in generated document, but maybe it's worth noting this is also a difference

DOC:
>   ![image](https://user-images.githubusercontent.com/55683568/69987262-659afb00-153f-11ea-9d5b-a47b3af22f16.png)

PDF:
>   ![image](https://user-images.githubusercontent.com/55683568/69987281-73508080-153f-11ea-9c03-068b9e65820a.png)

DOC is correct.. The label ("EXAMPLE -- Sample Code") should always be in the body font.

**Comment by ronaldtse** [comment]
There is another issue with "title-less clauses".

In ISO Rice:
<img width="544" alt="Screen Shot 2019-12-03 at 11 00 17 AM" src="https://user-images.githubusercontent.com/11865/70016868-6e7de200-15bc-11ea-9f47-bd40daa9ec52.png">

In DOC:
<img width="618" alt="Screen Shot 2019-12-03 at 11 00 39 AM" src="https://user-images.githubusercontent.com/11865/70016884-7c336780-15bc-11ea-8ea4-4b4809df73aa.png">

In PDF:
<img width="620" alt="Screen Shot 2019-12-03 at 11 00 57 AM" src="https://user-images.githubusercontent.com/11865/70016898-85bccf80-15bc-11ea-970a-7ff182f08f8a.png">

DOC and PDF:
* Should not have a line break between clause number and content.
* All links to clauses (not figures or tables) should be hyperlinked in BLUE.
* Footnote should be "2)" not just "2".
* Notice in the tables, all headers should be "vertically and horizontally centered".

**Comment by ronaldtse** [comment]
@Intelligent2013 actually, instead of a visual diff with DOC output, let's directly align with the original ISO Rice document:
https://github.com/metanorma/mn-samples-iso/blob/master/reference-docs/iso-rice-sample.pdf

Will start a new issue for that.

**Comment by Intelligent2013** [comment]
@ronaldtse 

> - Header has extra "(E)"

No information how to obtain it.

In https://github.com/metanorma/mn-native-pdf/issues/32:
"In the meantime, just do without the (E)."


> - In Table of Contents, there should be no Appendix 1 Sample code

There isn't Appendix 1 in the original ISO Rice document. Last Annex D.
In iso-rice-en.xml, Appendix 1 in a subsection of last annex.
In the current version of XSLT, Appendix don't show in TOC. If you need to show Appendix as subsection of Annex, then inform me.


> - The ISO preface clause should be numbered (with 0) IFF it has subsections.

Fixed.


> - Title after preface has an extra "Part 1:", i.e. "Cereals and pulses — Specifications and test methods — Part 1: Rice (in English)"

Fixed.

> - R is capital in the title "Normative references" in the original document (but probably shouldn't be...)

In source xml: https://metanorma.github.io/mn-samples-iso/documents/iso-rice-en.xml:
`<title>Normative References</title>`


> - Footnote 1 is set before the comma in "ISO 16634:–1,", while it is set after the comma in the original document

Fixed.

> - "ISO DATE:" is missing in the footnote 1 in the generated document

'ISO DATE:' is a part of note element in XML:

`<note format="text/plain">
ISO DATE: Under preparation. (Stage at the time of publication ISO/DIS 16634)
</note>`

> - Word "modified" is added in generated document in this sentence: "[SOURCE: ISO 7301:2011, 3.2, modified — The term “cargo rice” is shown as deprecated, and Note 1 to entry is not included here]"


Fixed.


> - Font of the notes should be different

I don't see any differences.


> - Missing line break after "" here: " organic and inorganic components other than whole or broken kernels"


Fixed.

> - In Table 1, first two rows should be boldfaced, i.e. terms such as "in husked rice" should be boldfaced

No changes. PDF version is correct (there isn't % in xml data).

> - Equations should be vertically centered

Fixed.

> - There should also be an indent for the definition list after "where".

Fixed.


> - Footnote font should be different

I don't see a differences.


> - The label ("EXAMPLE -- Sample Code") should always be in the body font

Fixed.



> - Should not have a line break between clause number and content.
> - All links to clauses (not figures or tables) should be hyperlinked in BLUE.
> - Footnote should be "2)" not just "2".

Fixed.

> - Notice in the tables, all headers should be "vertically and horizontally centered".

Some cells has a left alignment in source xml:
```
<th rowspan="2" align="left">Defect</th>
<td align="left">in husked rice</td>
<td rowspan="2" align="left">Description</td>

```
If you need skip 'align' attribute from xml, please, inform me.

**Comment by ronaldtse** [comment]
@anermina is this done? If so please close it. Thanks!

**Comment by anermina** [comment]
Yes, this one should have been closed. Closing now.
