### ISSUE TITLE
ISO/IEC DIR 2 is crashing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#349]
Suspect the issue is that there is a nested table (`table//example//table`). The error message is:

````
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:inline" is not a valid child of "fo:block-container"! (See position 1194:346)
````

Presentation XML file attached:

[document.presentation.xml.zip](https://github.com/metanorma/mn-native-pdf/files/8323426/document.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
Fixed.
