### ISSUE TITLE
Align with original ISO Rice document and optional cover page styles

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#35]
@Intelligent2013 this issue is to visually align 100% (if possible) with the original ISO Rice document:

https://github.com/metanorma/mn-samples-iso/blob/master/reference-docs/iso-rice-sample.pdf

Notice that the cover page is different. This is the cover page for "Published" documents. The Word DOC version cover page is for "Unpublished" documents. We will need to allow generating both types of cover pages.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/issues/34#issuecomment-560982214_

**Comment by Intelligent2013** [comment]
@ronaldtse Unfortunately, I can't open PDF locally:
![image](https://user-images.githubusercontent.com/5559926/70238835-29ec7500-177b-11ea-9952-325b43721ee9.png)

Looks like file is corrupted. Could you attach it here, please?

**Comment by ronaldtse** [comment]
I edited the file using Preview, maybe that's the problem.

The original file is this: https://github.com/metanorma/mn-samples-iso/blob/master/reference-docs/model_document-rice_model.pdf

The file I uploaded was edited from the original by removing the commenting pages. Can you do that and upload the new "un-corrupt" file? Thanks.

**Comment by Intelligent2013** [comment]
Thank you. I've tried update, but haven't access for mn-samples-iso repository.
So attach here:
[iso-rice-sample.pdf](https://github.com/metanorma/mn-native-pdf/files/3927463/iso-rice-sample.pdf)

**Comment by ronaldtse** [comment]
@Intelligent2013 you now have access!

**Comment by Intelligent2013** [comment]
@ronaldtse Something wrong...
`remote: Permission to metanorma/mn-samples-iso.git denied to Intelligent2013.                                                               fatal: unable to access 'https://github.com/metanorma/mn-samples-iso/': The requested URL returned error: 403`

**Comment by ronaldtse** [comment]
Sorry maybe a mistake, can you try again?

**Comment by Intelligent2013** [comment]
PDF updated successfully. Thanks.

**Comment by Intelligent2013** [comment]
> Notice that the cover page is different. This is the cover page for "Published" documents. The Word DOC version cover page is for "Unpublished" documents. We will need to allow generating both types of cover pages.

Is there some tag in xml to determine 'Published' or 'Unpublished' document?

**Comment by ronaldtse** [comment]
@Intelligent2013 yes, in ISO documents, it has `//bibdata/status/`:

```xml
  <status>
    <stage>30</stage>
    <substage>92</substage>
  </status>
```

The `<stage>` and `<substage>` values are well defined, as the International Harmonized Stage Codes (https://www.iso.org/stage-codes.html):

* stage `60` means published, everything before is a Draft (`90` means withdrawn, but the document doesn't change anymore)

**Comment by ronaldtse** [comment]
For ITU documents, 

The `//bibdata/status/`:
```xml
  <status>
    <stage>in-force</stage>
  </status>
```

See https://www.metanorma.com/author/itu/authoring/

<img width="790" alt="Screen Shot 2019-12-06 at 10 14 36 PM" src="https://user-images.githubusercontent.com/11865/70329213-cc891e80-1875-11ea-8483-31796eaf7eed.png">

**Comment by Intelligent2013** [comment]
@ronaldtse 
I've updated mn-iso.xsl for align with original ISO Rice document. In branch  alex-xslt-update.
Align with PDF document is complicated than DOC, because in PDF there aren't any properties (margins, for example), and it's necessary to make a few steps - change xsl-fo, create pdf, compare two docs in Adobe Reader via ctrl-F6, then change xsl-fo, create pdf, compare, etc.

**Comment by ronaldtse** [comment]
@Intelligent2013 Fully understand and appreciate your effort in aligning the PDFs!

**Comment by Intelligent2013** [comment]
Fixed. Comments please see in https://github.com/metanorma/mn-native-pdf/issues/34.
