### ISSUE TITLE
Solidus in `ISO/IEC` issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#350]
From https://github.com/metanorma/metanorma-iso/issues/604:

> This seems to be a PDF only issue (ping @Intelligent2013 ):
<img width="1158" alt="Screenshot 2022-04-02 at 1 12 32 PM" src="https://user-images.githubusercontent.com/11865/161367480-df3b13c8-891d-4f66-a199-5c7784cd5f03.png">
<img width="169" alt="Screenshot 2022-04-02 at 1 12 47 PM" src="https://user-images.githubusercontent.com/11865/161367488-66e44e16-e326-47ed-a1c9-b6e50795a9d5.png">

Source xml:
```
The meaning of this value is defined in ISO/IEC 8824-1, and is described in ISO 10303-1.
```

The reason: Apache FOP split the string by `/`.
To do: via xslt on-fly - replace"
```
(capital letters){2,}/{(capital letters){2,}(space)(digit)+(:digit+)*
```
by
```
<fo:inline keep-together.within-line="always"(capital letters){2,}/{(capital letters){2,}(non-breakspace)(digit)+(:digit+)*</fo:inline>
```

**Comment by ronaldtse** [comment]
@Intelligent2013 is there a generic solution for the content tree? There are issues with empty spaces inserted in underscores and hyphens as well.

**Comment by ronaldtse** [comment]
If we use a keep together, remember the pattern "ISO nnn-n" also applies. It is strange to only keep together "ISO/IEC nnn-n" but not "ISO nnn-n". 

That's why this solution is too specific for this problem.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is there a generic solution for the content tree? There are issues with empty spaces inserted in underscores and hyphens as well.

@ronaldtse there isn't generic solution, unfortunately. Let's assumed that we have 10 columns table and in one row in each cell there are text `aaaaaaa_bbbbbb_cccccccc`. If we don't put 'zero-width space' after each underscore, then each such string will overflow cell's border.
I will try to remove zero-width spaces in intermediate FOP xml (after text position determined) before PDF generation.

**Comment by Intelligent2013** [comment]
> If we use a keep together, remember the pattern "ISO nnn-n" also applies. It is strange to only keep together "ISO/IEC nnn-n" but not "ISO nnn-n".
> 
> That's why this solution is too specific for this problem.

@ronaldtse yes, sure, the common solution will be applied.

**Comment by ronaldtse** [comment]
@Intelligent2013 is it possible to separate the presentation text and the content text embedded in the content tree? Or, is there a way to force break strings?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is it possible to separate the presentation text and the content text embedded in the content tree? 

No, there isn't such possibility.

I'm sure that the issue in the using of old font 'Cambria'.
I've just compared my locally generated PDF with PDF on gh-pages (https://github.com/metanorma/iso-10303-detached-docs/).

PDF from gh-pages - `element_representation` consists from two parts in the PDF content tree:

![image](https://user-images.githubusercontent.com/5559926/161389465-6f4b29fe-2c13-4a68-be6e-dc5038dfda77.png)

And if I copy-paste the text from PDF to text editor:
![image](https://user-images.githubusercontent.com/5559926/161389527-3b8e5b5e-b3a5-4da7-b46d-ff46c4e76372.png)

My locally generated PDF - `element_representation` represented as one thing:

![image](https://user-images.githubusercontent.com/5559926/161389673-29ec2402-4441-4816-9762-fdd998fa4f34.png)

![image](https://user-images.githubusercontent.com/5559926/161389685-febe7578-23dc-48e1-8eb5-11d0cb04bda6.png)

In the section 'Normative References' you can see 'hash' characters (in PDF generated on gh-pages):
![image](https://user-images.githubusercontent.com/5559926/161389747-ca5a99e8-482f-493e-858d-9a8e972a1619.png)

It means that used font doesn't contain the character 'thin space' and Apache FOP replaces it by hash.
Regarding zero-width space, looks like the font doesn't contain it also, and Apache FOP process it as text separator in the content tree.


Also I've checked Apache FOP Intermediate Format. There aren't zero-width space already there (in my environment):
```xml
<text x="0" y="9652" foi:struct-ref="5bf">ip1</text>
</g>
<g transform="translate(69679,12000)">
<font weight="400"/>
<id name="_22a0b4c5-47a7-9f34-d9fb-f864fcd19604"/>
<text x="0" y="9652" dp="2 Z2 -99 Z3 -209 0" foi:struct-ref="5c0">every </text>
<font weight="700"/>
<text x="28435" y="9652" dp="12 Z34 -154 Z11 -154 0" foi:struct-ref="5c1">element_representation</text>
<font weight="400"/>
<text x="149644" y="9652" foi:struct-ref="5c2"> in the </text>
<font weight="700"/>
<text x="181225" y="9652" dp="1 Z2 -66 0" foi:struct-ref="5c3">cells</text>
<font weight="400"/>
<text x="203951" y="9652" dp="15 Z58 -88 0" foi:struct-ref="5c4"> shall belong to the </text>
<font weight="700"/>
<text x="294514" y="9652" dp="1 Z2 -209 0" foi:struct-ref="5c5">explicit_model</text>
<font weight="400"/>
```


> Or, is there a way to force break strings?

In xslt we can put the character `&#x2028;`. It works identical to `<br/>`.

**Comment by Intelligent2013** [comment]
My comment above doesn't relate to the source issue (ISO/IEC).

**Comment by Intelligent2013** [comment]
Issue with `ISO/IEC` fixed:
![image](https://user-images.githubusercontent.com/5559926/161395757-290155ac-e492-41ec-a2c1-6d617f7f5dc0.png)

Pattern is: `[A-Z]{2,}(/[A-Z]{2,})* \d+(-\d+)*(:\d{4})?`
