### ISSUE TITLE
Supporting additional fonts per-document

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#351]
Source: https://github.com/metanorma/metanorma-standoc/issues/618

Add additional fonts from:
```xml
<presentation-metadata>
	<name>fonts</name>
	<value>Euphemia</value>
</presentation-metadata>
```
to xslt into `fo:root` tag on-fly.

**Comment by ronaldtse** [comment]
@Intelligent2013 we will likely also add in the font names for the fonts to use in the flavor as default, e.g. Cambria. What is the best way to map font styles to text here in the XML?

**Comment by Intelligent2013** [comment]
Done.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we will likely also add in the font names for the fonts to use in the flavor as default, e.g. Cambria. What is the best way to map font styles to text here in the XML?

@ronaldtse for instance:
```xml
<presentation-metadata>
	<name>default_fonts</name>
	<value>Cambria</value>
</presentation-metadata>
```
I have to update xslt for reading these values.
