### ISSUE TITLE
ITU: Cover Page document identifier

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#36]
ITU issues with the Cover Page:

Wrong:
<img width="221" alt="Screen Shot 2019-12-02 at 3 19 47 PM" src="https://user-images.githubusercontent.com/11865/69938226-b26adb80-1517-11ea-9500-c58322621607.png">
<img width="196" alt="Screen Shot 2019-12-02 at 3 19 50 PM" src="https://user-images.githubusercontent.com/11865/69938227-b26adb80-1517-11ea-810d-af337722f453.png">
<img width="288" alt="Screen Shot 2019-12-02 at 3 19 59 PM" src="https://user-images.githubusercontent.com/11865/69938238-b8f95300-1517-11ea-9b29-f4c3b1002d2e.png">

The first two should have been "Recommendation"

The last one should have been:
<img width="336" alt="Screen Shot 2019-12-02 at 3 20 10 PM" src="https://user-images.githubusercontent.com/11865/69938256-c3b3e800-1517-11ea-9c64-7d8c0ea85f8b.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/pull/27#issuecomment-560267578_

**Comment by Intelligent2013** [comment]
@ronaldtse 
I need an additional information - how to determine type of document - 'article' or 'recommendation'?
I thought that it determines in bibdata/doctype:
```
<bibdata>
. . .
  <ext>
    <doctype>article</doctype>
    <editorialgroup>
      <bureau>T</bureau>
    </editorialgroup>
    <ip-notice-received>false</ip-notice-received>
    <structuredidentifier>
      <bureau>T</bureau>
      <docnumber>J.1108</docnumber>
    </structuredidentifier>
  </ext>
</bibdata>
```
but looks like there is some other tag...

In xmls:
https://metanorma.github.io/mn-samples-itu/documents/T-REC-J.1108-201901-P.MSW-E.xml
https://metanorma.github.io/mn-samples-itu/documents/T-REC-H.782-201811-I.MSW-E.xml
doctype=article

**Comment by ronaldtse** [comment]
@Intelligent2013 I think all of these should be "recommendation". "article" is probably wrong. Can you confirm @opoudjis ?

**Comment by opoudjis** [comment]
Yes, it's a bug. Fixed.

**Comment by ronaldtse** [comment]
Confirmed this is fixed. Closing.
