### ISSUE TITLE
Open PR for metanorma-* processors on XSLT update instead of commit to main

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-native-pdf#367]
@opoudjis proposed to not trigger CI for `metanorma-*` on XSLT:

> ... the xslts being added to main only get tested in GHA by my rspec about whether a PDF compiles at all. I have occasionally caught an issue that way, but I've done so on local pulls, rather than in GHA, and I always do local pulls before publishing.

@ronaldtse @Intelligent2013 how do you think about the suggestion?

**Comment by Intelligent2013** [comment]
@CAMOBAP currently, the repositories metanorma-* contain latest xslt after each update in the repository 'mn-native-pdf'. And user can execute `bundle update` to obtain latest xslt to produce pdf. He shouldn't wait next metanorma-* gem release. Right?
The repository 'mn-native-pdf' in the folder xslt_src doesn't contain 'ready to use' xslt. They should be 'merged' with common.xsl by xalan xslt processor. I don't understand - who and when will be run this process? May be I didn't understand the suggestion...

**Comment by ronaldtse** [comment]
@opoudjis I don't understand what the issue nor the suggestion is. Is the asks to have the PDF XSLTs to get tested in GHA before merging to `main` branch?

> currently, the repositories metanorma-* contain latest xslt after each update in the repository 'mn-native-pdf'. And user can execute bundle update to obtain latest xslt to produce pdf. He shouldn't wait next metanorma-* gem release. Right?

Yes that is the intent.

@CAMOBAP We can adopt a release system in mn-native-pdf so that only particular released XSLTs get sent to metanorma-* as PRs.

**Comment by CAMOBAP** [comment]
> @CAMOBAP We can adopt a release system in mn-native-pdf so that only particular released XSLTs get sent to metanorma-* as PRs.

I think so, we may do some tags for the repo or special keywords in commit message as a signal to push xslts to our metanorma-* processors

@opoudjis @ronaldtse @Intelligent2013 how do you think about this?

**Comment by ronaldtse** [comment]
On the other hand, we can have `main` trigger send PRs to metanorma-*, and in mn-native-pdf, @Intelligent2013 will use PR for GHA testing.

**Comment by CAMOBAP** [comment]
@ronaldtse it's not a problem to implement but as far as I understood @opoudjis his original intention was a bit different

I will agree with any final decision

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP , we will need @opoudjis to clarify what he actually meant.

**Comment by ronaldtse** [comment]
@opoudjis says:
> Anything that reduces the load on GHA
> I am not at all convinced that having XSLT pushes run on GHA is useful
> I end up running them anyway

The number of concurrent runners is limited per GitHub organization and we cannot change it.

We can reduce GHA load by limiting the scope of tests within mn-native-pdf:

1. Updates to PDF XSLTs are done within mn-native-pdf via PRs and 1 single merge to `main`.
2. Changes on `main` of particular PDF XSLTs will trigger the appropriate metanorma-* repository. e.g. change to "shared/core" XSLT will trigger all repos, but change to the XSLT of one flavor will only trigger a single metanorma-* flavor. (This may require restructuring of the repository, e.g. one folder per flavor, but it is up to @CAMOBAP )

@CAMOBAP what do you think?

**Comment by CAMOBAP** [comment]
1. In the case of several commits I think they all should go to a single PR, correct me if I'm wrong
2. In fact we have it because if there are no changes commit will no happens, example: https://github.com/metanorma/mn-native-pdf/runs/6758709145?check_suite_focus=true#step:7:122

Thanks for the answers, now I ready to start

**Comment by ronaldtse** [comment]
1. Agree. On merge from PR to main in mn-native-pdf, the mn-native-pdf repo will create a PR at the appropriate metanorma-* flavor repo, and re-use that PR until it is merged.

Thanks @CAMOBAP !

**Comment by Intelligent2013** [comment]
> merge from PR to main in mn-native-pdf

question: _who_ and _when_ should merge PR to main?

**Comment by ronaldtse** [comment]
@Intelligent2013 I'm assuming that you will develop in PRs in this repo, and merge them to main when you consider the changes releasable.

**Comment by CAMOBAP** [comment]
@ronaldtse @Intelligent2013 @opoudjis finally workflow is fixed, BTW we have the option to assign PRs to review. And we can configure it differently for different repos.

Any suggestions on who to add to reviewers?

**Comment by ronaldtse** [comment]
@CAMOBAP Can you set myself and @opoudjis for now? In any case, it will be good to have a documented way to do so. Thanks!

**Comment by opoudjis** [comment]
Oh God.

I was hoping for automatic merges: it's not like I actually review them at all.
