### ISSUE TITLE
Update xslt for Noto fonts

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#368]
Continue from https://github.com/metanorma/mn2pdf/issues/119.

To do:
### 1. Add Noto Sans/Serif font
Change from:
```xml
<fo:root ... font-family="Cambria, Times New Roman, Cambria Math, Source Han Sans"...
```
to
```xml
<fo:root ... font-family="Cambria, Times New Roman, Cambria Math, Noto Sans, Source Han Sans"...
```

And similar for 'Noto Sans Mono'.

### 2. Replace 'Source Han Sans' to 'Noto Sans/Serif lang', where 'lang' is HK, JP, KR, SC or TC.

From https://github.com/metanorma/mn2pdf/issues/119#issuecomment-1115952877:
> The different language variations is due to these regions use slightly different renditions of the same characters ... Users should be able to choose among them.

I propose to use:
```
:presentation-metadata-extended-cjk-font-lang: JP
```

In this case `font-family` will be:
```
<fo:root ... font-family="Cambria, Times New Roman, Cambria Math, Noto Sans, Noto Sans JP"...
```

And similar for 'Noto Sans Mono CJK lang' for monospaced fonts.

**Comment by ronaldtse** [comment]
Regarding the Metanorma option:
```
:presentation-metadata-extended-cjk-font-lang: JP
```

I think in the future we may need to support other language font packs, e.g. Devanagari. Perhaps we can generalize this to "main language"? And we need a way to indicate that what characters are to be represented by what fonts?

**Comment by Intelligent2013** [comment]
Strange behavior found:
- case1 - `embedding-mode="full"` (currently, set for all .otf fonts for https://github.com/metanorma/mn2pdf/issues/90#issuecomment-905692089) :
```xml
<font embed-url="file:/C:/Users/IntlUser/.metanorma/fonts/NotoSerifKR-Regular.otf" embedding-mode="full" kerning="yes" mn_default="true">
	<font-triplet name="Noto Serif KR" style="normal" weight="normal"/>
</font>
```
![image](https://user-images.githubusercontent.com/5559926/172155524-ae1f4b59-be48-400c-8de5-e9b9a2ef1df1.png)


- case2 - without embedding-mode="full"

![image](https://user-images.githubusercontent.com/5559926/172155358-835500ee-5496-44c1-8591-11e7f84d888c.png)


So, for Noto fonts `embedding-mode="full"` should be omitted.

**Comment by ronaldtse** [comment]
@Intelligent2013 I suppose that embedded "full" will be too large and probably triggers some sort of overflow?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 I suppose that embedded "full" will be too large and probably triggers some sort of overflow?

@ronaldtse for Noto fonts `embedding-mode="full"` should be removed, so no change of file size expected.

**Comment by Intelligent2013** [comment]
@ronaldtse some xslt (for instance, Ribose, CSD) use 'Source Sans Pro' as main font. Would you like to change it to 'Noto Sans' also?

**Comment by Intelligent2013** [comment]
@ronaldtse and regarding font 'Source Code Pro'. It's using for source code in CSA, CSD and Ribose xslt. It should be change to Noto Mono font?

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/metanorma-cc/issues/142:

> https://github.com/metanorma/metanorma-cc/runs/7300570397?check_suite_focus=true

> Looks like Source Sans Pro is still needed here? Can we change all to Noto?

Issue fixed.

So, my questions:
> CSD xslt uses 'Source Sans Pro' as main font. Would you like to change it to 'Noto Sans' also?

> and regarding font 'Source Code Pro'. It's using for source code in CSA, CSD and Ribose xslt. It should be change to 'Noto Sans Mono' font?

resolved - `Source Sans Pro` replaced to `Noto Sans` in CC, `Source Code Pro'` replaced to `Noto Sans Mono` in all flavors.

**Comment by ronaldtse** [comment]
@Intelligent2013 yes, correct. Replace all Source Sans with their Noto equivalents.
