### ISSUE TITLE
ITU: Figures/Tables with attribute `"unnumbered"`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#37]
Figures (and tables) marked to be "unnumbered" should not be numbered. In addition, if you see `itu-Y.3507-201812.pdf`, the number "Figure B.1" is reused multiple times (which it shouldn't).

<img width="670" alt="Screen Shot 2019-12-02 at 3 13 11 PM" src="https://user-images.githubusercontent.com/11865/69937778-961a6f00-1516-11ea-9eec-cf057f3fb517.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/11865/69937902-dda0fb00-1516-11ea-8179-5b56992b31bb.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/pull/27#issuecomment-560265916_

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/5559926/70462392-cf7d4c80-1acb-11ea-97f1-2b2a10762081.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
