### ISSUE TITLE
ITU: Cover page content should always be on same page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#38]
Cover page content should not be extended across pages:

<img width="536" alt="Screen Shot 2019-12-02 at 3 14 04 PM" src="https://user-images.githubusercontent.com/11865/69937834-b6e2c480-1516-11ea-9cc3-84bdc360d96c.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/pull/27#issuecomment-560265916_

**Comment by Intelligent2013** [comment]
Fixed. Logo placed now in fixed position on cover page.
![image](https://user-images.githubusercontent.com/5559926/70393482-6af2bc80-19fb-11ea-9e89-c8b2f0d5b326.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
