### ISSUE TITLE
Improve speed for larger documents

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#393]
As titled.
Especially, for  BIPM brochure.

**Comment by Intelligent2013** [comment]
Processing time for BIPM brochure generation (3 PDF files):

| Step  | Processing time (sec)
| ------------- | ------------- 
|**Set widths for tables** |
Generation of XSL-FO with information about the table's widths | 255
Generate FOP IF | 51
Apply XSLT (Create Table IF) | 22
|  | <div align="right">**328**</div>
Generate main XSL-FO | <div align="right">**243**</div>
| **Second pass, Update Indexes** |
Generate FOP IF | 32
Apply XSLT (Create Index file) | 23
Generate XSL-FO (second pass) | 164
| |<div align="right">**219**</div>
|**Adding Math as text**|
| Generate FOP IF | 26
| Updating IF (adding hidden math)| 66
| |<div align="right">**92**</div>
|PDF generation | <div align="right">**85**</div>
| **Generate PDF in French**|
|**Set widths for tables** | <div align="right">**0 ?**</div>
Generate main XSL-FO | <div align="right">**87**</div>
| **Second pass, Update Indexes** | <div align="right">**0 ?**</div>
|**Adding Math as text**|
| Generate FOP IF | 12
| Updating IF (adding hidden math)| 22
| |<div align="right">**34**</div>
|PDF generation | <div align="right">**32**</div>
| **Generate PDF in English**|
|**Set widths for tables** | <div align="right">**0 ?**</div>
Generate main XSL-FO | <div align="right">**82**</div>
| **Second pass, Update Indexes** | <div align="right">**0 ?**</div>
|**Adding Math as text**|
| Generate FOP IF | 12
| Updating IF (adding hidden math)| 21
| |<div align="right">**33**</div>
|PDF generation | <div align="right">**30**</div>
|Total: | <div align="right">**1265**</br>(>20min)</div>


To do:
- check step for French and English PDF with '0 sec'.
- the step 'Generation of XSL-FO with information about the table's widths' should be optimized - generate tables only, no need to transform whole document (skip clauses without tables).
- generate PDF in French and English in the parallel mode

**Comment by Intelligent2013** [comment]
> he step 'Generation of XSL-FO with information about the table's widths' should be optimized - generate tables only, no need to transform whole document (skip clauses without tables).

Done. The processing time decreased from 255sec to 55sec.

**Comment by Intelligent2013** [comment]
Redundant IF xml generation for line numbers found in the workflow (the debug file `....if.linenumbers.xml`). It should be omitted when line numbers feature is turned off.

**Comment by Intelligent2013** [comment]
The extension function `str:split` (`xmlns:str="http://exslt.org/strings"`) is very expensive, and should be replaced by regex.

**Comment by Intelligent2013** [comment]
`str:split` replaced by java regex. The time of processing IF for tables widths calculation decreased. For instance, for the document 'ISO 10303-108': before update - 130 seconds, after update - 42 seconds.

**Comment by Intelligent2013** [comment]
XSLT `table_if.xsl` for IF processing optimized - processing time decreased from 42 to 19 seconds.

**Comment by Intelligent2013** [comment]
Current status:
> - check step for French and English PDF with '0 sec'.

it's ok. Currently, the French and English PDF generation step is using table width calculation and indexes analyse result from main step.

> - the step 'Generation of XSL-FO with information about the table's widths' should be optimized - generate tables only, no need to transform whole document (skip clauses without tables).

The total PDF (collection, French and English) generation time decreased from 1265sec to 1070sec.

> - generate PDF in French and English in the parallel mode

next task. From https://xmlgraphics.apache.org/fop/2.7/embedding.html#multithreading:
> Apache FOP may currently not be completely thread safe. The code has not been fully tested for multi-threading issues, yet. If you encounter any suspicious behaviour, please notify us.

**Comment by Intelligent2013** [comment]
To do:
- try to optimize BIPM xslt.

**Comment by Intelligent2013** [comment]
> - generate PDF in French and English in the parallel mode

PDF in French and English can't be processed in the parallel mode, because:
- in English version - page numbers following the bilingual version, therefore we should generate French version first to know total pages
- XSLT calculates table's width in Bilingual version, and then use them in  French and English version. Otherwise, XSLT should calculate table's width triple - for Bilingual, English and French versions.

So 
> - try to optimize BIPM xslt.

is most important task.

**Comment by Intelligent2013** [comment]
mn2pdf (https://github.com/metanorma/mn2pdf/releases/tag/v1.55) and BIPM xslt updated.
Processing time decreased from 1265 to 625 sec.
Another XSLT updated earlier in https://github.com/metanorma/iso-10303-2/issues/103.

**Comment by opoudjis** [comment]
@Intelligent2013 You are a better dev than me, which is why your optimisations, when you do them, are linear time, and mine are exponential :)

The major timesink for me has always been lookups in the entire document by ID, `//*[@id = 'x']`. Caching those lookups in an array so they are only looked up once is what reduces tasks that take 30 mins to a few seconds. But clearly, you aren't doing anything that silly.

Although I have just introduced exactly that kind of lookup in the XSLT troubleshooting I'm doing in my day job :)
