### ISSUE TITLE
ISO: Non-Latin characters showing up as "#"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#4]
From @Intelligent2013 :

> korean, hebrew characters show as '#'. The font 'Cambria' doesn't contains glyphs for such characters. In Word we see these characters correctly because Word substitutes another font (Malgun Gothic as I understood) to display them.

**Comment by ronaldtse** [comment]
@Intelligent2013 is this fixed? Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse yesterday I've found the necessary fonts in Ububtu to display the glyphs, but can't find them in ubuntu github environment. I see that you've find the solution. Thank you!
Yes, this issue fixed.

**Comment by ronaldtse** [comment]
Excellent, thanks! 👍
