### ISSUE TITLE
No updates for xslt in private repo 'BSI' and 'NIST'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#408]
No updates received for XSLT in the private repositories NIST or BSI.

An year ago updating for BS I(mn-native-pdf-bsi) and NIST (mn-native-pdf-nist) was added here:
https://github.com/metanorma/mn-native-pdf/commit/71e71c6c2e5880deebb6ee17d0ba36847d5f30f3

But it's missing now in ubuntu.yml.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 for raising this issue. @CAMOBAP can you please help? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse we simply don't have this in the list I will add it

**Comment by ronaldtse** [comment]
Thanks!

**Comment by CAMOBAP** [comment]
Done
