### ISSUE TITLE
ITU: G.191 definition list alignment text overlap

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#42]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/11865/70413258-eef78380-1a91-11ea-8392-09276d8b07cc.png">

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/5559926/70452472-355fd900-1ab8-11ea-8ab2-def029f61799.png)
