### ISSUE TITLE
IEC: 'domain' field in DOC

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#44]
In xml https://metanorma.github.io/mn-samples-iec/documents/iec-rice.xml there 'domain' field in 'waxy rice' term:

```
<term id="_waxy_rice">
	<preferred>waxy rice</preferred>
	<definition>
		<p id="_12793fe3-c974-41e6-9fac-90547eb61eaa">variety of rice whose kernels have a white and opaque appearance</p><p id="_8acd11e5-7b99-4a95-96cb-1217281640f7">organic and inorganic components other than whole or broken kernels</p>
	</definition>
	<admitted>EM</admitted>
	<domain>rice</domain>
	<termexample id="_f66f5418-2c4b-49fc-9e42-58311d910e4d">
		<p id="_3719a14c-9efe-40e6-9e17-f8ed8b093e4c">Foreign seeds, husks, bran, sand, dust.</p>
	</termexample>
</term>
```

But in doc (https://metanorma.github.io/mn-samples-iec/documents/iec-rice.doc) this field omitted:
![image](https://user-images.githubusercontent.com/5559926/70819539-8d178080-1de7-11ea-9685-c0f10246c9e4.png)

Should I put it in PDF or not?

**Comment by ronaldtse** [comment]
@Intelligent2013 that must be a bug because ISO and IEC share the same styles. Just render it like in ISO.
