### ISSUE TITLE
CalConnect: Implement CalConnect PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#45]
Available from https://github.com/metanorma/mn-samples-cc

**Comment by Intelligent2013** [comment]
@ronaldtse Please confirm that sample PDF https://metanorma.github.io/mn-samples-cc/documents/cc-18011.pdf is correct.
There aren't:
- page numbers
- headers/footers

**Comment by ronaldtse** [comment]
Strangely the Word version isn't shown here. Here it is. Can you help make this? Thanks!
[cc-18011.docx](https://github.com/metanorma/mn-native-pdf/files/4060404/cc-18011.docx)

**Comment by Intelligent2013** [comment]
@ronaldtse Do you need xslt for docx only, or for docx and pdf both?

**Comment by ronaldtse** [comment]
@Intelligent2013 just the DOCX, the old PDF was a temporary version.

**Comment by Intelligent2013** [comment]
I've added xslt for CalConnect into https://github.com/metanorma/mn-native-pdf/pull/73/ (ns-change branch)
