### ISSUE TITLE
Create CSA PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#46]
Sample PDF output:
[Information Security Management through Reflexive Security.pdf](https://github.com/metanorma/mn-native-pdf/files/3977293/Information.Security.Management.through.Reflexive.Security.pdf)
[Six Pillars of DevsecOps-Branded.pdf](https://github.com/metanorma/mn-native-pdf/files/3977294/Six.Pillars.of.DevsecOps-Branded.pdf)

The cover page image needs to be customizable.

**Comment by Intelligent2013** [comment]
@ronaldtse I've added csa.standard.core.xsl into the branch add-csa-xslt (PR https://github.com/metanorma/mn-native-pdf/pull/105)

The fonts AzoSans-Regular, -Light and -Bold, and OpenSans-Bold are using in the sources PDFs.
OpenSans-Bold is using for list item bullets. I think we can dismiss this font.
But from where we can download AzoSans-* fonts?

**Comment by ronaldtse** [comment]
> OpenSans-Bold is using for list item bullets. I think we can dismiss this font.

Great!

> But from where we can download AzoSans-* fonts?

I found it on couple places on GitHub, but not sure if that's the right way of doing things... Do you think if the user does not have this font, we provide degraded output and provide a warning? So the user has to install in system or inside `~/.metanorma/fonts` manually?

**Comment by Intelligent2013** [comment]
> Do you think if the user does not have this font, we provide degraded output and provide a warning?

mn2pdf will show warning about font replacement. I've prepared PDFs with AzoSans and SourceSansPro fonts:

AzoSans:
![image](https://user-images.githubusercontent.com/5559926/79001298-e35abd00-7b56-11ea-928c-c16e2005db5d.png)

SourceSansPro:
![image](https://user-images.githubusercontent.com/5559926/79001338-f5d4f680-7b56-11ea-9cf2-a7873f385b3a.png)


> So the user has to install in system or inside `~/.metanorma/fonts` manually?

Yes. And font file names should have determined names - AzoSans-Regular.ttf , AzoSans-Bold.ttf, AzoSans-BoldItalic.ttf , etc.

If we need to use AzoSans, then I should modify mn2pdf.

**Comment by ronaldtse** [comment]
I think we can use Source Sans as default, and if AzoSans exist in the system, we use AzoSans.

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated xslt for csa for using AzoSans font, and updated also mn2pdf for using SourceSansPro if AzoSans can't be found.
