### ISSUE TITLE
Globally replace `misc-container` with `metanorma-extension`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#482]
Source issue: https://github.com/metanorma/mnconvert/issues/301#issuecomment-1385388566

To do: globally replace `misc-container` with `metanorma-extension` in XSLT.

**Comment by opoudjis** [comment]
Sorry, decided to make it metanorma-extension, because I'm concerned extension will turn up elsewhere in the XML.

**Comment by Intelligent2013** [comment]
Done.
