### ISSUE TITLE
ISO: Table width auto layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#5]
From @Intelligent2013 
> in xml there isn't column width attribute for tables, so Apache FOP displays columns with equal width (table-layout="auto" feature isn't implemented by Apache FOP yet). I'll try to solve it by calculate proportional width by content for each column.

**Comment by Intelligent2013** [comment]
Hi @ronaldtse,
I've fixed this issue.

**Comment by ronaldtse** [comment]
It looks really good. Thanks @Intelligent2013 !

However, there seems to be one more column that is made extra? 

<img width="700" alt="Screen Shot 2019-11-23 at 10 49 03 PM" src="https://user-images.githubusercontent.com/11865/69480590-b0cc5400-0e43-11ea-915a-d8fc3b23e373.png">

**Comment by Intelligent2013** [comment]
In source xml there are 15 column for second table:
- 9 columns with data,
- 5 empty columns,
- and 1 last  column has a value 'G' in a line 'bgnpcgn-bul-2013': 

![image](https://user-images.githubusercontent.com/5559926/69483318-da32b300-0e36-11ea-9955-25622d70f2f1.png)

I have updated xslt for correct display very narrow column (in previous version 'G' was outside of table cell).

If you delete 'G' value, then table will show without extra column.

**Comment by ronaldtse** [comment]
I've deleted the `G` value in #10 . Closing. Thanks!
