### ISSUE TITLE
Fonts STIX2Math and Noto Math comparison

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#510]
Check STIX2Math and Noto Math glyphs for characters from https://github.com/plurimath/plurimath/blob/main/lib/plurimath/latex/constants.rb.

**Comment by Intelligent2013** [comment]
The results:
- missing glyphs in STIX2Math: 3
   - arrowbullet `&#x27a2;` (https://www.compart.com/en/unicode/U+27A2)
   - ballotx `&#x2717;` (https://www.compart.com/en/unicode/U+2717)
   - pencil, `&#x270e;` (https://www.compart.com/en/unicode/U+270e)
note: these glyphs are missing in the Noto Math font too.
- missing glyphs in Noto Math font: 387

[plurimath_latex_constants.pdf](https://github.com/metanorma/mn-native-pdf/files/10880341/plurimath_latex_constants.pdf)

**Comment by Intelligent2013** [comment]
XML+XSLT for testing with mn2pdf:
[STIX2Math_Noto_comparison.zip](https://github.com/metanorma/mn-native-pdf/files/10880432/STIX2Math_Noto_comparison.zip)

Fontist manifest:
```
STIX Two Math:
  Regular:
    full_name: STIX Two Math Regular
    paths:
    - C:/Users/TestUser/.fontist/fonts/STIXTwoMath-Regular.otf
Noto Sans Math:
  Regular:
    full_name: Noto Sans Math Regular
    paths:
    - C:/Users/TestUser/.metanorma/fonts/NotoSansMath-Regular.ttf 
```

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013. In the output we can clearly see many glyphs missing in Noto Math. e.g.

<img width="568" alt="Screenshot 2023-03-03 at 12 50 51 PM" src="https://user-images.githubusercontent.com/11865/222713414-fde6b879-efef-420b-8fed-f27afa1b2814.png">
<img width="565" alt="Screenshot 2023-03-03 at 12 51 00 PM" src="https://user-images.githubusercontent.com/11865/222713439-8f9e6d67-b035-4459-857e-721ba3b46939.png">
<img width="567" alt="Screenshot 2023-03-03 at 12 51 11 PM" src="https://user-images.githubusercontent.com/11865/222713474-ae7ac55c-8e52-4ce2-b240-9f0ed8b0b094.png">

etc.

I wonder if it's worth the effort to report them.

**Comment by Intelligent2013** [comment]
> missing glyphs in Noto Math font: 387

Correct value from https://github.com/metanorma/mn2pdf/issues/181:
missing glyphs in Noto Math font: 319
