### ISSUE TITLE
Creating a Math font comparison table / site

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#528]
There is some clear need for comparing math fonts on what glyphs are supported.

The typical math fonts are:
* Cambria Math
* STIX Two Math
* Noto Math
* Libertinus Math

When people / SDOs choose one of these fonts, they need to know what math symbols are available and which ones are not.

XML+XSLT for testing with mn2pdf:
[STIX2Math_Noto_comparison.zip](https://github.com/metanorma/mn-native-pdf/files/10880432/STIX2Math_Noto_comparison.zip)

Fontist manifest:
```
STIX Two Math:
  Regular:
    full_name: STIX Two Math Regular
    paths:
    - C:/Users/TestUser/.fontist/fonts/STIXTwoMath-Regular.otf
Noto Sans Math:
  Regular:
    full_name: Noto Sans Math Regular
    paths:
    - C:/Users/TestUser/.metanorma/fonts/NotoSansMath-Regular.ttf 
```

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/issues/510#issuecomment-1453222228_

**Comment by Intelligent2013** [comment]
The comparison result for four fonts: [2023-08-15_plurimath_latex_constants.pdf](https://github.com/metanorma/mn-native-pdf/files/12346755/2023-08-15_plurimath_latex_constants.pdf)
