### ISSUE TITLE
UN: Issues in XML

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#53]
In xml: https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_437E_Rec42.xml there are a few issues, which don't allow to correct display PDF via XSL-FO:
- hard-coded paragraph number '24.':
`... databases and the generation of appropriate indicators. 24. Other trade ...`

- Box 1 has a 'Source:' text with a font-size (9pt) a bit smaller then main font (10pt)
![image](https://user-images.githubusercontent.com/5559926/71575472-2213bc80-2afe-11ea-9e98-f7c568cf5187.png)

but in xml this text markup as 'p':
```
<p id="_49bc4c63-f463-487d-a8c4-5843f89f61e8">
Another difference between BPA and the other two methods (TRS and TCD/CPMM) is that BPA not only provides indicators, but also provides a ‘standard’ way of analyzing indicators, trade procedures, identifying bottlenecks and diagnosing trade barriers—while the other two methods mainly provide indicators.
</p>
<p id="_876caf99-ea5b-438e-b1d7-4a5de4a915c4">
Source: The box is derived from an ESCAP-ADB publication entitled
<em>
Towards a National Integrated and Sustainable Trade and Transport Facilitation Monitoring Mechanism: BPA+
</em>
(2014). Available as of 14 December 2016 at:
<link target="http://www.unescap.org/resources/towards-national-integrated-and-sustainable-trade-and-transport-facilitation-monitoring"/>
.
</p>
</admonition>
```

**Comment by ronaldtse** [comment]
@opoudjis can you take a look at this? Thanks.

**Comment by opoudjis** [comment]
"24" removed.

The distinct markup of source notes is implied in http://www.dgacm.org/editorialmanual/ed-guidelines/format/tables.htm (that the source paragraph is a type of note that appears after tables, and implicitly under other types of text).

This has not been implemented, as indeed much of the UN Editorial Manual has not been implemented. I am opening a ticket to do this, but any request to prioritise it will be rebuffed unless @ronaldtse explicitly requests it (and Ronald, don't.)

**Comment by opoudjis** [comment]
This is now addressed: Sources and Abbreviations are entered as:

````
[type="source"] (or: [type="abbreviation"]
NOTE
====
....
====
````

and end up in XML as:

````
<note type="source"> , <note type="abbreviation">
````

They are currently labelled as "Source", "Abbreviations"; this will eventually be taken care of in internationalisation, and thus presentation XML https://github.com/metanorma/metanorma-standoc/issues/285.

@anermina @manuel489: One of you please go through all UN documents, find any instances of Source or Abbreviation notes (they are supposed to occur only after tables), and change markup.

@Intelligent2013 You can proceed with update to XSLT, although Presentational XML will make such updates redundant anyway, since I'll end up giving you the labels in the XML you see.

**Comment by manuel489** [comment]
Ok, I'm updating the markup...

**Comment by manuel489** [comment]
PR added in https://github.com/metanorma/mn-samples-un/pull/49

I checked all the docs in mn-samples-un and didn't find any *abbreviation* instance, only sources.

**Comment by opoudjis** [comment]
All good.

**Comment by Intelligent2013** [comment]
@opoudjis @manuel489 Thank you!

XSLT updated:
![изображение](https://user-images.githubusercontent.com/5559926/86157026-77fa0900-bb0f-11ea-9567-54e1e8b50c65.png)
