### ISSUE TITLE
otimes symbol is shown too big

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-native-pdf#554]
*Issue found in https://github.com/metanorma/iso-iec-80000/pull/38*

Markup:
```adoc
Inline 1: stem:[a ox b]

Inline 2: stem:[a otimes b]
````

renders in PDF:
![issue-7-pdf](https://user-images.githubusercontent.com/33627611/233235527-28447dc8-f9d1-46ec-aa54-9277de5931e0.PNG)

HTML output:
![issue-7-html](https://user-images.githubusercontent.com/33627611/233235585-1eebc43d-a945-4c56-8f7e-d99a003a9755.PNG)

**Comment by Intelligent2013** [comment]
In the Cambria Math font there two glyphs:
![image](https://user-images.githubusercontent.com/5559926/233376005-9cbd196d-f676-4360-aa9b-14b2aee0698b.png)

Second char renders a bit smaller in the Word.

But in the PDF, second char renders much smaller:
![image](https://user-images.githubusercontent.com/5559926/233376399-32cb8f49-b718-4abe-8048-8fd7778702a7.png)

May be in jEuclid there is a special processing for it.

I'll set font-size to `55%` for 1st char.

**Comment by Intelligent2013** [comment]
Done.
