### ISSUE TITLE
Editor: do review for IEC document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#58]
Visual diff on the IEC document against the Word version in mn-samples-iec. We need to ensure the Word and PDF version matches.

**Comment by anermina** [comment]
Notes:
- In the Table of Contents, uppercase is used for Foreword and Introduction in DOC, unlike in PDF.
- Width of the Table 1 is bigger in PDF than in DOC.
- In PDF, description of footnote 1 contains "ISO DATE:", which is not contained in DOC.
- Source for 3.1 ([SOURCE: ISO 7301:2011, 3.1]) doesn't fit to the same page in DOC.
- In 3.5 (waxy rice), text starts with "<rice>" in PDF. This is not the case in DOC.
- In 3.5 (waxy rice), there is no empty line between EM and EXAMPLE in PDF, while it exists in DOC.
- In 3.14 (gelatinization time), there is no indentation before t_90 in PDF, while it exists in DOC.
- Note 1 in Table 1 refers to "table 1" in PDF, and to "Table 1" in DOC (lowercase/uppercase difference).
- After the equations (1) and (2), there is no line break in PDF after the word "where", while line break is added in DOC. 
- Spacing between the items explained after the word "where" (referring to the equations) is bigger in DOC than in PDF.

**Comment by manuel489** [comment]
_(Double-checking)_
This is a subtle detail. 
In the description list below, the `a` from the last item (red square) has a  different size in both versions. Then, I look into the adoc file and noticed that this element is typeset as a footnote instead of a description list like its previous partners.

PDF:
![diff1-pdf](https://user-images.githubusercontent.com/33627611/72953655-31d49880-3d6c-11ea-9d02-95153138e11e.JPG)

DOC:
![diff1-doc](https://user-images.githubusercontent.com/33627611/72953669-3a2cd380-3d6c-11ea-851a-4461b877f35c.JPG)

**Comment by Intelligent2013** [comment]
> Uppercase is used for Foreword and Introduction in DOC, unlike in PDF.

For PDF generation, I use <title> element in <foreword and <introduction elements:

`<foreword obligation="informative"><title>Foreword</title>`
`<introduction id="_introduction" obligation="informative"><title>Introduction</title>`

(source xml is here: https://metanorma.github.io/mn-samples-iec/documents/iec-rice.xml)

Please inform me if I should uppercase <title> content via XSLT.

> Width of the Table 1 is bigger in PDF than in DOC.

Source XML doesn't contain information about table width, therefore I use 100% width with proportional width (depends on text content) for columns.

> In PDF, description of footnote 1 contains "ISO DATE:", which is not contained in DOC.

Source XML has 'ISO DATE:' text:
`<note format="text/plain">ISO DATE: Under preparation. (Stage at the time of publication ISO/DIS 16634)</note>`

I can check one for existing of 'ISO DATE:' text and cut off it via xslt, but please inform me.

> In 3.5 (waxy rice), text starts with "" in PDF. This is not the case in DOC.

I think that PDF is ok.


> In 3.5 (waxy rice), there is no empty line between EM and EXAMPLE in PDF, while it exists in DOC.
PDF...

Fixed.

> In 3.14 (gelatinization time), there is no indentation before t_90 in PDF, while it exists in DOC.
PDF...

Fixed.

> Note 1 in Table 1 refers to "table 1" in PDF, and to "Table 1" in DOC (lowercase/uppercase difference).

Fixed.

> After the equations (1) and (2), there is no line break in PDF after the word "where", while line break is added in DOC.

Fixed.

> Spacing between the items explained after the word "where" (referring to the equations) is bigger in DOC than in PDF.

Fixed.


>In the description list below, the a from the last item (red square) has a different size in both versions.

Fixed.

**Comment by ronaldtse** [comment]
@anermina @manuel489 can you help verify the issues are now resolved? Thanks!

**Comment by ronaldtse** [comment]
Re-ping: @anermina @manuel489 can you help verify the issues are now resolved? Thanks!

**Comment by manuel489** [comment]
Hi @ronaldtse, I have verified the IEC outputs (DOC vs PDF). Most of the issues are fixed.

Only remain those issues where @Intelligent2013  is asking for a decision on what action to take. I mean this part:
![cap-alex](https://user-images.githubusercontent.com/33627611/79901168-698bc480-83dd-11ea-8838-b82207d06903.PNG)

And, also remain this following issue that I missed to report:

- Horizontal spacing between terms and descriptions differs. (It's bigger in PDF.)

For example:
````
stem:[w]:: is the mass fraction of grains with a particular defect in the test sample;
stem:[m_D]:: is the mass, in grams, of grains with that defect;
stem:[m_S]:: is the mass, in grams, of the test sample.
````

*DOC output:*
![cap-doc](https://user-images.githubusercontent.com/33627611/79901510-edde4780-83dd-11ea-90b1-6bdeec6f1a55.PNG)

*PDF output:*
![cap-pdf](https://user-images.githubusercontent.com/33627611/79901520-f040a180-83dd-11ea-960d-8be6f2fed61f.PNG)

Thanks!

**Comment by ronaldtse** [comment]
> For PDF generation, I use <title> element in <foreword and <introduction elements:
> <foreword obligation="informative"><title>Foreword</title>
> <introduction id="_introduction" obligation="informative"><title>Introduction</title>
> (source xml is here: https://metanorma.github.io/mn-samples-iec/documents/iec-rice.xml)
> Please inform me if I should uppercase <title> content via XSLT.

@Intelligent2013 : Yes please, let's uppercase the content via XSLT (seems to be a stylistic thing)

> Width of the Table 1 is bigger in PDF than in DOC.
> Source XML doesn't contain information about table width, therefore I use 100% width with proportional width (depends on text content) for columns.

@Intelligent2013 : The Source XML is only supposed to have semantic information and is difficult to embed width information (e.g. display width in HTML vs PDF is different). What's the best option here?

> Source XML has 'ISO DATE:' text:
> <note format="text/plain">ISO DATE: Under preparation. (Stage at the time of publication ISO/DIS 16634)</note>
> I can check one for existing of 'ISO DATE:' text and cut off it via xslt, but please inform me.

@manuel489 is this a bug in the source text? If not, it must be an error in XML that should be raised at metanorma-iec.

**Comment by manuel489** [comment]
> @manuel489 is this a bug in the source text? If not, it must be an error in XML that should be raised at metanorma-iec.

It's an error in XML source. I've opened a ticket to address it; https://github.com/metanorma/metanorma-iec/issues/54

**Comment by Intelligent2013** [comment]
@ronaldtse 

> Yes please, let's uppercase the content via XSLT (seems to be a stylistic thing)

Issue was fixed earlier already (https://metanorma.github.io/mn-samples-iec/documents/iec-rice.pdf):
![изображение](https://user-images.githubusercontent.com/5559926/81504172-6e62da80-92f0-11ea-85cb-02df54b012c2.png)

![изображение](https://user-images.githubusercontent.com/5559926/81504201-98b49800-92f0-11ea-8f56-64122d8c8826.png)


> The Source XML is only supposed to have semantic information and is difficult to embed width information (e.g. display width in HTML vs PDF is different). What's the best option here?

Without information about column width it's not possible in FOP. Another option is using commercial FO processor like RenderX.
`td` and `th` cell have `align` attribute yet. May be is it possible to add some non-HTML attribute, let's say `pwidth`, i.e. specific use only for PDF?

**Comment by ronaldtse** [comment]
It might be acceptable to have format-specific directives embedded in the XML, it is foreseeable that other formats may need such direction, too.

**Comment by manuel489** [comment]
Double-check was performed. Only one difference noticed: https://github.com/metanorma/mn-native-pdf/issues/310
Closing.
