### ISSUE TITLE
Editor: do UN document review

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#61]
Visual diff on the UN documents (Recommendation, Plenary) against the Word version in mn-samples-un. We need to ensure the Word and PDF version matches. (And the original PDFs provided)

**Comment by manuel489** [comment]
Hi @ronaldtse ,
These are my visual diff reviews for the UNECE files: "42" and "GE.18-02016(E)". Located in https://metanorma.github.io/mn-native-pdf/

**Review of UNECE "42" file:**
- The table from "Scope of monitoring" section is not numbered in the PDF version, but it is so in doc version.

- In PDF version, the example box (from section `D`, sub-section `2`) is numbered as `1`, but in doc version, it is numbered as `0`. Also, the Figure inside the box is not numbered in PDF file, but it is so in doc file.

- From section `D`, sub-section `3`, the paragraph numbering in doc version ("mn-samples-un") is ahead by one position respect PDF version ("mn-native-pdf"). (It seems like the number `24.` is duplicated in PDF version)

- In PDF version, the header title says: "Recommendation No. 42", while in doc version, it says: "UN/CEFACT Recommendation 42"

- PDF version includes a table of contents, doc version doesn't.

In addition, there are a couple of differences between the PDF file located in "mn-samples-un/reference-docs" and the PDF file from "mn-native-pdf". But I don't if that is relevant.


**Review of UNECE "GE.18-02016(E)":**

Here, I didn't find any noticeable difference. However, I did notice some differences between the PDF files from "mn-samples-un/reference-docs" and "mn-native-pdf". These are as follows: 

- The box example numbering starts from `0` in "mn-native-pdf" instead of `1` like in original PDF (located in "mn-samples-un/reference-docs")

- The annex sections are numbered with Roman numerals instead with letters like the in the original PDF.

- The sub-sections in the annexes aren't numbered in the original PDF, but they are so in "mn-native-pdf" version.

Again, I don't know if this is relevant but I point it anyway.

**Comment by Intelligent2013** [comment]
Hi @ronaldtse, @manuel489,
I'm not assignee for this issue, but would like to leave a comment.

Regarding https://github.com/metanorma/mn-native-pdf/issues/51, UN Recommendation template was developed for source **PDF**: https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_437E_Rec42.pdf

UN Plenary template was developed for **DOC**: https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_C_CEFACT_2018_6E.doc

I.e. these files should be compared:
https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_437E_Rec42.pdf (original **PDF**)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_437E_Rec42.pdf (resulted PDF)

and

https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_C_CEFACT_2018_6E.doc (original **DOC**)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_C_CEFACT_2018_6E.pdf (resulted PDF).
@manuel489 as I understood, you've compared them yet I didn't find differences.

**Comment by anermina** [comment]
Comparison of https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_437E_Rec42.pdf (original PDF)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_437E_Rec42.pdf (resulted PDF)
----------------------------
- One paragraph and a signature are missing in Foreword. Text which should be below the signature should also be horizontally centered.
Original:
![image](https://user-images.githubusercontent.com/55683568/72938300-07361000-3d6b-11ea-819e-5810cd0c727d.png)
Resulted:
![image](https://user-images.githubusercontent.com/55683568/72938283-feddd500-3d6a-11ea-9349-a749c5ffafd3.png)
- Notation for the first figure differs.
Original (no "Figure" indication, caption below the figure):
![image](https://user-images.githubusercontent.com/55683568/72938776-d30f1f00-3d6b-11ea-9c91-449c9aabe38d.png)
Resulted (with "Figure" indication, caption above the figure, horizontally centered):
![image](https://user-images.githubusercontent.com/55683568/72938840-f8039200-3d6b-11ea-942b-0e8599c2e58b.png)
- In section 3, second listed item shouldn't be indented twice in generated PDF.
Original:
![image](https://user-images.githubusercontent.com/55683568/72938906-1e293200-3d6c-11ea-9610-662515d84cbc.png)
Resulted:
![image](https://user-images.githubusercontent.com/55683568/72938895-17022400-3d6c-11ea-8e09-14200a47bbca.png)
- "<" and ">" signs are missing in the URL in the generated PDF.
Original:
![image](https://user-images.githubusercontent.com/55683568/72939010-53358480-3d6c-11ea-9f3c-36911f17ca5e.png)
Resulted:
![image](https://user-images.githubusercontent.com/55683568/72939028-5af52900-3d6c-11ea-9206-594ad3e58625.png)
- Numbering contained in sections in Annex I differs.
Original:
![image](https://user-images.githubusercontent.com/55683568/72939156-a0b1f180-3d6c-11ea-9a36-14c75aee162a.png)
Resulted (additional 1., 2., etc.);
![image](https://user-images.githubusercontent.com/55683568/72939183-af98a400-3d6c-11ea-9d83-85495b0354b1.png)
- Additional blank page is added before the last page in the original PDF.

**Comment by anermina** [comment]
Comparison of https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_C_CEFACT_2018_6E.doc (original DOC)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_C_CEFACT_2018_6E.pdf (resulted PDF).
------------------------
- Original DOC has an extra blank page after the front page.
- Text goes out of the margins on page 6 of the resulted PDF.
Original DOC: 
![image](https://user-images.githubusercontent.com/55683568/72939983-46199500-3d6e-11ea-9097-2307e919f8c3.png)
Resulted PDF: 
![image](https://user-images.githubusercontent.com/55683568/72939953-3601b580-3d6e-11ea-9746-a3f1d28604bc.png)

**Comment by manuel489** [comment]
Thanks @anermina  for completing this for me. In addition to @anermina 's above comparison, I found this little detail:

The `Annex` cross-reference differs by a semicolon (`:`)
Original PDF:

![diff3-original-pdf](https://user-images.githubusercontent.com/33627611/72940093-924fdf80-3d44-11ea-8eca-aa0283fadc12.JPG)


Resulted PDF:

![diff3-resulted-pdf](https://user-images.githubusercontent.com/33627611/72940129-a1cf2880-3d44-11ea-83b1-26cf2862465e.JPG)

**Comment by Intelligent2013** [comment]
I've fixed the issues in XSL, but there are a few which relates to the source xml data.

**Comparison of https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_437E_Rec42.pdf (original PDF)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_437E_Rec42.pdf (resulted PDF)**

> One paragraph and the signature are missing in Foreword.

In source XML (https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_437E_Rec42.xml) there isn't this paragraph and the signature image.

> Text which should be below the signature should also be horizontally centered.

To fix it, the element 'p' in source xml should contain attribute align="center":
```
<p id="_2bf41f7e-8518-4770-abc4-3844220757f6" align="center">Olga Algayerova<br/>
Executive Secretary<br/>
United Nations Economic Commission for Europe</p>
```

I've found that paragraph in foreword have left alignment, and I've fixed this issue and added justify alignment in XSL.


> Notation for the first figure differs.

The original PDF document contains Figure 1 without "Figure" indication, and caption below the figure:
![image](https://user-images.githubusercontent.com/5559926/72996963-a65f1400-3e0c-11ea-8f69-609c9bb90cf8.png)


and Figure 2 with "Figure 2" indication and caption above the figure:
![image](https://user-images.githubusercontent.com/5559926/72996981-ac54f500-3e0c-11ea-91e5-6bd30dae9812.png)


The source XML contains identical markup for two figures:

```
<figure id="Figure1">
<name>UNECE Recommendation n°18 illustrates a simplified view of the international supply chain in the Buy-Ship-Pay model. The model identifies the key commercial, logistical, regulatory and payment procedures involved in the international supply chain. Source: <link target="http://tfig.unece.org/contents/buy-ship-pay-model.htm"/>.</name>
<image src="data:image/png;base64,iVBORw0KGgoAAAAN...=" id="_85834035-4fca-4a9b-8c86-d396772688bb" mimetype="image/png" height="auto" width="auto"/>
</figure>
```

```
<figure id="figure2">
<name>Recommended tier of indicators and database</name>
<image src="data:image/png;base64,iVBORw0KGgo...=" id="_40a11e9c-6fd5-4632-95a2-718d4f3ffc37" mimetype="image/png" height="auto" width="auto"/>
</figure>
```

In xml there isn't indication where caption should be placed - above or below the figure, and no information about "Figure" number indication.

I've found one more difference. The original PDF contains "(Figure 1)" text in caption for first Figure, but XML doesn't.


> In section 3, second listed item shouldn't be indented twice in generated PDF.

In the source XML the second listed item placed in nested list:
![image](https://user-images.githubusercontent.com/5559926/72997086-db6b6680-3e0c-11ea-9977-dedb8f442fd1.png)


> "<" and ">" signs are missing in the URL in the generated PDF.

In source XML the URL should be enclosed in lt; and gt; entities:
`&lt;<link target="http://www.unescap.org/resources/towards-national-integrated-and-sustainable-trade-and-transport-facilitation-monitoring"/>&gt;`


The similar issue in Annex II, in section "1. Top tier indicators".


> Numbering contained in sections in Annex I differs.

Yes, the original PDF doesn't contain numbering in sections in Annex I:
![image](https://user-images.githubusercontent.com/5559926/72997125-e6be9200-3e0c-11ea-9c68-173849b618ae.png)


but in Annex II there are numbering in sections:
![image](https://user-images.githubusercontent.com/5559926/72997140-f0e09080-3e0c-11ea-864b-cffb465decdf.png)


In source XML I didn't found the difference in annex markup to determine in which case we should place section number and when shouldn't. Could you specify it in XML?



> Additional blank page is added before the last page in the original PDF.

Fixed.


> The Annex cross-reference differs by a semicolon (:)

Fixed

**Comparison of https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_C_CEFACT_2018_6E.doc (original DOC)
vs.
https://metanorma.github.io/mn-native-pdf/documents/un-ECE_TRADE_C_CEFACT_2018_6E.pdf (resulted PDF).**


> Original DOC has an extra blank page after the front page.

Fixed.

> Text goes out of the margins on page 6 of the resulted PDF.

Fixed.

**Comment by manuel489** [comment]
Remaining issues for Recommendation template posted in https://github.com/metanorma/mn-native-pdf/issues/151

**Comment by manuel489** [comment]
I didn't notice any remaining issue with Plenary template

**Comment by manuel489** [comment]
Remaining issues in this ticket are posted in https://github.com/metanorma/metanorma-un/issues/61.

Closing.
