### ISSUE TITLE
Additional fonts priority

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#612]
Source: https://github.com/metanorma/pdfa-iso-32000-2/issues/12

Currently, when user specifies the additional font name `:fonts: MS Gothic`, this font adds at the end of `font-family` into XSL-FO:
```
font-family="Cambria, Times New Roman, Cambria Math, Noto Serif, Noto Serif HK, Noto Serif JP, Noto Serif KR, Noto Serif SC, Noto Serif TC, MS Gothic"
```

Need update: font(s) should be added immediately after 1st font, for instance:
```
font-family="Cambria, MS Gothic, Times New Roman, Cambria Math, Noto Serif, Noto Serif HK, Noto Serif JP, Noto Serif KR, Noto Serif SC, Noto Serif TC"
```

**Comment by ronaldtse** [comment]
Good point but let's take a broader view. 

1. Are there situations where we want to redefine the order of the fonts?
2. How are these fonts rendered / embedded in the artifacts? I know PDF support embedding, but how about Word and HTML? (There are font licensing concerns if embedding needs to happen?)
3. How do we deal with selective encoding of particular characters? We had that situation with the WorldWeatherSymbols in OGC, which is an icon font. Say someone wants to use icons from Font Awesome, what do we do?

**Comment by opoudjis** [comment]
1: Don't think so.

2: There is no support currently for font embedding: if the recipient does not have the required font, it doesn't render.

Given the font licensing concerns, I don't think we *want* to do font embedding in HTML and Word. 

3. is the ongoing issue about specifying font style of text in markup, so it does not need to be discussed here.

**Comment by opoudjis** [comment]
@Intelligent2013 I didn't realise you've already implemented this, and I couldn't see what action was expected on me. OK to close this?
