### ISSUE TITLE
Editor: do NIST document review

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#63]
@anermina if you can't get to this, pass it on to @manuel489 

The mn-sample-nist folder is in gitlab; ask @ronaldtse if you don't already have access to it.

**Comment by anermina** [comment]
There were a lot of ITU documents to check, and I have 8 more to go. @manuel489 did you finish yours? If yes, can you please take this task too?

**Comment by manuel489** [comment]
Yeah, actually I was working on it already :wink:. My reviews for NIST docs are posted here: https://gitlab.com/metanorma/mn-native-pdf-nist/issues/4
