### ISSUE TITLE
PDF: experimental feature - vertical layout

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#713]
Need add support for vertically oriented text for Japanese documents, for instance:
![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/05dc68e2-0b06-4892-bd72-1ab0b1dc4f73)
(example from https://www.antennahouse.com/hubfs/xsl-fo-sample/language/writing-mode-1.pdf)

Apache FOP doesn't support a vertical direction property (`tb-rl`), see https://xmlgraphics.apache.org/fop/2.9/complexscripts.html#writing_mode_property.

Need try to check that Japanese vertical layout can be achieved with two steps:
- turn each character in 90 degrees
- turn page in 90 degrees

**Comment by Intelligent2013** [comment]
> turn each character in 90 degrees

In XSL-FO there `reference-orientation` property, but it relates to the 'area', not for one glyph (https://www.w3.org/TR/2001/REC-xsl-20011015/xslspec.html#reference-orientation).

(In AH there is `glyph-orientation` property https://www.antennahouse.com/hubfs/xsl-fo-sample/character/glyph-orientation-1.pdf?hsLang=en)

There is one more idea - replace each character by SVG with text rotating instruction:
```xml
<svg xmlns="http://www.w3.org/2000/svg">
  <text transform="rotate(90)">B</text>
</svg>
```

**Comment by Intelligent2013** [comment]
I've tried to replace each character to the SVG with rotated text (one character):
```xml
<fo:instream-foreign-object fox:alt-text="{.}">
<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15">
<text font-size="14pt" transform="rotate(-90,15,0)"><xsl:value-of select="."/></text></svg>
</fo:instream-foreign-object>
```
and the resulted PDF looks so:
(Note: I know that some English letters didn't rotated.)

![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/f9e9bec6-27a0-4da4-8767-d1bdb94366a0)
Issues: 
- too small space between glyph, need to increase it (emulate font glyph distance via SVG property?)
- English glyphs didn't aligned horizontally

![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/2f585374-c11d-4086-a741-c4f39dfb8fc4)
- overlapped bottom page margin (looks like it's Apache FOP bug, I don't figure out how to fix it)

![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/ab08ddb3-5fa5-44fd-be2a-1e2bbecfc1e6)

- wrong PDF comments position

- I don't sure at all that table auto-layout algorithm will be work properly.

So, this approach is waste of time. It generates a bunch of bugs. Emulate glyph properties via SVG markup is very complicated idea.

**Comment by Intelligent2013** [comment]
from @ronaldtse:
> There is a Apache FOP fork that supports vertical layout:
> https://github.com/chunlinyao/fop

@ronaldtse I've tried to generate the example PDF by this FOP fork. The resulted PDF contains characters that are not rotated. I.e.:
- original (https://github.com/chunlinyao/fop/blob/yao/sample.pdf):
![image](https://github.com/user-attachments/assets/e827b87d-34a2-4a9d-ad3a-1baacd1329c4)


- generated ([test.yao2.pdf](https://github.com/user-attachments/files/16874357/test.yao2.pdf))
![image](https://github.com/user-attachments/assets/b32ff553-58af-4d5e-a4f8-6279aeecfaa3)

I'll try another branches in the repo.

**Comment by ronaldtse** [comment]
@Intelligent2013 there are only two branches there, `main` and `yao`. See if they work? I doubt that the author was just faking it

**Comment by ronaldtse** [comment]
The forked code probably needs fixing, the commits made to enable vertical layout are here:
* https://github.com/metanorma/mn-native-pdf/issues/713

There is one more important concept in the sample (https://raw.githubusercontent.com/chunlinyao/fop/yao/vertical.png).

The last paragraph that is not boxed, is called "horizontal in vertical", where you can see the English text being placed in horizontal form.

There are actually 3 types of embedding latin text inside a vertical layout:
1. Individual Latin characters printed in one vertical box each.
2. A Latin phrase squeezed to fit into one vertical box.
3. A Latin phrase rotated 90 degrees (so you have to read it sideways), crossing multiple vertical boxes.

**Comment by Intelligent2013** [comment]
> I'll try another branches in the repo.

- `yao` (default branch) - build error
- `yao-2_6` - not rotated characters
- `yao-2_9` - not rotated characters


> actually only the `yao` branch contains the commits:

also `yao-2_6`, `yao-2_7` and `yao-2_9` have the same commits:
![image](https://github.com/user-attachments/assets/b9fc38b4-5890-4de0-9347-ba9472272357)

### Difference in the PDF meta information:

`sample.pdf` properties:
![image](https://github.com/user-attachments/assets/01fdedbc-23c4-4448-b8cb-2e7e80ed4a49)
- year `2020`, it means the PDF generated in the Apache FOP version 2.5 or less
- Apache FOP version `SVN`

My generated PDF:
![image](https://github.com/user-attachments/assets/f6c9238d-f0e3-45c2-bc62-f7c8f49f3a82)

- Apache FOP version `2.9.0-SNAPSHOT`

The Apache FOP version found in the file `pom.xml` - `<version>2.9.0-SNAPSHOT</version>`. I didn't find the `pom.xml` with `<version>SVN</version>`.



> The forked code probably needs fixing, the commits made to enable vertical layout are here:
> * https://github.com/metanorma/mn-native-pdf/issues/713

The link points to this issue.

> There are actually 3 types of embedding latin text inside a vertical layout:

The source XSL-FO for sample.pdf is `https://github.com/chunlinyao/fop/blob/yao/fop/examples/fo/japanese/vertical_writing.fo`

> 1. Individual Latin characters printed in one vertical box each.

`reference-orientation="90"`

```xml
<fo:inline-container writing-mode="lr-tb" text-align="center"
                                       alignment-baseline="central" reference-orientation="90" width="1em" margin="0" padding="0"
                                       text-indent="0mm" last-line-end-indent="0mm" start-indent="0mm" end-indent="0mm">
                <fo:block-container width="1em">
                    <fo:block line-height="1em">29</fo:block>
                </fo:block-container>
            </fo:inline-container
```
> 2. A Latin phrase squeezed to fit into one vertical box.

I can't find this sample.

> 3. A Latin phrase rotated 90 degrees (so you have to read it sideways), crossing multiple vertical boxes.

The text `JIS X 4051` just inline in Japanese text: 
```xml
<fo:block margin-top="1em">
                縦中横（たてちゅうよこ）は、縦組みの文書の中で横組みすることである。読みは「たてちゅうよこ」であり、「たてなかよこ」ではない（JIS X 4051で規定）。縦組みの行の中で数文字（通常2、3文字。まれに4文字以上）の欧字や数字を、1文字分の高さで左横書きに配置する。
                縦中横を用いる場合、前の文字と後ろの文字の間に空白は開けず、行の中心が、縦中横全体の中心にくるように文字を配置する。また、縦中横の中の文字数が多い場合、それぞれの文字の幅を文字数に応じて三分（さんぶ。通常の文字の幅の3分の1）や四分（しぶ。同4分の1）などとすることで、縦中横にした箇所の幅が前後の文字と揃うように配慮する。
            </fo:block>
```

I've tried to copy-paste the text from 1st column (page1) and 1st row (page2) into the Word:

![image](https://github.com/user-attachments/assets/5b8e1636-591d-44b2-9a10-db9aa2de1946)

Some characters from page 1 render as 'block', i.e. not exist the the font.

It's puzzle for me.....

**Comment by Intelligent2013** [comment]
Fork supports `fox:shrink-to-fit` feature. My compiled .jar result:
- 1st - without `fox:shrink-to-fit`
- 2nd and 3rd - with `fox:shrink-to-fit`

![image](https://github.com/user-attachments/assets/824b882b-4a98-49b4-867d-9e64ce78cff6)


Ruby characters renders in the standard Apache FOP 2.9. Need to use the special `fo:inline-container` attributes:
```
<fo:block font-size="18pt">XMLとは<fo:inline-container width="2em" text-indent="0mm" last-line-end-indent="0mm" alignment-baseline="central">
    <fo:block font-size="0.4em" text-align="center" line-height="1.2em" space-before="-1.4em" space-before.conditionality="retain">じょほう</fo:block>
    <fo:block line-height="1em">情報</fo:block>
  </fo:inline-container>を<fo:inline-container width="2em" text-indent="0mm" last-line-end-indent="0mm" alignment-baseline="central">
    <fo:block font-size="0.4em" text-align="center" line-height="1.2em" space-before="-1.4em" space-before.conditionality="retain">ひょうげん</fo:block>
    <fo:block line-height="1em">表現</fo:block>
  </fo:inline-container>するための<fo:inline-container width="1.2em" text-indent="0mm" last-line-end-indent="0mm" alignment-baseline="central">
    <fo:block font-size="0.4em" text-align="center" line-height="1.2em" space-before="-1.4em" space-before.conditionality="retain">あたら</fo:block>
    <fo:block line-height="1em">新</fo:block>
  </fo:inline-container>しい<fo:inline-container width="2em" text-indent="0mm" last-line-end-indent="0mm" alignment-baseline="central">
    <fo:block font-size="0.4em" text-align="center" line-height="1.2em" space-before="-1.4em" space-before.conditionality="retain">ほうほう</fo:block>
    <fo:block line-height="1em">方法</fo:block>
  </fo:inline-container>です。</fo:block>
</fo:block>
```
![image](https://github.com/user-attachments/assets/2cca36cf-9838-4c00-aaa0-75b1f8ded11a)

**Comment by Intelligent2013** [comment]
My fault. The vertical layout feature in the https://github.com/chunlinyao/fop/commits/yao depends on [Complex Scripts](https://xmlgraphics.apache.org/fop/2.9/complexscripts.html) feature, that turned-off in https://github.com/metanorma/mn-samples-plateau/issues/168. I have to revise it.

With complex-script feature the characters rotated correctly:
![image](https://github.com/user-attachments/assets/0a39d566-c916-4eb5-aa00-95b98108122d)

**Comment by ronaldtse** [comment]
@Intelligent2013 thats great to know. 

In this case, we need to fix the original issue of bad character replacement?

**Comment by Intelligent2013** [comment]
> In this case, we need to fix the original issue of bad character replacement?

@ronaldtse yes.

**Comment by alex-sc** [comment]
TBH, I don't like the way the horizontal in vertical text is implemented

```xml
<fo:inline-container writing-mode="lr-tb" text-align="center"
                                       alignment-baseline="central" reference-orientation="90" width="1em" margin="0" padding="0"
                                       text-indent="0mm" last-line-end-indent="0mm" start-indent="0mm" end-indent="0mm">
                <fo:block-container width="1em">
                    <fo:block line-height="1em">29</fo:block>
                </fo:block-container>
            </fo:inline-container>
```

but Antenna is doing it similarly, so this is likely the way to go

```xml
<fo:block-container writing-mode="tb" height="18em" xml:lang="ja" line-height="1.4" axf:punctuation-trim="all" axf:text-autospace="none" axf:text-autospace-width="0">
<fo:block text-indent="1em">縦書きの中に「<fo:inline-container writing-mode="lr" text-align="center" text-indent="0" line-height="1em" color="blue">
<fo:block>'08</fo:block>
</fo:inline-container>年<fo:inline-container xml:lang="en" writing-mode="lr" text-align="center" text-indent="0" line-height="1em" color="blue">
<fo:block>12</fo:block>
</fo:inline-container>月<fo:inline-container writing-mode="lr" text-align="center" text-indent="0" line-height="1em" color="blue">
<fo:block>8</fo:block>
</fo:inline-container>日」のように部分的に数字などを横書きにすることを「縦中横」といいます。</fo:block>
</fo:block-container>
```

https://www.antennahouse.com/hubfs/xsl-fo-sample/line/tatechuyoko-1.pdf?hsLang=en

https://www.antennahouse.com/hubfs/xsl-fo-sample/line/tatechuyoko-1.zip?hsLang=en

**Comment by Intelligent2013** [comment]
The next task is very accurate integrating the changes from [https://github.com/chunlinyao/fop] (https://github.com/chunlinyao/fop/commits/yao) into the `mn2pdf`.

**Comment by Intelligent2013** [comment]
To enable the version layout I propose to use the document attribute:
```
:presentation-metadata-vertical-layout: true
```

From @ronaldtse:
>  I guess we just need some syntax to indicate that clause numbers should be vertically placed as well. 

```
:presentation-metadata-vertical-layout-rotate-clause-numbers: true
```

**Comment by Intelligent2013** [comment]
Vertical layout feature available in Plateau XSLT and supported `mn2pdf` `v1.99` (https://github.com/metanorma/mn2pdf/releases/tag/v1.99)

Add the document attribute `:presentation-metadata-vertical-layout-rotate-clause-numbers: true` to enable the vertical layout.

Next tasks:
- [ ] support `:presentation-metadata-vertical-layout-rotate-clause-numbers: true`
- [ ] fix issue with page numbers - wrong page margins in the rotated pages
![image](https://github.com/user-attachments/assets/37475cc3-d739-4992-9c7c-cac33b50dd39)

**Comment by ronaldtse** [comment]
@Intelligent2013 @opoudjis I think we should expose the vertical layout into Metanorma properly. Maybe as a PDF specific feature for now? I know CSS (and Word) also supports vertical layout, but that will be later.

I am hoping to provide a vertical layout example using an experimental JIS layout.

**Comment by Intelligent2013** [comment]
Closing. The further developments see in https://github.com/metanorma/metanorma-jis/issues/226.
