### ISSUE TITLE
passthrough code added to PDF XSLT

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#764]
As part of https://github.com/metanorma/isodoc/issues/609 , I request that the following XSLT be added to mn-native-pdf core, so that I do not need to do is as XSLT preprocessing for PDF:

````
<xsl:template match="*[local-name() = 'passthrough']">
      <xsl:if test="contains(@formats, ',pdf,')"> 
                <xsl:copy><xsl:apply-templates select="@* | node()"/></xsl:copy>
      </xsl:if>
</xsl:template>
````

The intent is that an element `<passthrough formats=",html,pdf,">ABC</passthrough>` will be rendered in PDF through its contents, and an element `<passthrough formats=",html,doc,">ABC</passthrough>` will be ignored. (I will be inserting the "," either side of the formats string.)

I don't believe this has ever been used, but just in case.

**Comment by Intelligent2013** [comment]
To do:
- [ ] add into `common.xsl`
```xml
<xsl:template match="*[local-name() = 'passthrough']" mode="update_xml_step1">
      <xsl:if test="contains(@formats, ',pdf,')"> 
                <xsl:apply-templates select="@* | node()" mode="update_xml_step1"/>
      </xsl:if>
</xsl:template>
```

- [ ] add into `bipm.brochure.core.xsl`:
```xml
<xsl:template match="*[local-name() = 'passthrough']" mode="flatxml">
      <xsl:if test="contains(@formats, ',pdf,')"> 
                <xsl:apply-templates select="@* | node()" mode="flatxml"/>
      </xsl:if>
</xsl:template>
```

**Comment by ronaldtse** [comment]
Question: why is this in BIPM?

@opoudjis `,html,pdf,` is supremely weird. If you wanted delimiters, just use an empty space.

**Comment by ronaldtse** [comment]
@Intelligent2013 shouldn't we move this issue to the mn2pdf repo instead?

**Comment by Intelligent2013** [comment]
> Question: why is this in BIPM?

@ronaldtse BIPM XSLT has a special pre-processing step for flattening the XML for the side notes rendering. I.e. hierarchical Presentation XML structure transforms to the linear structure with one level depth. This transformation occurs in the templates with `mode="flatxml"`. This is the best place to add the element `passthrough` transformation.
Another XSLTs have the pre-processing step `update_xml_step1` for the element ordering based on `@displayorder`, some element removing (`image/emf`, `metanorma-extension/metanorma/source`) for the memory consumption optimization, etc. Therefore, `passthrough` processing added there.

**Comment by opoudjis** [comment]
> Question: why is this in BIPM?
> 
> @opoudjis `,html,pdf,` is supremely weird. If you wanted delimiters, just use an empty space.

You heard the man, @Intelligent2013 . Make it `<xsl:if test="contains(@formats, ' pdf ')"> `

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 . The point is we want to remove format specific processing from the Semantic/Presentational XML as much as possible and keep the format specific processing at the renderers in order to have a clean separation of concerns.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/mn-native-pdf/pull/765.

**Comment by opoudjis** [comment]
> I think the condition without any separators around key will be work more robust: `<xsl:if test="contains(@formats, 'pdf')">`.

The problem is that you can't guarantee there isn't in future a format "pdfa" or "xpfd". We already have both "sts" and "isosts". I'd rather you use the spaces, and I'm putting the spaces in to the XML (replacing the commas)...

**Comment by Intelligent2013** [comment]
Ok, agree. Fixed.

**Comment by opoudjis** [comment]
Need this incorporated in tomorrow's release as well, @Intelligent2013
