### ISSUE TITLE
Implement ISO FDIS layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#97]
The attached file contains the 2 cover pages, table of contents, and back cover.
[iso-cover-fdis.pdf](https://github.com/metanorma/mn-native-pdf/files/4413693/iso-cover-fdis.pdf)

**Comment by ronaldtse** [comment]
FDIS layout also implements a special header on the first content page:
<img width="614" alt="Screen Shot 2020-04-01 at 4 48 13 PM" src="https://user-images.githubusercontent.com/11865/78117722-94b37180-7438-11ea-9f65-85687c9d5214.png">

**Comment by Intelligent2013** [comment]
@ronaldtse FYI, in xml there aren't info for:
![image](https://user-images.githubusercontent.com/5559926/78812541-3ce6ae80-79d4-11ea-81eb-cc0e6fbdb484.png)

**Comment by ronaldtse** [comment]
We need to make a provision for them. If the dates exist in the document, show them. If the dates don't exist, show some placeholder. Let's make an issue that metanorma-iso needs to support these two voting dates.

**Comment by Intelligent2013** [comment]
Done. Resulted PDF:
https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/iso-rice-en.covers.fdis.pdf

**Comment by Intelligent2013** [comment]
To do: Add voting  dates.

**Comment by Intelligent2013** [comment]
> We need to make a provision for them. If the dates exist in the document, show them. If the dates don't exist, show some placeholder. Let's make an issue that metanorma-iso needs to support these two voting dates.

Voting dates processing added.

When the dates exist in the document:
![image](https://user-images.githubusercontent.com/5559926/80960220-23892480-8e11-11ea-9e6a-801de820b55d.png)



When the dates don't exist:
![image](https://user-images.githubusercontent.com/5559926/80960063-c5f4d800-8e10-11ea-8689-45e55cdba906.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 instead of XXXX-xx-xx can we use YYYY-MM-DD ?

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 instead of XXXX-xx-xx can we use YYYY-MM-DD ?

Modified:
![изображение](https://user-images.githubusercontent.com/5559926/81004420-0fffad00-8e55-11ea-8bd0-c72ac2bd1ed3.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
