### ISSUE TITLE
Implement ISO PROOF layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#98]
Difference from FINAL:

- every content page (all pages except front cover page) has "PROOF/ÉPREUVE" in the footer center, bolded
- front page contains large print of "PROOF/ÉPREUVE"

![iso-cover-proof-1](https://user-images.githubusercontent.com/11865/78117452-4900c800-7438-11ea-83aa-8b9fefa48bc4.png)
![iso-cover-proof-2](https://user-images.githubusercontent.com/11865/78117460-4a31f500-7438-11ea-9351-2a858b136a7f.png)
![iso-cover-proof-3](https://user-images.githubusercontent.com/11865/78117465-4aca8b80-7438-11ea-8879-f0ded4887f31.png)
![iso-cover-proof-4](https://user-images.githubusercontent.com/11865/78117470-4bfbb880-7438-11ea-9509-1a552f90e340.png)

**Comment by opoudjis** [comment]
@ronaldtse Is this functionality, and that of the other tickets you've been assigning for ISO, going to be replicated in the Word version?

I consider it dangerous not to. Unless you deprecate DOC output in ISO.

**Comment by ronaldtse** [comment]
No, this is only for PDF. The DOC output is meant for ISO submission.

**Comment by Intelligent2013** [comment]
@ronaldtse  Looks like in all xml there isn't data for the footer on the last page:
**ICS 35.240.63**

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Resulted PDF:
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.prf.pdf

**Comment by ronaldtse** [comment]
<img width="414" alt="Screen Shot 2020-04-10 at 10 21 31 AM" src="https://user-images.githubusercontent.com/11865/78956495-0e242180-7b15-11ea-8d16-5c7e1fd6a727.png">

The document ID on top right should not have `PRF`

**Comment by Intelligent2013** [comment]
@ronaldtse 

> The document ID on top right should not have `PRF`

I read the document ID from elememtn `<docidentifier type="iso">` and it contains '/PRF' substring. Should I cut '/PRF' substring or use something other element?

**Comment by ronaldtse** [comment]
In this case it is an xml bug, can you file ticket for metanorma-ISO? Thanks!

**Comment by opoudjis** [comment]
I am no longer adding /PRF suffix in doc id.

**Comment by Intelligent2013** [comment]
@opoudjis Thank you!
