### ISSUE TITLE
Implement ISO Published layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#99]
See https://standards.iso.org/ittf/PubliclyAvailableStandards/C076797_ISO_IEC_23736-6_2020(E).zip

**Comment by ronaldtse** [comment]
There is a special header on the first content page:

<img width="909" alt="Screen Shot 2020-04-01 at 4 49 32 PM" src="https://user-images.githubusercontent.com/11865/78117874-c4627980-7438-11ea-898c-0f40a3f3a357.png">

**Comment by Intelligent2013** [comment]
@ronaldtse Done. Resulted PDF:
https://github.com/metanorma/mn-native-pdf/raw/gh-pages/documents/iso-rice-en.covers.final.pdf

**Comment by ronaldtse** [comment]
Thanks, LGTM!
